### ISSUE TITLE
Support `git pull --rebase origin some-branch`

### ISSUE THREAD

**Issue by drmercer-lucid** [pcottle/learnGitBranching#1004]
**Expected behavior:** this sequence of commands works:

```
git clone
git fakeTeamwork
git commit
git pull --rebase origin main
```

**Actual behavior:**

```
$ git clone

local branch "main" set to track remote branch "o/main"

$ git fakeTeamwork

$ git commit

$ git pull --rebase origin main

main is not a remote in your repository! try adding origin to that argument
```

**Note:** omitting the last two arguments to `git pull --rebase` works as expected, and `git pull origin main` (i.e. without rebase) works to do a merge-pull. So I think there's a specific problem with parsing the `<repository>` and `<branch>` arguments when `--rebase` is supplied.

**Comment by pcottle** [comment]
yeah let me check -- dropping just one argument works too:
https://learngitbranching.js.org/?NODEMO&command=git%20checkout%20-b%20foo;%20git%20clone;%20git%20fakeTeamwork%20foo;%20gc;%20git%20pull%20--rebase%20foo

**Comment by pcottle** [comment]
this is due to my incredibly horrible argument parsing logic that attaches `origin` to the `--rebase` option rather than including it in general args :P

added a test for now!
