### ISSUE TITLE
[Bug]: Locked Main

### ISSUE THREAD

**Issue by mg901** [pcottle/learnGitBranching#1019]
Hi! If I run the command from your  solution `git checkout -b feature C2` and `git push origin feature` I get this result.

![image](https://user-images.githubusercontent.com/7874664/194582257-3bf0f8ac-4e39-4ee8-b5f9-6261ea878384.png)

This is a bug? Or that I am doing wrong?

P.S. Thanks in advance.

**Comment by bbcbear** [comment]
git branch -f main c1

**Comment by pcottle** [comment]
That's the expected result based on those commands, but it's not sufficient to solve the level. The very last bit of the tutorial for this level mentions needing to reset your main branch backwards:

> Create another branch called feature and push that to the remote. Also reset your main back to be in sync with the remote otherwise you may have issues next time you do a pull and someone else's commit conflicts with yours.
