### ISSUE TITLE
[Bug] no error thrown for "git gc"

### ISSUE THREAD

**Issue by ulyssear** [pcottle/learnGitBranching#1021]
I accidentally wrote "git gc" instead of "gc" or "git commit". However, I didn't get any errors in the terminal. I will take care of this issue which should be simple to fix.

EDIT : In case "git gc" is a feature, then the commit is not created after running the command.

![image](https://user-images.githubusercontent.com/11415595/194815135-5a244aec-c7bb-4c54-8c5c-8e290956756d.png)

**Comment by ulyssear** [comment]
i just forgot the git-gc my bad ^^'

**Comment by thetayloredman** [comment]
I added this in #957, it just cleans up any of the orphan commits in case you get a mess of them.
