### ISSUE TITLE
Progress can`t be saved

### ISSUE THREAD

**Issue by vOrlovItomych** [pcottle/learnGitBranching#1032]
Hello! Hope you are well. 
Thanks for your education platform, great job! But looks like we found a bug. From today, it don't save any lessons, what we trying to pass. Level board remains grey after completing any level.

**Comment by pcottle** [comment]
Thanks for the kind words and reporting this bug. I don't think we have lost this data but it's simply a styling issue, this is probably related to #1030 (cc @ulyssear)

I think we need to update this line:
https://github.com/pcottle/learnGitBranching/blob/main/src/js/views/levelDropdownView.js#L405

**Comment by pcottle** [comment]
Fixed this in 6442e770f1aea68e395ccb59ba85c18d7e6a7c61, pushing the site now!

**Comment by pcottle** [comment]
<img width="1269" alt="Screen Shot 2022-10-21 at 12 04 12 PM" src="https://user-images.githubusercontent.com/1135007/197260611-673882e2-d74d-41f2-b27c-cfe84b5be076.png">
its back :)

**Comment by vOrlovItomych** [comment]
Thank you so much! Now it's awesome)
