### ISSUE TITLE
Premature completion of the task

### ISSUE THREAD

**Issue by keystaff** [pcottle/learnGitBranching#1044]
Hi!

I found that on lesson "Juggling Commits #2" (level 4, lesson 3) if you type `git checkout main` and `git cherry-pick C2 C3` then the task will be done, but we doesn't have the second apostrophe on C2 commit, as it's displayed in the solution:

![one](https://user-images.githubusercontent.com/56756931/208639400-3ef40124-28ed-4890-b5cc-8503cce89ba9.png)
![two](https://user-images.githubusercontent.com/56756931/208639419-5926fff1-3ac9-4592-93aa-4a58940c4cf3.png)

**Comment by pcottle** [comment]
Yeah this was done intentionally to allow a wider variety of solutions, but I just changed the assert to enforce that C2 has more amends than C3. this will make the above no longer solve the level, but prevent some other valid solutions as well (in terms of what this level is trying to teach you)

**Comment by hong4rc** [comment]
Please check this commit work for https://github.com/pcottle/learnGitBranching/issues/487

https://github.com/pcottle/learnGitBranching/commit/85ae115fc20da020bde4976b783d1b324b12f60f
