### ISSUE TITLE
Level Builder hangs when trying to edit dialog

### ISSUE THREAD

**Issue by fk3** [pcottle/learnGitBranching#1045]
When using the level builder and trying to create a dialog, a window appears with the Buttons to add a modal view or a git demonstration view. But clicking the buttons does not do anything, not even cancel works, i.e. the edit-dialog-window basically "hangs" and I need to refresh the browser page.

Reproduction steps:
> build level
> edit dialog

(issue is also present when actually building a level, but editing the dialog right at the start is faster to show the issue)

**Comment by pcottle** [comment]
Good catch! Yeah this broke when there was a migration to use `button` elements instead of `div`s, which meant some click handlers broke
