### ISSUE TITLE
'Cancel' Button in the Interactive Rebase Window still results in the successful message

### ISSUE THREAD

**Issue by shreyas3156** [pcottle/learnGitBranching#1058]
First, thank you so much for this one-of-a-kind learning experience! I have used git commands in bits and parts before, but going through the levels on this website has finally made me confident.

**Issue**: When navigating through the instructions in the 'Interactive Rebase' Level, the final stage of Git Demonstration opens the window with Pick and Omit options for several commits, along with the buttons 'Cancel' and 'Confirm'. 
![learnGit2](https://user-images.githubusercontent.com/125031481/219874702-02e701fc-2184-4d63-8b25-ecf628544ee6.png)

Upon clicking the 'Cancel' button, it still shows the 'Boom! Git copied down commits..' message as shown below. 
![learnGit3](https://user-images.githubusercontent.com/125031481/219874942-f698ffc9-26c2-4fb2-8e97-a08c0235e06b.png)

I think the successful message can be shown when clicking the confirm button, but not with the 'Cancel' button.

**Comment by pcottle** [comment]
Yeah this is an unfortunate edge case, since we don't expect you to really cancel the command we are trying to teach you during the dialog. I'll see if maybe I can just disable the command button in that case.

**Comment by pcottle** [comment]
<img width="1187" alt="Screenshot 2023-02-19 at 4 40 47 PM" src="https://user-images.githubusercontent.com/1135007/219982495-e075809b-fa67-48e9-b9d4-db374b513202.png">
