### ISSUE TITLE
Level Relative Refs #2 could use more elaboration

### ISSUE THREAD

**Issue by abeburnett** [pcottle/learnGitBranching#109]
First of all, thank you so much for creating this intuitive way to learn and understand Git branching. This is an awesome learning tool. 

My issue is that I go through the first 6 lessons and then hit lesson 7 (Relative Refs #2) and hit a brick wall. I get the general idea of how '~' can be used to jump up many levels at once, but using it in the context of the given exercise doesn't make any sense to me. I don't have a clue how to begin. 

I'd suggest elaborating on this lesson and making the given examples hew closer to what will be required for completing the exercise...maybe even split this lesson into two lessons which cover the material at greater length (maybe an easier exercise followed by a harder exercise). As it is since I don't have any clue how to use the lesson material to complete the exercise, I can't move past the lesson. And worse, I don't understand the concepts shared. 

Thanks again!

**Comment by Chad813** [comment]
didn't know you could force branch to a commit that hasn't been made yet.  how do you do that without knowing the hash??
and why does checking out bugFix at c5 and committing make a c7 and not a c6??  more questions than answers.
