### ISSUE TITLE
fakeTeamwork command for creating a branch and adding commits is not working!

### ISSUE THREAD

**Issue by TonyStark-47** [pcottle/learnGitBranching#1091]
### In Level : Remote : Faking Teamwork -

**The command shown in animation `git fakeTeamwork foo 3` works well in animation but not in terminal.**

![Screenshot from 2023-07-28 23-20-00](https://github.com/pcottle/learnGitBranching/assets/73957207/db1679e9-04eb-4277-8a60-93fe760853df)
![Screenshot from 2023-07-28 23-20-11](https://github.com/pcottle/learnGitBranching/assets/73957207/4daf7673-30cd-4eb9-a02a-ea9b8782aac7)

### In terminal, it shows the error:

![Screenshot from 2023-07-28 23-22-58](https://github.com/pcottle/learnGitBranching/assets/73957207/1d412af4-aa70-4c8e-b9b4-0c1beb790a5e)

**By the way, `git fakeTeamwork` and `git fakeTeamwork main 3` are working!**

**Comment by pcottle** [comment]
That's because the "foo" branch has to exist on the origin. Try the same command with "main" instead, or make the foo branch on origin :)

**Comment by TonyStark-47** [comment]
Yeah! Now it's working. Thank you for helping!
And sorry for the inconvenience.
