### ISSUE TITLE
o/main is not synced when doing `git pull origin main:main`

### ISSUE THREAD

**Issue by cirex-web** [pcottle/learnGitBranching#1124]
Is this supposed to be the case? (testing on actual git seems to have the remote tracking branch synced as well after running the above command) 
(I also asked on [this stackoverflow post](https://stackoverflow.com/a/53859568/13171687) that talks about this command)
<img width="676" alt="image" src="https://github.com/pcottle/learnGitBranching/assets/57322506/2b831486-d480-4ac7-929a-ede377105f35">

Before: ![image](https://github.com/pcottle/learnGitBranching/assets/57322506/2949cccb-752b-4dca-97d6-4fffd3289f2b)
After: ![image](https://github.com/pcottle/learnGitBranching/assets/57322506/af300839-30e2-40b6-b4b5-c5bc0c7a90bb)

**Comment by pcottle** [comment]
Yep that's the intended behavior when you specify a full set of arguments like that; the very last lesson explains this:
<img width="885" alt="Screenshot 2024-01-13 at 3 25 15 PM" src="https://github.com/pcottle/learnGitBranching/assets/1135007/764c8631-43a0-454e-8da8-975d3f5ad63d">
<img width="898" alt="Screenshot 2024-01-13 at 3 26 11 PM" src="https://github.com/pcottle/learnGitBranching/assets/1135007/0c6da36d-33cc-401e-879e-bac45a733921">
<img width="890" alt="Screenshot 2024-01-13 at 3 26 35 PM" src="https://github.com/pcottle/learnGitBranching/assets/1135007/28d35377-097e-492e-aa1a-d2f073d78ab2">


I'm not entirely sure why git just doesn't automatically update `o/main` for you in this case (I can't think of a time where you want `o/main` to diverge from the commits you have locally for the origin version of main) but you can fix it with a single command of `git fetch origin main` afterwards

**Comment by cirex-web** [comment]
so is this comment wrong?
![image](https://github.com/pcottle/learnGitBranching/assets/57322506/7bd7a135-5a41-467b-9ebb-6278e21bc94a)

**Comment by pcottle** [comment]
So I think there are a few things going on:

1) is the git simulator currently working as designed for the lessons? Yes, I don't think it's a recent regression or it prevents levels from being completed

2) should pulling always update the origin tracking branch even if you provide an argument? Probably (even if it doesn't in the simulator)

I started this project over a decade ago so it's very likely that either I missed this detail while implementing or maybe old versions of git didn't do this

**Comment by pcottle** [comment]
Anyways if you can find anything in the docs that confirm this, we can work on implementing the change
