### ISSUE TITLE
Rebase Introduction is incorrect (git 2.42.0)

### ISSUE THREAD

**Issue by david-morris** [pcottle/learnGitBranching#1125]
According to Learn Git Branching > Rebase Introduction we can use
![image](https://github.com/pcottle/learnGitBranching/assets/5530960/33bf2786-f192-4028-a6b7-82f665aacb23)

to achieve
![image](https://github.com/pcottle/learnGitBranching/assets/5530960/45b696a4-2f14-45fa-9d13-897d4e3f3b02)

However, when I use git 2.42.0 I get the following:
![image](https://github.com/pcottle/learnGitBranching/assets/5530960/085d6f64-456d-44a7-9fed-25bf5159b6e8)

Does this work for others when rebasing against local branches?

**Comment by david-morris** [comment]
Yes.  Looking up the way to get this goal state was actually the only reason I tried this project.

The current answer is to be on `main` and run `git rebase HEAD bugFix` by the way.

**Comment by eatdrinksleepcode** [comment]
The behavior of git in this scenario has not changed. LearnGitBranching shows the correct end state for this series of commands. Using git 2.42.1:

```shell
❯ git commit --allow-empty -m "C0"
[main (root-commit) 03fde4b] C0
❯ git commit --allow-empty -m "C1"
[main 195cff0] C1
❯ git co -b bugFix
Switched to a new branch 'bugFix'
❯ git commit --allow-empty -m "C2"
[bugFix 7f80028] C2
❯ git co main
Switched to branch 'main'
❯ git commit --allow-empty -m "C3"
[main faa100c] C3
❯ git co bugFix
Switched to branch 'bugFix'
❯ git rebase main
Successfully rebased and updated refs/heads/bugFix.
```

produces this graph:

```shell
* 2024-04-02 17:58 (Tue) a3e4e16 (HEAD -> bugFix) C2 <David Nelson>
* 2024-04-02 17:59 (Tue) faa100c (main) C3 <David Nelson>
* 2024-04-02 17:58 (Tue) 195cff0 C1 <David Nelson>
* 2024-04-02 17:58 (Tue) 03fde4b C0 <David Nelson>
```

**Comment by david-morris** [comment]
Thanks for doing that additional research!

Given that information, I think this is probably a problem with the kafkaesque build environment we use.
