### ISSUE TITLE
level remoteAdvanced3 branch naming not in assignment but required

### ISSUE THREAD

**Issue by AngeloThys** [pcottle/learnGitBranching#1128]
In level *remoteAdvanced3* it doesn't specify a different branch should be used, but is intuited.

However, the solution does not accept any name other than the one provided in the *goal* or *solution*, making the level not solvable without using of the goal as a hint.

The following example not being accepted as a valid solution:

![image](https://github.com/pcottle/learnGitBranching/assets/91565194/db9ed0a6-4116-4c3d-8b0e-1c7b0a4bc21f)

```bash
$ git checkout -b foo o/main
local branch "foo" set to track remote branch "o/main"
$ git commit
$ git pull --rebase
$ git push
```

Not sure if this is intended behaviour or not.

P.S. Thank you for this amazing resource 🙇🏼‍♂️ , and making it available to all ❤️

**Comment by pcottle** [comment]
Thanks for the kind words :) and good point! I think that's what this silly sentence at the end is implying (that you have to figure out the branch name should be `side`):
<img width="968" alt="Screenshot 2024-02-19 at 3 39 41 PM" src="https://github.com/pcottle/learnGitBranching/assets/1135007/1f335add-a0c4-4caa-91dd-84c62db24904">

but thats not a very satisfying thing to figure out or learn. Ill update the levle

**Comment by pcottle** [comment]
Updated to this:
<img width="1218" alt="Screenshot 2024-02-19 at 3 42 55 PM" src="https://github.com/pcottle/learnGitBranching/assets/1135007/14cbafcb-f06c-4417-962d-7b9344029ec4">

**Comment by AngeloThys** [comment]
I mistook figuring out the new branch's name as a bug rather than an intended feature, that's why I thought it might've been a bug and that rather any new branch name would/should be a valid solution.

Anyway, awesome of you to be so considerate in improving a non issue ❤️
