### ISSUE TITLE
show solution doesn't work with custom level

### ISSUE THREAD

**Issue by webformation** [pcottle/learnGitBranching#1134]
With a custom level used from gist, show solution doesn't work with an exception 

Uncaught Error: that level doesn't exist!
    isLevelSolved https://learngitbranching.js.org/build/bundle-84f1f278.js:203
    showSolution https://learngitbranching.js.org/build/bundle-84f1f278.js:203
    processLevelCommand https://learngitbranching.js.org/build/bundle-84f1f278.js:203
    trigger https://learngitbranching.js.org/build/bundle-84f1f278.js:203
    processCommand https://learngitbranching.js.org/build/bundle-84f1f278.js:203
    popAndProcess https://learngitbranching.js.org/build/bundle-84f1f278.js:203
    sipFromBuffer https://learngitbranching.js.org/build/bundle-84f1f278.js:203
    timeout https://learngitbranching.js.org/build/bundle-84f1f278.js:203

**Comment by webformation** [comment]
The gist of the documentation : https://learngitbranching.js.org/?gist_level_id=a84407351f9c9f0cb241 has the problem.

And any gist I try too

**Comment by pcottle** [comment]
Fixed!
