### ISSUE TITLE
Add deep links

### ISSUE THREAD

**Issue by dangbert** [pcottle/learnGitBranching#1137]
It would be nice to have deep links like https://learngitbranching.js.org/level2/part1

So I can directly link people to a particular thing they need to learn in git

(Note: I may be able to add this functionality myself if I have time)

**Comment by dan-cbm** [comment]
Interesting thanks! Still could be nice if the web app automatically updated the url as you traverse through the levels (or had a share button for the current page) but this workaround is handy
