### ISSUE TITLE
Incorrect implementation for git fetch/pull with colon ":" affecting remoteAdvance6

### ISSUE THREAD

**Issue by juanmv94** [pcottle/learnGitBranching#1138]
In _remoteAdvance6_ level we execute the command **git fetch origin foo~1:bar** to move remote _foo~_ into local _bar_ branch, but that's actually not allowed by Git, resulting in a **fatal: Invalid refspec 'foo~1:bar'** message.

When using colon ":", origins can be a remote branch name, or commit hash, no ~^ modifiers allowed. Also when using a remote branch as origin, example: **git fetch origin foo:bar** it will update _bar_ but also updates _o/foo_ not being reflected in the simulator.

These same issues affects **git pull** commands in the same way

**Comment by pcottle** [comment]
Good catch! Do you think just switching to commit hashes instead would solve the inconsistency but still provide a valuable lesson?

**Comment by juanmv94** [comment]
Definitely that could be a workaround until it’s fixed on the simulator, although I think the most common way of using the colon fetch is with a branch name origin (updating o/branch)

**Comment by pcottle** [comment]
Alright @juanmv94 just updated the level -- let me know what you think:
https://learngitbranching.js.org/?NODEMO&command=level%20remoteAdvanced6

**Comment by juanmv94** [comment]
**More issues discovered affecting fetch and pull commands:**
I'm making a pull request fixing all these issues including the previous ones

### _git fetch origin foo:bar_ (with HEAD on o/foo up to date, bar branch still doesn't exists) --> Already up to date!

**Examples:**

git clone
git fetch origin main:foo

### _git fetch origin foo:bar_ (with current HEAD not part of history of foo) --> Your origin branch is out of sync with the remote branch and fetch cannot be performed

**Examples:**

git checkout -b foo c0
git commit
git clone
git fetch origin main:bar

git clone
git fetch origin c0:foo
