### ISSUE TITLE
Ramping Up - Relative Ref 2 - caret issue

### ISSUE THREAD

**Issue by BigBoulard** [pcottle/learnGitBranching#1153]
When I type the caret on my macOs the character is a bit smaller than in the solution so the command is not understood by the program `git branch bugFixˆ`

![image](https://github.com/pcottle/learnGitBranching/assets/60930059/ae0a131f-359c-400a-9318-ce22c2e8aafc)

**Comment by pcottle** [comment]
Are you using a utf8 symbol and not something that's part of standard ascii?

**Comment by BigBoulard** [comment]
Good question, I'm just typing `option + i`

**Comment by pcottle** [comment]
Ah yeah that is the Modifier Letter Circumflex Accent[1], aka ˆ

Please use the standard ^ character (shift + 6 on american QWERTY keyboards) which is Circumflex Accent (https://www.compart.com/en/unicode/U+005E)


<br class="Apple-interchange-newline">Modifier Letter Circumflex Accent[[1]](https://www.compart.com/en/unicode/U+02C6#UNC_DB)"
