### ISSUE TITLE
rampup2 starts with * on main instead of bugFix, so we can only finish the game in 2 instead of the stated 1 needed steps

### ISSUE THREAD

**Issue by fadhleryani** [pcottle/learnGitBranching#1157]

**Comment by Theprathamshah** [comment]
Hey @fadhleryani , if you use` git checkout c3` command then it can be done in 1 step! but we are not using relative refs in this method!

**Comment by Theprathamshah** [comment]
Hey, @pcottle can you please assign this issue to me!!

**Comment by pcottle** [comment]
There you go! :)

**Comment by Theprathamshah** [comment]
Hey @pcottle, I noticed the issue was assigned to someone else, but no worries, I’ve made the necessary changes! Could you please review the code and approve the PR.Thank you!

**Comment by pcottle** [comment]
Merged #1164 and pushing the site now!
