### ISSUE TITLE
Can't type anything at Main Level, Level 1: Introduction to Git Commits

### ISSUE THREAD

**Issue by Boy-Kerikil** [pcottle/learnGitBranching#1167]
Hello, I cant type anything at Main Level, Level 1: Introduction to Git Commits, altough i can type again after change Remote level, but it's still a bug

**Comment by pcottle** [comment]
<img width="477" alt="Screenshot 2024-08-29 at 5 25 14 PM" src="https://github.com/user-attachments/assets/aad213f5-d835-494f-8a0e-8acdc1e9698d">
hrm i can input stuff...

**Comment by Boy-Kerikil** [comment]
![image](https://github.com/user-attachments/assets/d51d06d6-a913-443d-9b8e-85ee33bcdfd3)
ok now fixed

**Comment by 1ceshadow** [comment]
refresh and then it's ok
