### ISSUE TITLE
Language switcher fails on switching language back to English

### ISSUE THREAD

**Issue by AlexDanDuna** [pcottle/learnGitBranching#1171]
I accidentally swapped the language from English to Chinese, and then changed it back. However, the title in the top left of the page does not seem to have changed back to its English translation.

![image](https://github.com/user-attachments/assets/d0fab5d0-c7de-4df8-883a-6eb2e6ffb23c)

**Comment by pcottle** [comment]
Hrmm interesting! This indeed repros. I wonder what's going on...

**Comment by pcottle** [comment]
One line fix :)
