### ISSUE TITLE
newbie question: how to create permalink from current session ?

### ISSUE THREAD

**Issue by parmentelat** [pcottle/learnGitBranching#1174]
Hi
Complete newbie here, I have looked for a way to:
- start from the sandbox
- type a few commands
- then type a magic command like `permalink` or whatever in order to produce the corresponding permalink

I did find the recipe to do this myself but taking care of the html escaping and the copy/paste/splitting with ; is becoming tedious

otoh I may have missed it altogether if that exists already, does it ?

**Comment by pcottle** [comment]
Oh wow I totally forgot `share permalink` exists! Thanks for refreshing my memory
