### ISSUE TITLE
Next and previous buttons are not appearing

### ISSUE THREAD

**Issue by SleeplessInToronto** [pcottle/learnGitBranching#1176]
Next and previous buttons are not showing anymore when using: https://learngitbranching.js.org/

**Comment by pcottle** [comment]
oh I bet its due to the icon upgrade, justasecond!

**Comment by SleeplessInToronto** [comment]
hehe yeah I figured that was it. Thanks!!

**Comment by pcottle** [comment]
pushing the fix now :)

**Comment by pcottle** [comment]
A hard refresh (clear cache on the domain) fixes it!

**Comment by SleeplessInToronto** [comment]
Works like a charm now. Thanks so much. Best GIT tutorial ever! :)
