### ISSUE TITLE
Typo in pl translation

### ISSUE THREAD

**Issue by TomaszKupis** [pcottle/learnGitBranching#1181]
Simple change nia -> nie

https://github.com/pcottle/learnGitBranching/blob/194befc09123f356a7398a2d2b1523e941e842f9/src/levels/intro/rebasing.js#L1135

**Comment by pcottle** [comment]
Like so?
https://github.com/pcottle/learnGitBranching/pull/1182

**Comment by pcottle** [comment]
Gotta merge the PR first! It should auto-close based on my commit message
