### ISSUE TITLE
Suggestion: toggle button to show the log tree upside down

### ISSUE THREAD

**Issue by marrahi8** [pcottle/learnGitBranching#1188]
Some people (including me) are used to seeing the log tree in reverse mode, that is, first commits at the bottom and recent commits at the top. It would be nice to have a toggle or switch button that changes this visualization setup.

**Comment by pcottle** [comment]
Check out the command `flip`!
https://learngitbranching.js.org/?NODEMO&command=flip;gc;git%20checkout%20-b%20foo;gc;git%20checkout%20main;gc

![Screenshot 2024-10-23 at 7 58 59 AM](https://github.com/user-attachments/assets/26f3d5ff-6749-48a8-833c-eda9a92f4bad)
