### ISSUE TITLE
Support Alt + Backspace shortcut for deleting previous word

### ISSUE THREAD

**Issue by Ashark** [pcottle/learnGitBranching#1194]
To remove the previous word, in terminals (like Konsole), the default shortcut is  "Alt" + "Backspace".
While having "Ctrl" + "Backspace" is nicer in terms of "usual" applications, I currently very used to the default shortcut. Unfortunately, it does not work in game. Can you please add support for this?

P.S. Thanks for the very nice project!

**Comment by pcottle** [comment]
We dont even support ctrl + backspace for now, how about if we started there?

**Comment by Ashark** [comment]
Ctrl + Backspace works for me.

**Comment by pcottle** [comment]
Thanks @Ashark for the feedback, this was relatively easy but a HUGE increase in usability! love this change now :)

**Comment by pcottle** [comment]
I ended up going with both control+W and control+backspace :)

**Comment by Ashark** [comment]
Thanks!

**Comment by Ashark** [comment]
Hm, but Alt + Backspace is not working still.

Ctrl + W closes the current browser tab, so it probably makes no sense to use.
And Ctrl + Backspace is what already worked when I opened this issue.

**Comment by pcottle** [comment]
Oh I didn't code for alt and backspace. I can update it

**Comment by pcottle** [comment]
> Ctrl + W closes the current browser tab, so it probably makes no sense to use.

I'm on mac so thats command+W for me, hence I didnt catch this. sorry!

> And Ctrl + Backspace is what already worked when I opened this issue.

I think this is built in by default for certain input fields, I never did anything to program it specifically....

**Comment by Ashark** [comment]
It works, thanks!
