### ISSUE TITLE
Confusing description for "pick" / "omit" buttons for interactive rebase

### ISSUE THREAD

**Issue by Ashark** [pcottle/learnGitBranching#1197]
Currently, the description for the interactive rebase lesson is the following:

![current description for pick omit](https://github.com/user-attachments/assets/3b643377-4072-4958-939a-25139781086b)

And the actual interface is the following:

![actual interface](https://github.com/user-attachments/assets/05811853-edbc-4ff0-bee9-d687709bbb20)

As for me, this part is kind of confusing:

> When the dialog opens, each commit is set to be included by the `pick`  button next to it being active. To drop a commit, toggle off its `pick` button.

Because  it mixes the "inclusion" and "active" state of a button "pick" (which is dimmed).

How about something like this:

> In the opened dialog, you can decide to include or drop each individual commit by toggling "pick"/"omit" button next to it. 

This way this will not confuse that dimmed commit's "pick" button is active. It _is_ active, but dimmed.

Note that I am not a native speaker however.

**Comment by pcottle** [comment]
You're definitely right, its confusing for most people :) I've gotten feedback on this before

What if we did something like:

```
= C2 (Click to Drop/Omit)
= C3 (Click to Include/Pick)
= C4 (Click to Drop/Omit)
```

?

**Comment by pcottle** [comment]
![Screenshot 2024-11-11 at 5 38 39 PM](https://github.com/user-attachments/assets/8d3860bb-cb8b-4aa8-ad84-44d34eef9e9c)

**Comment by pcottle** [comment]
![Screenshot 2024-11-11 at 5 43 04 PM](https://github.com/user-attachments/assets/47adfe75-b6af-403c-b6ff-6af745415d7a)

**Comment by Ashark** [comment]
Thanks!
