### ISSUE TITLE
Remote level 8: Locked Main. The solution is not correct.

### ISSUE THREAD

**Issue by nisemenov** [pcottle/learnGitBranching#1202]
Hi, everyone!

I've just noticed the first step of **your right solution** is not correct.

**Start position**:
![image](https://github.com/user-attachments/assets/00a4c646-d7a2-4b42-8c4c-e711194f73be)

**Your first step**:
`git reset --hard o/main`

**From git docs**:
> git reset --hard [\<commit>]
> Resets the index and working tree. Any changes to tracked files in the working tree since <commit> are discarded. Any untracked files or directories in the way of writing any tracked files are simply deleted.

So `git reset --hard` cleans working tree at all.
We can use `git reset --soft` for saving our changes and execute `git commit` command. But it is two steps :)

<details>

<summary>One of possible solution for save 3 step only</summary>

```bash
git branch -f main HEAD^
git checkout -b feature C2
git push
```

</details>

**Comment by pcottle** [comment]
Yep its just a habit that I use `git reset --hard` when doing movements in the tree like that. Theres no working tree or staged changes in learn git branching so it doesn't really matter between `--hard` and `--soft`. I even explain this:

![Screenshot 2024-11-15 at 8 08 21 AM](https://github.com/user-attachments/assets/04385314-8b53-4bff-ae30-fdb9e1745329)

**Comment by pcottle** [comment]
But your feedback is valid that the solution command could be better :) I'm going to update to this so:

- we encourage folks to set the main back to the origin's state of main (more declarative than C1 or HEAD^)
- we specifically push our feature to the origin, not just everything:

![Screenshot 2024-11-15 at 8 12 51 AM](https://github.com/user-attachments/assets/d910a275-ed07-4ab7-9ac6-8a53e5473156)
