### ISSUE TITLE
Make this project more easy to translate

### ISSUE THREAD

**Issue by luzfcb** [pcottle/learnGitBranching#161]
Thanks for this project. I'm interested in translating it to pt_BR. I have little knowledge of Javascript. I'm a Django (python language) developer. In Django have a simple way of internationalizing applications. ( https://docs.djangoproject.com/en/1.6/topics/i18n/translation/ )

When I want to support the translation of certain text, instead of using a normal string, use a function call to "gettext" passing as parameter the string to be translated. (the example of the link above is using an alias for unicode gettext, in other words _ (" string ")   )

After this step, execute a command for Django to generate the translation files ( .po files) and send to transifex.com translation platform, which is free for opensource projects.
The Transifex platform is very easy to manage translations and groups of translators.

Is it possible to add support for something like this project?
It would be interesting at least list somewhere, the files containing the strings for translation to facilitate the addition of new translations.

What is your opinion about it?

http://stackoverflow.com/questions/8121575/po-files-and-gettext-vs-json-and-custom-i18n-library

@pcottle @aschrab @sid0 @remore @donkirkby

**Comment by pcottle** [comment]
(closing out old issues, would still like to do this. I feel bad for the current translation process)
