### ISSUE TITLE
"git rebase" doesn't work but "git rebase -i" does

### ISSUE THREAD

**Issue by brianmay** [pcottle/learnGitBranching#179]
Hello,

Was playing around with creating a lesson to illustrate a common git issue.

See: https://gist.github.com/brianmay/a84407351f9c9f0cb241

However, I noticed that "git rebase origin/master" doesn't resolve the issue. It doesn't do anything in fact. However "git rebase -i origin/master", followed by no interactive changes, does.

Unless I am mistaken, I believe that both operations are suppose to do the same thing.

Thanks

**Comment by pcottle** [comment]
(closing out old issues)
