### ISSUE TITLE
Extra tree displayed when loading custom levels by URL

### ISSUE THREAD

**Issue by Ajedi32** [pcottle/learnGitBranching#188]
When visiting the [example page](http://pcottle.github.io/learnGitBranching/?gist_level_id=a84407351f9c9f0cb241) linked in the README demonstrating loading levels from gists, I noticed something odd:

![Three trees](https://cloud.githubusercontent.com/assets/1876931/3456951/e0f941ae-01f3-11e4-84d3-ee67e1daa391.png)

There's an extra tree in the middle. No idea why.

I'm running Chrome 35.0.1916.153 on Ubuntu 12.04 LTS.

I also noticed the following error in the LearnGitBranching console (but not the browser console):

![Something went wrong TypeError: Cannot read property 'canvas' of undefined](https://cloud.githubusercontent.com/assets/1876931/3456994/697182d0-01f4-11e4-9b85-5cabac28922e.png)

**Comment by pcottle** [comment]
(I think this was fixed)
