### ISSUE TITLE
grunt build failing

### ISSUE THREAD

**Issue by lkysow** [pcottle/learnGitBranching#20]
Hi, awesome project! I'd like to add some more shortcuts but I can't seem to build the project. I ran npm install and then npm install grunt -g but I'm getting this error when trying to build:

```
[lkysow@Lukes-Macbook learnGitBranching (master)]$ grunt build
Loading "shell.js" tasks and helpers...ERROR
>> TypeError: Cannot read property '_' of undefined
<WARN> Task "shell" not found. Use --force to continue. </WARN>

Aborted due to warnings.
```

And when run with --force:

```
lkysow@Lukes-Macbook learnGitBranching (master)]$ grunt  build --force
Loading "shell.js" tasks and helpers...ERROR
>> TypeError: Cannot read property '_' of undefined
<WARN> Task "shell" not found. Used --force, continuing. </WARN>

Done, but with warnings.
```

If you think the issue I'm seeing is something peculiar to my environment then no worries, I'll continue trying to debug it myself.

**Comment by webeng** [comment]
Installing v1.3.1 worked for me. I think the newest version is using ES6?
