### ISSUE TITLE
Remember the goal window position when advancing levels

### ISSUE THREAD

**Issue by ADTC** [pcottle/learnGitBranching#210]
As pull request #166 already supports dragging the goal window, I think it will be better if the goal window can remember where it was dragged to as I move from level to level, and always appear there.

The goal window appears by default on the left side, covering up the command history window. As I have a large screen, I drag the window to the right side and I find that the commit tree moves to the left to give the goal window more room, which is nice.

But I find myself having to drag the goal window to the right on every new level, because it _always_ appears on the left side when it opens. It will be great if the window can remember its position, and also the commit tree can get pushed to the left when the goal window re-appears on the right.

**Comment by pcottle** [comment]
(closing out old issues... also vaguely remember this being hard)
