### ISSUE TITLE
command-line pointer is not walking on the edge of the text

### ISSUE THREAD

**Issue by bebehei** [pcottle/learnGitBranching#243]
![j](https://cloud.githubusercontent.com/assets/2073458/6111213/76a048e6-b087-11e4-9db1-7b2802a5e16d.png)
![m](https://cloud.githubusercontent.com/assets/2073458/6111212/769af04e-b087-11e4-9f25-e4197aa1a967.png)

One main reason is, that the text does not use a mono-spaced font. Another one is that in `/src/js/views/commandView.js` is a fixed width of 10 px hardcoded, which is not valid if there is no mono-spaced font used.

**Comment by bebehei** [comment]
The JS Code-Block, which is responsible for it: https://github.com/pcottle/learnGitBranching/blob/master/src/js/views/commandViews.js#L133-L160

**Comment by bebehei** [comment]
Ok, I installed now the monaco-font. "It works." But why does the fallback not work? Coul it be, that in the CSS the following line has to get changed?

    font-family: Monaco, Courier, font-monospace;

to

    font-family: Monaco, Courier, monospace;


Look at: http://www.w3schools.com/cssref/css_websafe_fonts.asp

**Comment by pcottle** [comment]
Yeah the cursor positioning is a source of pain. unfortunately you can't use a "real" text field so you end up having to implement hacks.

but yeah `font-monospace` isnt even a real font, let me change that. not sure how that typo slipped in

**Comment by pcottle** [comment]
Resolved in 4030f8f! thanks again

**Comment by bebehei** [comment]
A dynamic hack would be, if you spawn a similar field, which is not visible and has got the same CSS-settings than the actual command-line. Fill in this field some chars  and measure the size of the full invisible field. The actual size of it divided by the amount of chars will give you the width of a single char. So you don't have to hardcode[0] the width of a char and can use any monospace-font.

This is just an idea, I'm pretty sure this will work, but I won't implement it. My JS-Skills are obsolete.

[0] https://github.com/pcottle/learnGitBranching/blob/master/src/js/views/commandViews.js#L141
