### ISSUE TITLE
Slide-In animation changes git-graph position in dialog

### ISSUE THREAD

**Issue by MaPePeR** [pcottle/learnGitBranching#244]
![image](https://cloud.githubusercontent.com/assets/527679/6145076/49e38d1a-b1de-11e4-9b02-dd0d2842cd89.png)

For some levels i could not see the example git graphs at all.

I think the slide in animation from the top should be removed anyway - especially if one only switches to the next page of a dialog window.

Another solution would be to only start rendering the git-graph when the dialog window has slided in completely.

(Using Chrome on Linux)

**Comment by pcottle** [comment]
Yeah this is a recurring issue on Linux :-/ deals with some chrome-specific bug with how they measure the position of elements (it should be updated by the time its called).

The good news is that im rebuilding this dialogs in React! So no more animations and this bug should go away :+1:

**Comment by Hongarc** [comment]
I don't use Linux and this issue is very old so I don't know this issue is exits or not.
If you fix it, please close this issue.

**Comment by pcottle** [comment]
(closing out old issues)
