### ISSUE TITLE
404 on main.56afcf29.css 

### ISSUE THREAD

**Issue by Insti** [pcottle/learnGitBranching#249]
When trying to access: http://pcottle.github.io/learnGitBranching/

The main stylesheet seems to not be found, causing the whole page to fail to render correctly.

http://pcottle.github.io/learnGitBranching/build/main.56afcf29.css

**Comment by christothes** [comment]
I hit this today also

**Comment by pcottle** [comment]
Ah my bad! I'm in manila right now for work and have really bad internet -- for PR #247 yesterday I had to push to prod and something probably got messed up along the way.

i just pushed again and it seems to be working -- sorry for the interruption :scream:
