### ISSUE TITLE
Sanity-check new build after pushing to prod

### ISSUE THREAD

**Issue by pcottle** [pcottle/learnGitBranching#252]
@mgarciaisaia had a good point over in Issue #250  -- we can poll the pages API:
https://developer.github.com/v3/repos/pages/

and wait for the new build to get picked up. afterwards we can do a recursive wget to make sure no 404s get registered!

**Comment by mgarciaisaia** [comment]
As I've said in #250, there's a [`page_build` event](https://developer.github.com/webhooks/#events) that may be exactly what we needed here.

It would be great to test it a little bit, if it _really_ gets triggered after the site is updated, and then it's just a matter of using any existing tool to check for 404's and other errors.

**Comment by pcottle** [comment]
(closing out old issues)

Also it's hard to do this without some kind of headless browser, unless 404s are the only thing you're testing for
