### ISSUE TITLE
Locale choice by URL parameter

### ISSUE THREAD

**Issue by coyl** [pcottle/learnGitBranching#268]
It would be great to have a parameter in URL to define locale. 
Something like http://pcottle.github.io/learnGitBranching/?locale=ru_RU
So I'll be able to give a direct link to Russian version without annotation like "close welcome screen, then click on the 'earth' icon on the bottom right panel, then click 'Русский'".
Unfortunately, I'm not very good in JS, so I can't do it myself and be sure that I didn't broke something else =)

**Comment by pcottle** [comment]
We do have exactly this!

![screen shot 2015-05-08 at 12 58 49 pm](https://cloud.githubusercontent.com/assets/1135007/7544449/012bdefa-f582-11e4-8d12-ce913a65ef50.png)
![screen shot 2015-05-08 at 12 58 45 pm](https://cloud.githubusercontent.com/assets/1135007/7544448/012a4d9c-f582-11e4-85e6-a97d2737595b.png)

Did you try it? is it not working for you?

**Comment by coyl** [comment]
Oh, silly me =) I did not tried it =)
