### ISSUE TITLE
"build level" does not work

### ISSUE THREAD

**Issue by Lia-C** [pcottle/learnGitBranching#273]
![screenshot from 2015-05-19 22 57 01](https://cloud.githubusercontent.com/assets/6060817/7737258/943db454-fefe-11e4-9478-45389ffdc58f.png)
![screenshot from 2015-05-19 22 57 01](https://cloud.githubusercontent.com/assets/6060817/7738300/b807ca06-ff07-11e4-89c6-ac57f0e882e8.png)

When you type in <code>build level</code>, you are supposed to get a dialog box: "The dialog will walk you through the process, and at the end you can export level to get a JSON blob."
However, nothing happens-- the command just perpetually loads, and there is no dialog pop-up. See the above screenshot-- the little loading icon just runs forever.

If I do debug.copyTree(), I get:
<code>{"branches":{"master":{"target":"C1","id":"master","remoteTrackingBranchID":null}},"commits":{"C0":{"parents":[],"id":"C0","rootCommit":true},"C1":{"parents":["C0"],"id":"C1"}},"tags":{},"HEAD":{"target":"master","id":"HEAD"}}</code>
and the message:
<code>NO INTL support for key Copy the tree string below. this is probably a dev error</code>

**Comment by Lia-C** [comment]
I also tried cloning the repo, and following your workflow:
===========================================
git clone <your fork of the repo>
cd learnGitBranching
npm install # to install all the node modules I depend on

git checkout -b newAwesomeFeature
vim ./src/js/git/index.js # some changes
grunt fastBuild # skips tests and linting, faster build
===========================================


---but upon doing "grunt fastBuild", I get this error:
===========================================
Running "clean:0" (clean) task

Running "browserify:dist" (browserify) task
Warning: bundle() no longer accepts option arguments.
Move all option arguments to the browserify() constructor. Use --force to continue.

Aborted due to warnings.
===========================================

My browserify version is 4.0.0. I've also tried using browserify version 10.2.1 but receive the same error message.

**Comment by Lia-C** [comment]
I am not sure if this is related, but when I run <code>sudo npm install</code> to install all the node modules you depend on, I get:

    npm WARN package.json LearnGitBranching@0.8.0 No description
    npm WARN package.json node@0.0.0 No repository field.

**Comment by pcottle** [comment]
Hey Lia I'll check this out later today hopefully. This feature is pretty untested so I would be surprised if it broke

Also those errors are unrelated don't worry :P just some silly log spew from the new package.json format

**Comment by Lia-C** [comment]
Thanks for investigating! Did you find anything?

**Comment by pcottle** [comment]
Hey @Lia-C sorry again for the delay, but I fixed this all up! there were some minor breakages from a few codemods and view rewrites but now it should all work -- let me know if you have any other issues.

All the interns are starting at Facebook nowadays so work has been a bit crazier than normal, but at least this should be healthy now

![screen shot 2015-05-27 at 9 30 01 pm](https://cloud.githubusercontent.com/assets/1135007/7852760/b7f4a7f4-04b7-11e5-968d-af9d06ad064f.png)
![screen shot 2015-05-27 at 9 30 04 pm](https://cloud.githubusercontent.com/assets/1135007/7852762/b7f74d60-04b7-11e5-88ac-308e73328b81.png)
![screen shot 2015-05-27 at 9 30 28 pm](https://cloud.githubusercontent.com/assets/1135007/7852761/b7f71e9e-04b7-11e5-8ef1-ee0c19b1eeaf.png)
