### ISSUE TITLE
When using the git reset command with the --hard argument I am told to omit it because this is the default behaviour - this is wrong

### ISSUE THREAD

**Issue by OffbeatDrizzle** [pcottle/learnGitBranching#277]
See http://git-scm.com/docs/git-reset

The default mode is actually --mixed, which does NOT overwrite the files in your working folder.

git reset [<mode>] [<commit>]
This form resets the current branch head to <commit> and possibly updates the index (resetting it to the tree of <commit>) and the working tree depending on <mode>. If <mode> is omitted, defaults to "--mixed"

**Comment by pcottle** [comment]
> When using the git reset command with the --hard argument I am told to omit it because this is the default behaviour

Oooh yeah I see what you mean -- I didn't mean its the default behavior *in normal git* but the default behavior *in Learn Git Branching*.  I felt bad for people having to type out `--hard` all the time when that was the only mode that works.

let me update this

**Comment by pcottle** [comment]
![screen shot 2015-05-27 at 9 37 57 pm](https://cloud.githubusercontent.com/assets/1135007/7852800/b18629be-04b8-11e5-945b-a7e390d3fdcd.png)

there we go, hope that clarifies everything! thanks for the report, this was ambiguous before

**Comment by OffbeatDrizzle** [comment]
No worries - it's just that I am learning git as well and I feel that if people are told it's the default behaviour they might assume it's the same in git too, which might cause some issues :)

**Comment by pcottle** [comment]
No worries! It was great feedback :)

On Thu, May 28, 2015 at 1:18 PM, OffbeatDrizzle <notifications@github.com>
wrote:

> No worries - it's just that I am learning git as well and I feel that if
> people are told it's the default behaviour they might assume it's the same
> in git too, which might cause some issues :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcottle/learnGitBranching/issues/277#issuecomment-106584557>
> .
>



-- 
Peter M Cottle
UC Berkeley Class of 2012
Master's of Science, Mechanical Engineering
UC San Diego Class of 2011
Bachelor's of Science, Mechanical Engineering
(408) 455 9405

"Equipped with his five senses, man explores the universe around him and
calls the adventure Science." - Edwin Hubble
