### ISSUE TITLE
Simpler solution to Juggling Commits 2 not recognized

### ISSUE THREAD

**Issue by jedbrown** [pcottle/learnGitBranching#28]
This 3-command sequence achieves the desired outcome

```
git rebase newImage master # checkout and fast-forward master
git commit --amend
git cherry-pick caption
```

This 4-command sequence also achieves the same thing

```
git checkout master
git reset --hard newImage
git commit --amend
git cherry-pick caption
```

Neither of the above are recognized. The expected solution seems to be

```
git checkout master
git cherry-pick newImage # identical except for the date
git commit --amend
git cherry-pick caption
```

although this also works

```
git rebase newImage master
git commit --amend
git commit --amend  # yes, twice
git cherry-pick caption
```

**Comment by mangobrain** [comment]
Juggling commits #2 is still broken IMHO. The original complaint that the following simple solution is not recognised is still valid:

```
git rebase newImage master # checkout and fast-forward master
git commit --amend
git cherry-pick caption
```

The objective text says C2 only needs to be amended once, which is exactly what has happened. However, in the resulting graph, master will contain C2' and C3' (NOT C2'' and C3'). This level rewards you for cheating (amending C2 twice) or figuring out the exact expected command sequence, not for solving the stated problem!

**Comment by pcottle** [comment]
Yeah @mangobrain, again I wish I had a way to mark which commits were amended and then use that in the final level comparison. There are obvious shortcomings to the comparison modes we have, but I think this is the most general comparison mode we can use for now (and better than the pre-issue state).

The reason why I never built this up is that it requires piping a new boolean value (`isAmended`) through every state transition (cherry-picking, rebasing, git push/pull, etc) and tree serialization / deserialization, etc etc. I'd happily accept a PR that whips this all up, but don't think its worth the effort at the moment right now.

Besides, the overall goal of LGB is to help newbies learn -- usually the people that figure out the alternate solutions are smart enough to see where my comparison methods fall short (like yourself) :P

**Comment by skogshjort** [comment]
Hi!

I'm new to git, and did jump ahead a bit so my understanding of interactive rebase is not so good. So my instinct to solve Juggling Commits was the following

```bash
git checkout newImage                    # switch to the earlier commit
git commit --amend                       # make changes
git rebase --onto HEAD caption~ caption  # is this where others are cherry picking?
```

or 

```bash
git checkout newImage                    # switch to the earlier commit
git commit --amend                       # make changes
git checkout caption                     # switch to the later commit
git rebase newImage                      # a bit easier to type
```

which to me is more intuitive way of swapping (although I am a complete beginner, so I might think about this the wrong way)

Did I think of a more intuitive way to solve this or did I misunderstand the assignment? 

<i>Hugs, and thank you so much for this project! I don't expect any answer to this but would be flattered to get one!</i>
