### ISSUE TITLE
Build fails with "Unexpected token" parsing error

### ISSUE THREAD

**Issue by marko-asplund** [pcottle/learnGitBranching#280]
The following build error occurs at commit 6c3a7ad327b8b7233acb04950c4f9738a6200f31:

```
~/projects/learnGitBranching (master ✔) ᐅ ./node_modules/grunt-cli/bin/grunt build
Running "clean:0" (clean) task

Running "browserify:dist" (browserify) task
>> Error: Parsing file /Users/marko/projects/learnGitBranching/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/html.js: Line 446: Unexpected token )
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

**Comment by pcottle** [comment]
Hrm this looks like an error from deep inside some jquery dependency. Are
you on a fresh checkout? What version of node are you running?

On Wednesday, May 27, 2015, marko asplund <notifications@github.com> wrote:

> The following build error occurs at commit 6c3a7ad
> <https://github.com/pcottle/learnGitBranching/commit/6c3a7ad327b8b7233acb04950c4f9738a6200f31>
> :
>
> ~/projects/learnGitBranching (master ✔) ᐅ ./node_modules/grunt-cli/bin/grunt build
> Running "clean:0" (clean) task
>
> Running "browserify:dist" (browserify) task
> >> Error: Parsing file /Users/marko/projects/learnGitBranching/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/html.js: Line 446: Unexpected token )
> Warning: Error running grunt-browserify. Use --force to continue.
>
> Aborted due to warnings.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcottle/learnGitBranching/issues/280>.
>


-- 
-Sent from Gmail Mobile

**Comment by marko-asplund** [comment]
the last commit in my repository clone is 6c3a7ad327b8b7233acb04950c4f9738a6200f31.
I'm using nodejs v0.12.4 via nvm.

**Comment by mizunashi-mana** [comment]
I had a same accident.  The reason may be that `jquery@1.7.3` has older `jsdom` reference and browserify was updated.

I tried to update jquery to 2.1 without thinking deeply.  Then, I got a answer :P
[See also](https://github.com/UncoolAJ86/node-jquery)

**Comment by pcottle** [comment]
Ah yeah, I'm on 

```
[pcottle:~/Dropbox/wip/learnGitBranching:master]$ node --version
v0.10.35
```

@mizunashi-mana  you seem to have figured this out -- should we add a stricter dependency in our `package.json`? wondering if we could just stick to browserify 3.14

what versions of browserify do you guys have installed?

**Comment by mizunashi-mana** [comment]
My browserify for learnGitBranching is 3.14.1.

Oh, I'm sorry for my mistake.  So, there may be another reason.  I'm using 
```
$ node --version
v0.12.2
```
Is it the reason?  But, I could build a few days ago using v0.12.2.

**Comment by mizunashi-mana** [comment]
I try to fix this issue.  I experimented on a older repo being able to make:
```
$ npm update
backbone@1.2.0 node_modules/backbone
└── underscore@1.8.3
react@0.13.3 node_modules/react
└── envify@3.4.0 (through@2.3.7, jstransform@10.1.0)
react-tools@0.13.3 node_modules/react-tools
├── jstransform@10.1.0 (base62@0.1.1, esprima-fb@13001.1001.0-dev-harmony-fb, source-map@0.1.31)
└── commoner@0.10.1 (commander@2.5.1, private@0.1.6, graceful-fs@3.0.7, install@0.1.8, q@1.1.2, mkdirp@0.5.1, iconv-lite@0.4.10, glob@4.2.2, recast@0.9.18)
$ grunt fastBuild
...
Aborted due to warnings.
```
And:
```
$ npm install backbone@1.1.2 # the version using pre repo
$ grunt fastBuild
...
Done, without errors.
```

I think backbone's major update is the cause.
So, we should add a stricter jquery version or modify using backbone version.

Usually, "backbone": "^1.1.2" will may be changed to "backbone": "~1.1.2".

**Comment by pcottle** [comment]
Thanks a ton @mizunashi-mana !! Yeah ill change the version over, must have been the latest upgrade. thanks a ton for the debug, I knew it was one of these pesky >= dependencies. Since it was an error with jquery though I only looked at that dependency though

let me update this real quick
