### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by Lia-C** [pcottle/learnGitBranching#282]
When I try to run `npm install` after cloning, I get `npm ERR! not ok code 0` at the end.

What can I do to make `npm install` work successfully? I tried using the package.json that was recommended in this [closed issue](https://github.com/pcottle/learnGitBranching/issues/89), but still run into errors.

Here is the output of `npm install` with the original package.json that is provided in the repo.
```
licoleman@licoleman-VirtualBox:~/tesla/gitgame/learnGitBranching$ npm install
npm WARN package.json LearnGitBranching@0.8.0 No description
npm http GET https://registry.npmjs.org/grunt
npm http 200 https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
npm http 200 https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
npm ERR! error rolling back Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake'
npm ERR! error rolling back  grunt@0.4.5 { [Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake' }
npm ERR! Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee'
npm ERR!  { [Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/licoleman/tesla/gitgame/learnGitBranching
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/licoleman/tesla/gitgame/learnGitBranching/npm-debug.log
npm ERR! not ok code 0
licoleman@licoleman-VirtualBox:~/tesla/gitgame/learnGitBranching$ npm cache clean
licoleman@licoleman-VirtualBox:~/tesla/gitgame/learnGitBranching$ npm install
npm WARN package.json LearnGitBranching@0.8.0 No description
npm http GET https://registry.npmjs.org/grunt
npm http 200 https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
npm http 200 https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
npm ERR! error rolling back Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake'
npm ERR! error rolling back  grunt@0.4.5 { [Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake' }
npm ERR! Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake'
npm ERR!  { [Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/licoleman/tesla/gitgame/learnGitBranching
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/licoleman/tesla/gitgame/learnGitBranching/npm-debug.log
npm ERR! not ok code 0
```

**Comment by pcottle** [comment]
Can you attach node --version output? and also run as sudo. Lastly this
might be related:


https://github.com/pcottle/learnGitBranching/issues/280

On Fri, May 29, 2015 at 2:24 PM, Lia Coleman <notifications@github.com>
wrote:

> When I try to run npm install after cloning, I get npm ERR! not ok code 0
> at the end. What can I do to make npm install work successfully? I tried
> using the package.json that was recommended in this closed issue
> <https://github.com/pcottle/learnGitBranching/issues/89>, but still run
> into errors.
>
> Here is the output of npm install with the original package.json that is
> provided in the repo.
>
> licoleman@licoleman-VirtualBox:~/tesla/gitgame/learnGitBranching$ npm install
> npm WARN package.json LearnGitBranching@0.8.0 No description
> npm http GET https://registry.npmjs.org/grunt
> npm http 200 https://registry.npmjs.org/grunt
> npm http GET https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
> npm http 200 https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
> npm ERR! error rolling back Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake'
> npm ERR! error rolling back  grunt@0.4.5 { [Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake']
> npm ERR! error rolling back   errno: 3,
> npm ERR! error rolling back   code: 'EACCES',
> npm ERR! error rolling back   path: '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake' }
> npm ERR! Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee'
> npm ERR!  { [Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee']
> npm ERR!   errno: 3,
> npm ERR!   code: 'EACCES',
> npm ERR!   path: '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
>
> npm ERR! System Linux 3.16.0-30-generic
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! cwd /home/licoleman/tesla/gitgame/learnGitBranching
> npm ERR! node -v v0.10.25
> npm ERR! npm -v 1.3.10
> npm ERR! path /home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee
> npm ERR! code EACCES
> npm ERR! errno 3
> npm ERR! stack Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/coffee'
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/licoleman/tesla/gitgame/learnGitBranching/npm-debug.log
> npm ERR! not ok code 0
> licoleman@licoleman-VirtualBox:~/tesla/gitgame/learnGitBranching$ npm cache clean
> licoleman@licoleman-VirtualBox:~/tesla/gitgame/learnGitBranching$ npm install
> npm WARN package.json LearnGitBranching@0.8.0 No description
> npm http GET https://registry.npmjs.org/grunt
> npm http 200 https://registry.npmjs.org/grunt
> npm http GET https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
> npm http 200 https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
> npm ERR! error rolling back Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake'
> npm ERR! error rolling back  grunt@0.4.5 { [Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake']
> npm ERR! error rolling back   errno: 3,
> npm ERR! error rolling back   code: 'EACCES',
> npm ERR! error rolling back   path: '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake' }
> npm ERR! Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake'
> npm ERR!  { [Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake']
> npm ERR!   errno: 3,
> npm ERR!   code: 'EACCES',
> npm ERR!   path: '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
>
> npm ERR! System Linux 3.16.0-30-generic
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! cwd /home/licoleman/tesla/gitgame/learnGitBranching
> npm ERR! node -v v0.10.25
> npm ERR! npm -v 1.3.10
> npm ERR! path /home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake
> npm ERR! code EACCES
> npm ERR! errno 3
> npm ERR! stack Error: EACCES, unlink '/home/licoleman/tesla/gitgame/learnGitBranching/node_modules/grunt/node_modules/.bin/cake'
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /home/licoleman/tesla/gitgame/learnGitBranching/npm-debug.log
> npm ERR! not ok code 0
>
> gyp ERR! stack at ChildProcess.onCpExit
> (/usr/share/node-gyp/lib/configure.js:431:16)
> gyp ERR! stack at ChildProcess.EventEmitter.emit (events.js:98:17)
> gyp ERR! stack at Process.ChildProcess._handle.onexit
> (child_process.js:797:12)
> gyp ERR! System Linux 3.16.0-30-generic
> gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
> gyp ERR! cwd
> /home/licoleman/tesla/gitgame/learnGitBranching/node_modules/jquery/node_modules/jsdom/node_modules/contextify
> gyp ERR! node -v v0.10.25
> gyp ERR! node-gyp -v v0.10.10
> gyp ERR! not ok
> npm WARN This failure might be due to the use of legacy binary "node"
> npm WARN For further explanations, please read
> /usr/share/doc/nodejs/README.Debian
>
> npm WARN optional dep failed, continuing contextify@0.1.14
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcottle/learnGitBranching/issues/282>.
>



-- 
Peter M Cottle
UC Berkeley Class of 2012
Master's of Science, Mechanical Engineering
UC San Diego Class of 2011
Bachelor's of Science, Mechanical Engineering
(408) 455 9405

"Equipped with his five senses, man explores the universe around him and
calls the adventure Science." - Edwin Hubble

**Comment by Lia-C** [comment]
The node version is 0.10.38. 

However, I think I may have gotten past that error. Now I am trying to execute `grunt fastBuild`. Upon doing `grunt fastBuild`, I get this error:

```
licoleman@licoleman-VirtualBox:~/gitgame/learnGitBranching$ grunt fastBuild
Running "clean:0" (clean) task

Running "browserify:dist" (browserify) task
Error: Parsing file /home/licoleman/gitgame/learnGitBranching/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/html.js: Line 446: Unexpected token )
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
```

There is nothing extraordinary about line 446 in html.js: `set head() { /* noop */ },`.
If I comment out line 446 and then try `grunt fastBuild` again, then I receive a very similar error:

```
licoleman@licoleman-VirtualBox:~/gitgame/learnGitBranching$ grunt fastBuild
Running "clean:0" (clean) task

Running "browserify:dist" (browserify) task
Error: Parsing file /home/licoleman/gitgame/learnGitBranching/node_modules/jquery/node_modules/jsdom/lib/jsdom/level1/core.js: Line 418: Unexpected token )
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
[2]+  Done                    geany /home/licoleman/gitgame/learnGitBranching/node_modules/jquery/node_modules/jsdom/lib/jsdom/level2/html.js
```

I keep getting these grunt-browserify parsing file errors. Any idea how to fix it?

Now, it is a problem with line 418 in level1's core.js: `set nodeName() { throw new core.DOMException();},`. Again, nothing extraordinary.

**Comment by Lia-C** [comment]
I tried the suggestion of doing `grunt fastBuild --force` from the console output `Warning: Error running grunt-browserify. Use --force to continue.`-- but that doesn't work either. It produces an index.html where there is no text cursor and you cannot type anything in.

**Comment by mizunashi-mana** [comment]
Please, Try:
```
learnGitBranching $ npm install backbone@1.1.2
```

It may fix this problem.

See also #280.  I think it's same issue and provides more information.

**Comment by Lia-C** [comment]
Ah, yes. That did it! It builds successfully now. Thanks so much.
