### ISSUE TITLE
How can I specify the best number of commands for a level I built?

### ISSUE THREAD

**Issue by Lia-C** [pcottle/learnGitBranching#284]
I created a new level with the level builder, took the JSON, stored it in a `mylevel.js` file in `src/levels/mylevels`. I also added this `mylevel.js` to `src/levels/index.js`, so now `mylevel` appears in the modal when you type `levels`.
However, when I test my level, after I complete it, I get the the modal that says 

    You solved the level in 2 command(s); our solution uses 1.
    See if you can whittle it down to 1 :D

Mylevel actually takes 2 commands, but where do I specify this? 
I know that in `src/js/dialogs/nextLevel.js` there is the line  'our solution uses {best}"-- but where do I specify `{best}` for mylevel?

**Comment by Lia-C** [comment]
Also is there a way to make a new tab in `levels`, so that we have three tabs: Main, Remote, and MyLevels?

**Comment by Lia-C** [comment]
I figured out my first question: you can specify the number of commands right in the level's json: `"solutionCommand": "git rebase dev; git commit"`. The number of commands you put here is what is used as the "best" number of commands.

Still trying to figure out how to create a new tab, though...

I also want to try to add to the `rebase -i` functionality to add a `squash` option, instead of just `pick`. Do you have any advice as to which files/areas I would need to edit?

**Comment by Lia-C** [comment]
Figured out how to create a new tab! You add a new tab in `src/js/views/levelDropdownView.js`. AFter making a level, you can add your level to your tab in `src/levels/index.js` by putting `tab: 'yourtabname'` in your level's part of the JSON.

**Comment by pcottle** [comment]
Yep @Lia-C ! The tabs part is fairly mainly since we only have two tabs

For the solutionCommand stuff, we automatically record the commands you used to solve the level -- but if you have a more efficient solution, youll need to re-record the level or just edit the json manually

also notice that `grunt test` should test the new level automatically!
