### ISSUE TITLE
How can I manually change language?

### ISSUE THREAD

**Issue by TheStigger** [pcottle/learnGitBranching#286]
I can't find any link which will change language.

**Comment by pcottle** [comment]
A few ways:

Click the helper bar globe icon:
![screen shot 2015-06-03 at 12 08 29 pm](https://cloud.githubusercontent.com/assets/1135007/7969054/45e2b4c6-09e9-11e5-97d8-424b23ae8166.png)

which then pops all the languages we have:
![screen shot 2015-06-03 at 12 08 32 pm](https://cloud.githubusercontent.com/assets/1135007/7969058/4bb82980-09e9-11e5-8682-b4a2520bb992.png)

or use the locale command:

![screen shot 2015-06-03 at 12 09 18 pm](https://cloud.githubusercontent.com/assets/1135007/7969074/5ec63526-09e9-11e5-851e-32475bd52908.png)

or put it in the address bar:
http://pcottle.github.io/learnGitBranching/?NODEMO&locale=ja

or change your browser language to a supported language and we will detect it

hope that helps!
