### ISSUE TITLE
Window with lessons dance when I try to select lessons from 'Ramping Up' section

### ISSUE THREAD

**Issue by alexeiberkov** [pcottle/learnGitBranching#288]
As a user I am not able to select lessons from second row at "main" dialog. It happens on mouseOver event. Just check this video with bug reproduction: http://monosnap.com/file/F3zrhiNVC7vZRD4OgLaL9pANkKd4Zp

Browser: Google Chrome
Version: 43.0.2357.81 (64-bit)
Environment: http://pcottle.github.io/learnGitBranching/

**Comment by pcottle** [comment]
Yeah ugh this is a super annoying UI bug with webkit / box layout. I'll fix it in a bit, but you can instead use the **arrow keys** to navigate your level selection and then hit **enter** to select a given level

**Comment by pcottle** [comment]
Alright @alexeiberkov I can't actually repro on chrome or safari on my machine but I can repro a similar issue on Firefox, and I just put up the fix. It involves changing the design of the levels page a bit but I think it's a step forward anyways

**Comment by pcottle** [comment]
Alright pushing the fix out to prod -- @alexeiberkov mind checking to see if its fixed on your machine?

**Comment by pcottle** [comment]
You should see an expanded level dialog:

![screen shot 2015-06-06 at 1 17 09 pm](https://cloud.githubusercontent.com/assets/1135007/8021282/5c3f8214-0c4e-11e5-9c0b-3782013f68b8.png)

**Comment by alexeiberkov** [comment]
Okay. The problem has gone now.
