### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by syzer** [pcottle/learnGitBranching#300]
```bash
React packager ready.

 ERROR  watch EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch"}
Error: watch EMFILE
    at exports._errnoException (util.js:746:11)
    at FSWatcher.start (fs.js:1172:11)
    at Object.fs.watch (fs.js:1198:11)
    at NodeWatcher.watchdir
```
on mac os
`ulimit -n`
6553

**Comment by mizunashi-mana** [comment]
I think this is same issue:
https://github.com/facebook/react-native/issues/1537

Try to use `sudo` if you not do yet.

**Comment by syzer** [comment]
might help
```
cat /etc/launchd.conf
limit maxfiles 1000000 1000000
```

**Comment by pcottle** [comment]
Yeah can we consolidate this into facebook/react-native#1537 ? Any react native frameworky things should go there.

Btw my other repository at:
https://github.com/pcottle/MinCalTrain

Has an actual working / complete RN app -- I started out doing LGB but I wanted to focus on something more tractable and release that first. Besides, RN art has to come a long way before it can match raphael. the animation stuff will be huge though.

![photo jul 01 5 11 09 pm](https://cloud.githubusercontent.com/assets/1135007/8489086/da4331c8-20cc-11e5-857f-0bd258ef4d82.png)
