### ISSUE TITLE
Add translation mechanism for "Objective"

### ISSUE THREAD

**Issue by alexandear** [pcottle/learnGitBranching#321]
String "Objective" can't be translated to any language except English.

![image](https://cloud.githubusercontent.com/assets/3228886/10674786/80331c5c-7905-11e5-9ce8-fb190bddf0ce.png)

**Comment by alexandear** [comment]
I could solve this issue.

**Comment by pcottle** [comment]
@alexandear itd be great if you could send the pull request! I think either the translated string is missing for russian or simplify I forgot to wrap it in a `intl` call...

**Comment by alexandear** [comment]
You forgot it to wrap if file `src/js/react_views/LevelToolbarView.jsx`
```
<div className="showObjectiveWrapper">
            <button
              onClick={this.props.onObjectiveClick}
              type="button">
              Objective
            </button>
</div>
```

**Comment by pcottle** [comment]
Ah yeah my bad -- then it should just be a literal with an intl call. i probably messed it up while converting to react

something like

```
<button>
  {intl.str('objective')}
</button>
```

@alexandear  want to send the PR? Or want me to do it?

**Comment by alexandear** [comment]
@pcottle I can send the PR on Monday
