### ISSUE TITLE
Translation of "Select a level" doesn't work

### ISSUE THREAD

**Issue by alexandear** [pcottle/learnGitBranching#331]
* Change language from English to Russian.
* **Expected:** text "Select a level" changed to "Выбери уровень".
* **Current:** text remains English "Select a level".

![screenshot from 2015-11-15 20 52 21](https://cloud.githubusercontent.com/assets/3228886/11170370/ee580c96-8bda-11e5-943d-db14a4389d83.png)

Translation strings for "Select a level" is present in file [strings.js](https://github.com/pcottle/learnGitBranching/blob/master/src/js/intl/strings.js).
```
  'select-a-level': {
    '__desc__': 'The prompt to select a level on the drop down view',
    'en_US': 'Select a level',
    'de_DE': 'Level auswählen',
    'zh_CN': '选择一关',
    'zh_TW': '選擇其中一關',
    'es_AR': 'Seleccioná un nivel',
    'pt_BR': 'Selecione um nível',
    'fr_FR': 'Choisissez un niveau',
    'ru_RU': 'Выбери уровень',
    'uk': 'Обери рівень'
  },
```

**Comment by pcottle** [comment]
Ah yeah, this is because we cache the instance of the modal terminal and even though we re-render for locale store / level store updates, it wont reset the title of the terminal.

lemme see if I can fix this!

**Comment by pcottle** [comment]
<img width="865" alt="screen shot 2015-11-15 at 12 04 32 pm" src="https://cloud.githubusercontent.com/assets/1135007/11170717/169d159c-8b91-11e5-8ede-1a1dd7f44f41.png">
<img width="814" alt="screen shot 2015-11-15 at 12 04 47 pm" src="https://cloud.githubusercontent.com/assets/1135007/11170718/169d81f8-8b91-11e5-8d81-a3571a189d59.png">

fixed! wish these were react components :(

**Comment by pcottle** [comment]
Thanks for the report -- this was broken forever
