### ISSUE TITLE
Unable to delete a commit in remote repo by force push

### ISSUE THREAD

**Issue by Radrik5** [pcottle/learnGitBranching#362]
![image](https://cloud.githubusercontent.com/assets/9339459/13378843/cfe44a12-de24-11e5-953d-7d80c3026df6.png)

Howerver, this works in Git.

**Comment by pcottle** [comment]
Yep this is a bug, let me try to fix it. I handle the opposite case of
course, just not the deletion case :P

On Sunday, February 28, 2016, Dmitry Oksenchuk <notifications@github.com>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/9339459/13378843/cfe44a12-de24-11e5-953d-7d80c3026df6.png>
>
> Howerver, this works in Git.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pcottle/learnGitBranching/issues/362>.
>


-- 
-Sent from Gmail Mobile
