### ISSUE TITLE
Problem to update packages

### ISSUE THREAD

**Issue by icalderond** [pcottle/learnGitBranching#363]
When I want to download it takes more than half an hour and not download anything.
![screen shot 2016-02-28 at 11 38 57](https://cloud.githubusercontent.com/assets/5691112/13380774/f6c7e874-de0f-11e5-834f-577fbbb2c7ba.png)

**Comment by pcottle** [comment]
this is probably an npm issue -- what version are you using? supposedly 3 is a lot slower, I would stick to 2.

either way this is good feedback for npm team, but we cant do much for this

**Comment by icalderond** [comment]
it is correct. I update npm and work perfectly
