### ISSUE TITLE
Tiny Correction for korean translation

### ISSUE THREAD

**Issue by jmg7173** [pcottle/learnGitBranching#366]
https://github.com/pcottle/learnGitBranching/blob/master/src/levels/remote/tracking.js#L991

**Comment by mingrammer** [comment]
Japanese?

**Comment by pcottle** [comment]
Mind sending the PR? this is all latin to me!

**Comment by mingrammer** [comment]
https://github.com/pcottle/learnGitBranching/blob/master/src/levels/remote/tracking.js#L991
 is japanese, not korean. :(

**Comment by jmg7173** [comment]
Oh, at that time, that line was Korean. So I suggested to correct typo. Sorry :(

**Comment by mingrammer** [comment]
Ah, It seems to have already been corrected. You may close this issue :)
