### ISSUE TITLE
Problem in "Reversing changes" challenge

### ISSUE THREAD

**Issue by ffxsam** [pcottle/learnGitBranching#368]
![learn_git_branching](https://cloud.githubusercontent.com/assets/12532733/14123746/ea78ebfe-f5b6-11e5-9f22-ecf261bc6a68.png)

The challenge is:

>To complete this level, reverse the two most recent commits on both local and pushed.

On `local`, the command should be:

    git reset HEAD~2

though the lesson says the command should be `git reset HEAD~1`. To reset *two* commits, this is incorrect.

**Comment by pcottle** [comment]
Sorry, it means the two most recent commits, meaning C3 and C4. i can update the language here.

2 total, 1 per branch

**Comment by ffxsam** [comment]
Ahh, gotcha. Thanks for clearing that up!

**Comment by pcottle** [comment]
pushed the site, should be updated now
