### ISSUE TITLE
Something went wrong TypeError: Cannot read property 'canvas' of undefined

### ISSUE THREAD

**Issue by Ajedi32** [pcottle/learnGitBranching#371]
While trying to load my custom level (<http://pcottle.github.io/learnGitBranching/?gist_level_id=be6d08de5273c85e0e151769d6891079>) the following error occured:

![Something went wrong TypeError: Cannot read property 'canvas' of undefined](https://cloud.githubusercontent.com/assets/1876931/14565258/cfafb118-02ef-11e6-90eb-909158e23afd.png)

Everything seemed to still work okay until I got past the dialog boxes and into the level itself:

![Extra tree](https://cloud.githubusercontent.com/assets/1876931/14565260/d11c86a2-02ef-11e6-9bc4-2dca8d96848d.png)

There's an extra repository tree there that doesn't seem to do anything.

I'm running Chrome 50 on Windows 7. Here's a link to the source gist: https://gist.github.com/Ajedi32/be6d08de5273c85e0e151769d6891079

**Comment by pcottle** [comment]
weird. did you see any errors in the JS console? When did you make the
level?

On Fri, Apr 15, 2016 at 7:55 AM, Andrew Meyer <notifications@github.com>
wrote:

> While trying to load my custom level (
> http://pcottle.github.io/learnGitBranching/?gist_level_id=be6d08de5273c85e0e151769d6891079)
> the following error occured:
>
> [image: Something went wrong TypeError: Cannot read property 'canvas' of
> undefined]
> <https://cloud.githubusercontent.com/assets/1876931/14565258/cfafb118-02ef-11e6-90eb-909158e23afd.png>
>
> Everything seemed to still work okay until I got past the dialog boxes and
> into the level itself:
>
> [image: Extra tree]
> <https://cloud.githubusercontent.com/assets/1876931/14565260/d11c86a2-02ef-11e6-9bc4-2dca8d96848d.png>
>
> There's an extra repository tree there that doesn't seem to do anything.
>
> I'm running Chrome 50 on Windows 7.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pcottle/learnGitBranching/issues/371>
>



-- 
Peter M Cottle
UC Berkeley Class of 2012
Master's of Science, Mechanical Engineering
UC San Diego Class of 2011
Bachelor's of Science, Mechanical Engineering
(408) 455 9405

"Equipped with his five senses, man explores the universe around him and
calls the adventure Science." - Edwin Hubble

**Comment by Ajedi32** [comment]
Just tried it on another computer. Chrome 50 on Windows 10. Same error.

Browser console is showing:

![Browser console](https://cloud.githubusercontent.com/assets/1876931/14578218/dda1f918-0347-11e6-87d4-10dbcc474d4d.PNG)

Can't reproduce on Firefox 38.

**Comment by pcottle** [comment]
Ah yeah I have a repro locally as well. I don't think it's related to the canvas JS error, its something silent (the JS console doesn't show anything serious). I'll look this weekend!

**Comment by pcottle** [comment]
Fixed it! Yeah it was a weird race condition with raphael not initializing fully yet, which meant one of the JS calls fataled

**Comment by pcottle** [comment]
Ill push the site with the fix now, but your level seems to not be working (i tried the commands and once i got to the final state, it didnt register as fixed). but maybe thats just due to bad JSON being in your level config :P

**Comment by Ajedi32** [comment]
Had to clear my browser cache to get it to work, but everything seems to working now. Thanks!
