### ISSUE TITLE
Start from scratch when you make a mistake

### ISSUE THREAD

**Issue by LydiaF** [pcottle/learnGitBranching#375]
Hey,

Thank you for the wonderful tutorial.

Sorry if I have missed how to do this, but is there a way to get rid of your work and start again quickly? So, when you make a mistake you do not have to go through the lesson again to get a fresh page.

Many thanks,

Lydia

**Comment by pcottle** [comment]
Yes, the "reset" command does this! Try that out and it should do what you
want.

You can always type help to see all the available commands.

On Saturday, May 28, 2016, Lydia Flynn <notifications@github.com> wrote:

> Hey,
>
> Thank you for the wonderful tutorial.
>
> Sorry if I have missed how to do this, but is there a way to get rid of
> your work and start again quickly? So, when you make a mistake you do not
> have to go through the lesson again to get a fresh page.
>
> Many thanks,
>
> Lydia
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pcottle/learnGitBranching/issues/375>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABFRn4okXjCeoROQK3h2GuFw0gar7O_zks5qGMcCgaJpZM4IpLEn>
> .
>


-- 
-Sent from Gmail Mobile

**Comment by LydiaF** [comment]
Thank you thank you!
