### ISSUE TITLE
No-op and undo let's you count down "steps taken" counter

### ISSUE THREAD

**Issue by nicolaiskogheim** [pcottle/learnGitBranching#378]
*I did not realise what the cause was when I started writing this issue, but now that I think I do I can tell you that the choice of level is not important, only the combination of some operation that doesn't change the tree, followed by an `undo`*

### Steps to reproduce
Type the following commands
```sh
level advanced1
hide goal
git rebase side another
git rebase bugFix another
git rebase master another
git merge master
undo
git branch -f master another
```

#### Expected Result
The dialog says the challenge was completed in *4* steps.

#### Actual Result
The dialog says the challenge was completed in *3* steps.

![Screenshot](https://www.dropbox.com/s/hpgcfwwkjj2lavm/Screenshot%202016-07-03%2001.27.20.png?dl=1)

### Cause
This is what I was able to gather from playing around:
```sh
level advanced1
hide goal
git rebase side another
git rebase bugFix another
git rebase master another

# This is a no-op because 'master is up to date',
# and does not count towards the number of steps
# one have used so far
git merge master

# The undo command is oblivious of the previous
# operation being a no-op, resets the state to
# what it was before `git merge master` (aka.
# nothing changes), and subtracts one step
# from the final count.
undo

git branch -f master another
```

I was eventually able to get a score of 1, by repeating the noop-undo combination 🏆

**Comment by pcottle** [comment]
Ahhhh yes good find :) we must be assuming in the undo command that the
previous command was not a no-op and thus we can reduce the number of steps.

This might be tricky to patch. How do you feel about not giving credit back
after undos? Harsh but probably most correct.

I can see if I can do the real patch

On Saturday, July 2, 2016, Nicolai Skogheim <notifications@github.com>
wrote:

> *I did not realise what the bug was when I started writing this issue, but
> now that I think I do I can tell you that the choice of level is not
> important, only the combination of some operation that doesn't change the
> tree, followed by an undo*
> Steps to reproduce
>
> Type the following commands
>
> level advanced1
> hide goal
> git rebase side another
> git rebase bugFix another
> git rebase master another
> git merge master
> undo
> git branch -f master another
>
> Expected Result
>
> The dialog says the challenge was completed in *4* steps.
> Actual Result
>
> The dialog says the challenge was completed in *3* steps.
>
> [image: Screenshot]
> <https://camo.githubusercontent.com/1145a5e3ff323cd8369dc9e8752d3b5c5b746820/68747470733a2f2f7777772e64726f70626f782e636f6d2f732f687067636677776b6a6a326c61766d2f53637265656e73686f74253230323031362d30372d303325323030312e32372e32302e706e673f646c3d31>
> Cause
>
> This is what I was able to gather from playing around:
>
> level advanced1
> hide goal
> git rebase side another
> git rebase bugFix another
> git rebase master another
> # This is a no-op because 'master is up to date',# and does not count towards the number of steps# one have used so far
> git merge master
> # The undo command is oblivious of the previous# operation being a no-op, resets the state to# what it was before `git merge master` (aka.# nothing changes), and subtracts one step# from the final count.
> undo
>
> git branch -f master another
>
> I was eventually able to get a score of 1, by repeating the noop-undo
> combination 🏆
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pcottle/learnGitBranching/issues/378>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/ABFRn4hKTE3g2TxEjzAz3Y6STbRdXA04ks5qRvtMgaJpZM4JDxfm>
> .
>


-- 
-Sent from Gmail Mobile

**Comment by pcottle** [comment]
any thoughts?

**Comment by pcottle** [comment]
Fixed! Its a bit different now in levels but we only push undo state if the command actually counts -- which means when we do the undo command, we can both pop state and pop the commands issued.

so `undo` after a no-op command will actually go back to the last time something ACTUALLY changed, not the identical state from before.

**Comment by nicolaiskogheim** [comment]
Sorry I wasn't able to reply on this. I haven't had access to internet the last days.

I think you solved it beautifully!

**Comment by pcottle** [comment]
no worries -- replies are sometimes a good motivator for me to get off my
butt and fix something, but i fixed another issue this week too.

glad i could at least do it in a way thats more correct!

On Fri, Jul 8, 2016 at 5:16 AM, Nicolai Skogheim <notifications@github.com>
wrote:

> Sorry I wasn't able to reply on this. I haven't had access to internet the
> last days.
>
> I think you solved it beautifully!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/pcottle/learnGitBranching/issues/378#issuecomment-231344915>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABFRnyvJY0GSQatp6MppovszBavttwxvks5qTj-qgaJpZM4JDxfm>
> .
>



-- 
Peter M Cottle
UC Berkeley Class of 2012
Master's of Science, Mechanical Engineering
UC San Diego Class of 2011
Bachelor's of Science, Mechanical Engineering
(650) 862 3491

"Equipped with his five senses, man explores the universe around him and
calls the adventure Science." - Edwin Hubble
