### ISSUE TITLE
git fakeTeamwork command hangs when followed by two words (not numbers)

### ISSUE THREAD

**Issue by marcosmazz** [pcottle/learnGitBranching#381]
**Steps to reproduce**

type de following commands
```
git clone
git fakeTeamwork a b
```

**Expected result**
```
syntax error message
```
**Actual result**
*system hang*

Additionally when the first parameter to the command is a non existing branch the commit equally done.

**Possible Cause**
Bad validation of fakeTeamwork command arguments in ` learnGitBranching/src/js/git/commands.js `

**Comment by pcottle** [comment]
thanks for the report @marcosmazz! agreed there was some clowny validation going on :) should be all fixed up now and the tests pass

![screenshot 2016-07-06 at 9 19 01 pm](https://cloud.githubusercontent.com/assets/1135007/16642381/45e9d042-43bf-11e6-846a-ba65453d777c.png)
