### ISSUE TITLE
Alternative Solution for Juggling Commits #2??

### ISSUE THREAD

**Issue by sinhote** [pcottle/learnGitBranching#385]
I may be wrong, but I (think I) solved the Juggling Commits #2 level but the page would not acknowledge that. I had to come here and check the right solution in the source to see what I was doing wrong. I still do not see why my alternative should not be valid, so I am assuming it is a bug, or I'm failing to see where the problem is. Here's what I've done:

```
git commit --amend newImage
git cherry-pick caption
git branch -f master newImage
```

Granted, the "newImage" branch is no longer pointing to the original commit, but that was not (I think) part of the requirements to complete the level. 

I hope this input helps. 

Keep up the good work! I think this whole project is amazing!

**Comment by pcottle** [comment]
Glad you like the project!

cherry-pick is disabled for the level, how did you execute it?

here is what i get when i do those commands

![screenshot 2016-07-27 at 9 59 04 pm](https://cloud.githubusercontent.com/assets/1135007/17201674/6de27f72-5445-11e6-9aee-b80e01663c28.png)

**Comment by sinhote** [comment]
Sorry, I mean "Juggling Commits #2", that is the level "mixed3". I'm sorry if I was not too clear in my first response.

**Comment by pcottle** [comment]
<img width="1107" alt="screenshot 2016-07-28 at 5 45 56 pm" src="https://cloud.githubusercontent.com/assets/1135007/17234166/29e15644-54eb-11e6-9a19-f4b538ad2921.png">

now i get this -- also seems like that one command didnt execute?

**Comment by sinhote** [comment]
Hi,

This is so weird --it did not work like that before (and actually I'd say that the way it works it's wrong). You see, when you `amend` the newImage commit, suddenly caption points at C3', not C3. I'm not a git expert, but I think that's not right: `commit --amend` should indeed create a new C2' commit, but C3 and the tag "caption" should still hang from C2, not from C2' (that's exactly the behavior I've seen before I filed this ticket).

OK, I have taken a pause and did the experiment with a real git repo. The problem is that you cannot commit to a branch you have not checked out. That means that `git commit --amend newImage` should NOT work (one can only ammend -or commit, for that matter- in the current branch). 

That makes the "real" solution: 
```
git checkout newImage
git commit --amend
git cherry-pick caption
git branch -f master newImage
   [and perhaps]
git checkout master
```
, which is obviously not so efficient as the proposed solution and it changes the original `newImage` branch, but on the other hand does not create a dangling commit (that's mostly irrelevant, I know, but I need to defend my alternative :P) and it should still be considered valid (unless you explicitly state that the `newImage` branch should not be modified):

![learngit](https://cloud.githubusercontent.com/assets/2742080/17242227/5a96e98a-5576-11e6-801d-2be409973683.png)

Sorry for the mess! I hope that everything is clear now.

**Comment by pcottle** [comment]
yeah the issue is that we are not throwing on that last arg in the git commit --amend case. from the man page:

```
 --amend
           Replace the tip of the current branch by creating a new commit. The recorded tree is prepared as usual (including the effect of the
           -i and -o options and explicit pathspec), and the message from the original commit is used as the starting point, instead of an
           empty message, when no other message is specified from the command line via options such as -m, -F, -c, etc. The new commit has the
           same parents and author as the current one (the --reset-author option can countermand this).

           It is a rough equivalent for:

                       $ git reset --soft HEAD^
                       $ ... do something else to come up with the right tree ...
                       $ git commit -c ORIG_HEAD

           but can be used to amend a merge commit.

```

**Comment by pcottle** [comment]
let me see if i can do a tighter arg validation on that command....

**Comment by pcottle** [comment]
<img width="1026" alt="screenshot 2016-07-31 at 4 05 11 pm" src="https://cloud.githubusercontent.com/assets/1135007/17279977/93d77840-5738-11e6-9130-0ec638bc462b.png">

there we go :) yeah i was being lazy an doing an array cast in the options map for `isAmend` and didn't actually validate that there were no options provided to `amend`.

easy fix!

**Comment by pcottle** [comment]
thanks for your great feedback btw -- this was definitely wrong :)

**Comment by sinhote** [comment]
A pleasure! 

I was wrong too, anyway... In this case, it seems that two wrongs CAN make a right! :D

**Comment by lbm364dl** [comment]
> That makes the "real" solution:
> 
> ```
> git checkout newImage
> git commit --amend
> git cherry-pick caption
> git branch -f master newImage
>    [and perhaps]
> git checkout master
> ```

I think it's not clear from the comments here if this was supposed to be an accepted solution or not. I mean, I see this thing about the 'full credit if there is difference between apostrophes', but why is that enforced and the solution above is not accepted?
