### ISSUE TITLE
[Proposal] Improve the UI Designs

### ISSUE THREAD

**Issue by mingrammer** [pcottle/learnGitBranching#390]
LGB is very well made for learning git.
But, the UI design (visual design) is not good a little bit i think. For example, macOS-like topbar (this is unnatural), some icons and colors is not modern.

I want for modifying the UI design more modernize. So, the LGB will be more modern and pretty than now. (Also, it can imporves the user experiences)

How about you?

**Comment by gergelypolonkai** [comment]
+1 (or more like -1) for the OS/X specifix “window” header.

**Comment by mgarciaisaia** [comment]
Do you have any proposal for how you think it should look like?

**Comment by mingrammer** [comment]
@mgarciaisaia I don't have concrete proposal now. but if some people are agree with that, i'm willing to make the prototype design for proposal.

**Comment by pcottle** [comment]
Yeah I'll agree that I'm not an expert on visual design :P 

The OSX windows/headers were inspired by the ones on try.github.com:
https://try.github.io/levels/1/challenges/1

Like the authors at GitHub, I do think that making the educational experience as close as possible to the real-life experience (aka typing commands into a fake terminal) is beneficial. Some people find terminals intimidating when they shouldn't be; getting experience with terminals in a very forgiving and visual environment should hopefully abate some of that fear. Similarly, getting used to modifying the state of the world only through commands is great training for using Git in practice.

On the other hand though we went pretty far in the skeuomorphic direction; people started assuming that the windows were fully interactive/simulated and wanted the buttons to work. Implementing this functionality was perhaps a mistake.

Anyways yeah some concrete proposals and mockups of the changes would be great.

**Comment by gergelypolonkai** [comment]
If you want to keep the Terminal window, why not going without any buttons? This way it would still resemble a window, but maybe prevent people from thinking it can be moved, closed, etc. Also, all popular DE today except OS/X and Ubuntu's Unity keeps its window buttons on the right (correct me if I'm wrong).

Another (but maybe strange) way could be if the whole window would act as a terminal window, putting the typed commands behind the commit graph, dimmed. For this, a button/keyboard shortcut could be used to switch between the command history and the graph.

Keep in mind that I'm not an UX designer, so these are just wild ideas.

**Comment by mingrammer** [comment]
@pcottle Thanks. So, I'll make concrete proposal with visual prototype (maybe this is just visual design without any functionalities. but it should represents the how the functions are applied) in september as possible.

And .. how can i propose the prototype design if that is done? (in here?)

**Comment by mingrammer** [comment]
@pcottle @gergelypolonkai 
I'm not a UX designer too. So, my proposal may not be perfect. (it may be wrong enough)
Therefore, I need for some your helps. (and some other people).

I want to make it together :D

**Comment by pcottle** [comment]
> visual prototype (maybe this is just visual design without any functionalities. but it should represents the how the functions are applied) in september as possible.

> And .. how can i propose the prototype design if that is done? (in here?)

yeah just some mockups are fine (using Sketch or something similar and uploading images), or if you really want you can make a prototype and send it as a PR that I can download locally and play with

either works! 

> Another (but maybe strange) way could be if the whole window would act as a terminal window, putting the typed commands behind the commit graph, dimmed.

I actually prototyped something similar to this and people found it confusing how to switch between the two, and usually just didn't bother with "switching" and just tried to read the text around the UI in front.

I agree its difficult though -- you want to show all the visual layout of the tree, but also the command history is pretty important too :P

**Comment by pcottle** [comment]
(closing out old issues)
