### ISSUE TITLE
Add link to translated versions

### ISSUE THREAD

**Issue by derek-austin** [pcottle/learnGitBranching#391]
learnGitBranching have a link to the demo mode http://pcottle.github.com/learnGitBranching/?demo
Please add a link to the different translations:
http://pcottle.github.com/learnGitBranching?translation=japanese
http://pcottle.github.com/learnGitBranching?translation=korean
http://pcottle.github.com/learnGitBranching?translation=simplifiedChinese
http://pcottle.github.com/learnGitBranching?translation=traditionalChinese
http://pcottle.github.com/learnGitBranching?translation=spanish
http://pcottle.github.com/learnGitBranching?translation=french
http://pcottle.github.com/learnGitBranching?translation=german
http://pcottle.github.com/learnGitBranching?translation=russian
http://pcottle.github.com/learnGitBranching?translation=ukrainian

**Comment by pcottle** [comment]
what do you mean? add a link to the UI or the readme?

we already have the former (a way to switch translations) and we default to your browser header language, so not sure what else we could do.

**Comment by pcottle** [comment]
bottom right:
<img width="591" alt="screenshot 2016-09-23 at 6 52 11 am" src="https://cloud.githubusercontent.com/assets/1135007/18788056/452d4df4-815a-11e6-8363-251a5074faf1.png">
