### ISSUE TITLE
Skip "git push" in Remotes>Pushin' with "git commit; git commit; git clone"

### ISSUE THREAD

**Issue by Sim00n** [pcottle/learnGitBranching#398]
Hi,
There are obviously different ways of getting to a specific solution. On the practical part of the Pushin' section in Remotes, it asks the user to create two commits and push them to remote. However, it doesn't exclusively state that you have to create the remote yourself. If you're going fast you might want to jump into doing 2 commits and then a push. You've obviously forgot to create the remote, you'll get an error during the push so you will try using "git clone" and the command will work. The problem is that since the two commits are already created on the local, it will make a clone with those two commits and the task will be passed without explicitly using "git push" which is the point of the task.
I'm not sure if you'd consider this a bug but I guess the interpretation depends on how explicit should the solutions be.
Thanks for the great tutorial though!

**Comment by pcottle** [comment]
Ahh yeah, that's a tricky one. the issue is that we do stateless tree compares so we can't tell if you got there from git pushing or from just committing and cloning.

we could start you off on a cloned tree ahead of time, that might work. let me check that out

**Comment by pcottle** [comment]
done! now you start with an origin to begin with.

i might make the same mistake on some other levels (where you can technically build up the final state locally and then clone later) but this level is so simple its probably worth doing the fix
