### ISSUE TITLE
[bug] git pull --rebase works incorrectly if there were no local commits

### ISSUE THREAD

**Issue by selivan** [pcottle/learnGitBranching#400]
**Steps to reproduce:**

1. Open http://learngitbranching.js.org/?NODEMO
2. Type commands:
```
git clone
git fakeTeamwork
git pull --rebase
```

**Result:**

Remote commit C2 is transferred to the local repository, o/master points to C2, but master is not fast-forwarded to C1, it remains on C1.

**Expected result:**

Local master should be also fast-forwarded to C2.

![learngitbrunching js-bug-2016-12-02-09 26 06 pm](https://cloud.githubusercontent.com/assets/1208989/20845447/2fb70704-b8d6-11e6-9f8a-fad6f4478f92.png)

P.S. I checked this out with real git repository - it works as I expect.

**Comment by pcottle** [comment]
Ah yeah, you can see that it attempts to fast forward local master but something goes wrong since its expecting a rebase. my bad! let me debug

doing it without the `--rebase` works fine of course

**Comment by pcottle** [comment]
Seems we had code here to handle this:
https://github.com/pcottle/learnGitBranching/blob/master/src/js/git/index.js#L1430

most likely just a regression. comparing error messages is quite brittle lol
