### ISSUE TITLE
Goal window hides console

### ISSUE THREAD

**Issue by Graham42** [pcottle/learnGitBranching#403]
By default the Goal window shows over top of the console and covers the "Hide Goal" button. For someone who is not familiar with a Mac they might not figure out how to hide the Goal Window. There's lots of room, we should have it open beside the console.

**Comment by pcottle** [comment]
we also call out that you can hide the window with `hide goal` (inlined into the goal window at the top). and you can also drag it around, which hopefully anyone who has used a window-based GUI can understand.

closing this out since i dont have any more ideas but thanks for the feedback!
