### ISSUE TITLE
Why title of terminal is CAPITALIZED when locale is changed

### ISSUE THREAD

**Issue by AlexByte** [pcottle/learnGitBranching#413]
Link to test – http://learngitbranching.js.org/?NODEMO&locale=test

![lgb term title](https://cloud.githubusercontent.com/assets/25251772/23827876/f0257d62-06cf-11e7-82a6-4ee6ed14d3f5.png)

**Comment by pcottle** [comment]
i think this is because `test` isnt a valid locale, so we try to just take the english version of the string. dont think this is worth investing time to fix :)

**Comment by AlexByte** [comment]
OK, valid locale http://learngitbranching.js.org/?NODEMO&locale=fr_FR

**Comment by pcottle** [comment]
There we go! Fixed. I believeeee this was because back in the day, there were some buttons that had labels that only made sense when uppercased. but it seems that the title header is the only `intl-aware` span left, and so we can remove that logic!
