### ISSUE TITLE
Add interception of the `tab` key

### ISSUE THREAD

**Issue by AlexByte** [pcottle/learnGitBranching#415]
If the <kbd>Tab</kbd> is accidentally pressed, the terminal loses focus, the input command is overridden by the prompt. It's annoying.

![lgb tab](https://cloud.githubusercontent.com/assets/25251772/23837193/6d147b82-0795-11e7-8f6a-28ca5e8b9042.png)

**Comment by pcottle** [comment]
Good point! fixing now
