### ISSUE TITLE
Fake Teamwork Feedback

### ISSUE THREAD

**Issue by smizell** [pcottle/learnGitBranching#417]
I have just found the sandbox feature of this tool to use for giving live tutorials for Git, and it's perfect. I can show commands and how they look visually in real time. While training, I've found a few things around fake teamwork that were a tad difficult to use and explain.

First, using `git clone` to create a remote repository was hard to explain. While I understand the rationale, it felt like it confused the use of `git clone`, especially during training. I had wondered if a command specifically for it would be helpful, like `remote init` would be helpful.

In a related point, it felt like putting commands under `git` that were not `git` required some explaining, specifically `git fakeTeamwork`. Would it make sense to pull this out to it's own command to be called via just `fakeTeamwork`?

Just to give a note about `fakeTeamwork`, it would have been nice to be able to run commands against that remote repo. This would allow for me to create branches there before they were created locally among other things. I had thought, maybe you could have `git-remote` or prefix everything with `remote` like `remote git checkout -b branch`. 

Lastly, I think it would help to have labels after running `git remote` to show one is "local" and the other is "remote."

---

These are just some thoughts/feedback. If you have any interest in any of these, I'd be happy to start tinkering with the code to see if I could do it. This is a really wonderful tool. Thanks so much for creating and sharing it.

**Comment by pcottle** [comment]
Yeah `git clone` isn't perfect. Usually a lot of people start a repo in one of two ways:

 - `git init` (which is not applicable in this case)
 - `git clone github://blah`, which is the closest analogy to what we have.

Most newcomers to git have GitHub initialize the repo instead of the multi-step process of `git init; git add whatever.txt; git commit; (go to github and make an empty repo); git add remote origin foobar; git push`

so I went with clone because of that

**Comment by pcottle** [comment]
I usually reserve high-level commands that arent prefixed with git for things specific to the demo. like `levels`, `sandbox`, and others. `fakeTeamwork` isnt a real git command but modifies git state, hence why I included it there

**Comment by pcottle** [comment]
`git-remote checkout -b foo` is a cool idea! I think I made some assumptions that the remotes cant get into certain states though, so you might have to be a tad careful on forwarding 100%. Would you want to take a crack at putting up the PR?

**Comment by pcottle** [comment]
(closing out old issues)
