### ISSUE TITLE
[bug] Correct invalid solution for 'manyRebases.js'

### ISSUE THREAD

**Issue by teddy-error** [pcottle/learnGitBranching#428]
The solution string in `/src/levels/rebase/manyRebases.js` does not appear to solve the `Rebasing over 9000 Times` level. Specifically, the final command of the string `git rebase another master` should perhaps instead be `rebase master another`, but this still requires an additional command to
move `master` to C7.

Admittedly, my Git-fu is not over 9000 and I could be missing the clever solution. I was only able to solve in five, rather than four commands. In any case, the provided solution does not satisfy the problem statement.

**Comment by teddy-error** [comment]
Whoops, I must have done something wrong here. Although it was creating a new branch at Master previously, after resetting and applying the commands in the solution tree on a clean level, the solution looks to be correctly satisfying the problem statement. Hooray!

**Comment by pcottle** [comment]
Glad you figured it out! We actually have test coverage that ensures each level:
https://github.com/pcottle/learnGitBranching/blob/master/__tests__/levels.spec.js#L11

can be solved by the solution command:
https://github.com/pcottle/learnGitBranching/blob/master/__tests__/base.js#L37

so id be surprised if you hit a condition where that didn't hold. thanks for stopping by and leaving the feedback though!
