### ISSUE TITLE
Suggestion: levels workflows, branching models and best practices

### ISSUE THREAD

**Issue by natanbr** [pcottle/learnGitBranching#434]
Hi, 
There are some good blogs that suggest branching models and workflows for git. 
As example: [A successful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/), or [OneFlow](http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow)
By the way not everyone think that this is a good [model](https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/)
I suggest to add new tab for "real world" examples. With some levels as adding new feature to existing project, fixing bugs, etc. The main focus is keeping the remote branch clean according to the best practices.

Thanks

**Comment by pcottle** [comment]
Yeah I definitely don't think that [http://nvie.com/posts/a-successful-git-branching-model/](the successful git branching model) is the right one :P Over at Facebook/Instagram/Oculus, we have a single trunk that we push to and thats it. It's a lot simpler than maintaining all these different branches and forks.

That being said I didn't want to be too assumptive/argumentative about the right models; I tried to introduce the git tools without imposing a certain way to use them, so thats why ive avoided the third tab for the time being around the right way to use git. thanks for the suggestion though!
