### ISSUE TITLE
Typo in level "remoteAdvanced1"

### ISSUE THREAD

**Issue by Alsturm** [pcottle/learnGitBranching#440]
Remote is referred as "origin" instead of "o". For example command `git pull o master --rebase` results in `o is not a remote repository! try adding origin that argument`, while `git pull origin master --rebase` works fine.

**Comment by pcottle** [comment]
yeah this is the unfortunate part of our UI -- we cant write out the whole remote name since it is too long, but the remote is truly named `origin` so the commands still take that in.

probably too late to change this now but thanks for the feedback!

**Comment by Alsturm** [comment]
Yeah, I remember this note about o vs origin in hints to some level. But before "remoteAdvanced1" level UI git commands accept `o` reference just fine...

**Comment by pcottle** [comment]
do they reference it by branch name though? 

I guess thats the inconsistency -- the branch name is `o/master` but the remote is named origin for the other commands :( gah

**Comment by Alsturm** [comment]
Any way, thanks for great resource!
