### ISSUE TITLE
SSL Cert Issue on Webpage

### ISSUE THREAD

**Issue by Propheis** [pcottle/learnGitBranching#442]
Sorry if this isn't the best place to inform you but you have a cert error (domain name on the cert doesnt match learngitbranching.js.org). This will probably drive a lot of people away from using your (amazing) resource!

**Comment by pcottle** [comment]
Whats the error you get? I see the 
![screenshot 2017-09-28 at 3 30 55 pm](https://user-images.githubusercontent.com/1135007/30993088-078fa164-a462-11e7-84d0-683c29e76e69.png)

but its not a huge deal?

**Comment by Propheis** [comment]
I think I see what the problem is. My browser will by default upgrade to SSL/TLS when available (via the HTTPS Everywhere plugin). The cert for the website is invalid, which is why the error below appears:
![screenshot](https://user-images.githubusercontent.com/665669/31001709-5d386bfa-a4d5-11e7-9e7d-dbd9e47e9ee8.png)

Trying to connect via https://learngitbranching.js.org will cause the error

**Comment by pcottle** [comment]
Ah I see, and yeah we 301 from http://pcottle.github.io/learnGitBranching/?demo to that domain...

I checked in https://github.com/js-org/dns.js.org and it can be configured! brb

**Comment by pcottle** [comment]
lets move this to:
https://github.com/js-org/dns.js.org/pull/1489
🎉
