### ISSUE TITLE
The web page is using the development build of React

### ISSUE THREAD

**Issue by arniu** [pcottle/learnGitBranching#452]
The browser plugin **React Developer Tools** complains that _This page is using the development build of React._

<img width="525" alt="learngit" src="https://user-images.githubusercontent.com/1286674/35429695-25dd65c8-02b0-11e8-911f-e26bd3f3b07c.png">

**Comment by pcottle** [comment]
<img width="599" alt="screenshot 2018-01-27 at 9 53 55 am" src="https://user-images.githubusercontent.com/1135007/35474795-0498f40c-0348-11e8-9cb7-0d23d2a656f2.png">
alright now we get this :) ill try to upgrade react as well

**Comment by pcottle** [comment]
I tried upgrading to react 15 but it caused a big build failure that was tough to debug :( if you have any trips or want to try locally, let me know!
