### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by maiya-22** [pcottle/learnGitBranching#455]
Hi,

I love your game.  

As a user, it would be way easier to understand what was going on, if the "objective" button's name was changed to "instructions."

Also, it would be great if you could see the instructions while also playing the game.  This makes it much easier to learn.

**Comment by pcottle** [comment]
Hrm, but that button only launches the *last* slide of the instructions, which is where I typically tell the user what the goal of the exercise is.

Would you want it changed to `Instructions` and also have it launch the guide from the beginning?

**Comment by maiya-22** [comment]
When I was trying to play it initially, I gave up because I felt lost.  I would have understood, if the button said "instructions" (because I would have assumed that it was the instructions for the current step);  but "instructions for this step" would have also been clear.   I interpreted "objective" to mean something like "what we are learning."  Like "objective: Learn Branching", etc.  Now that you explain it, it makes sense;  but when I was by myself with the game, I did not get it.

**Comment by pcottle** [comment]
Yeah I agree objective is a bit ambiguous. I'll switch it

**Comment by maiya-22** [comment]
Thank you!  It looks great.  My friend is using it now too.  
This game has been *so* helpful for learning git.

**Comment by pcottle** [comment]
Glad you've been finding it useful! 🎉
