### ISSUE TITLE
Text uses px styling leading to illegible font sizes on higher resolution

### ISSUE THREAD

**Issue by blonkm** [pcottle/learnGitBranching#457]
Text uses px styling leading to illegible font sizes, e.g. here (Goal to reach window). Resolution used: 1600x900.

![capture](https://user-images.githubusercontent.com/9397116/37876059-7781aaf0-3015-11e8-92c1-4830b6b4690c.PNG)

Best use `em` or `rem` sizes;

```
p.helperText, div.terminal-text p.helperText, .iRebaseDialog p.helperText {
    font-size: 10px;
}
```

**Comment by pcottle** [comment]
Aren't they equivalent though? Like if I specify the font size 0.625em instead of 10px, the calculated rendering stays the same correct?

**Comment by pcottle** [comment]
![screenshot 2018-03-25 at 11 40 26 am](https://user-images.githubusercontent.com/1135007/37878663-5597ca12-3021-11e8-93c1-9143056fbf27.png)

i have a diff for this locally but the results I get look exactly the same. Reopen the issue if theres an actual difference between the rendering of em vs px.

or are you saying you have a different default font size?

**Comment by blonkm** [comment]
Ok maybe you don't see the problem as I do. Normally when I get to a website where fonts are too small, I zoom in (CTRL+). Most browser do not offer the 'resize font' shortcut anymore and offer zoom only. 
The problem is that when I zoom the site to the point where the font in Goal is the same as the font in Instructions, the site becomes unusable because of overlapping pseudo-windows. I would advise to make the font in Goal bigger, whether in px or in em.
![capture](https://user-images.githubusercontent.com/9397116/37879113-344891f0-3041-11e8-9e52-4b80da19413a.PNG)

**Comment by blonkm** [comment]
Also maybe read [this](https://kyleschaeffer.com/development/css-font-size-em-vs-px-vs-pt-vs/)

**Comment by pcottle** [comment]
Ah yeah the zoom functionality on learn git branching is really difficult to support given how much manual graphics drawing and absolute positioning work we need to do. Sadly its out of scope for this app

**Comment by pcottle** [comment]
And yeah sounds like em is similar to pixel if the standard settings apply, only gets tricky/different if you change your default font size or are on super high density displays that do different base logic
