### ISSUE TITLE
Level Juggling Commits

### ISSUE THREAD

**Issue by coingraham** [pcottle/learnGitBranching#461]
Error: the option "--append" is not supported

Recreate the issue:

git rebase -i HEAD~2
(switch C2 and C3)
git commit --append
!! Error

**Comment by pcottle** [comment]
`git commit --append` isnt an option?

**Comment by pcottle** [comment]
```
[pcottle:~/Dropbox (Personal)/wip/learnGitBranching:master]$ git commit --append
error: unknown option `append'
usage: git commit [<options>] [--] <pathspec>...

  
```

**Comment by coingraham** [comment]
So walking through the instructions, we're told to run `commit --append` which I took to mean `git commit --append` (which throws the error).  What is the correct command?

**Comment by pcottle** [comment]
yep:

```
[pcottle:~/Dropbox (Personal)/wip/learnGitBranching:master]$ grep -re '--amend' . | wc -l
      75
[pcottle:~/Dropbox (Personal)/wip/learnGitBranching:master]$ grep -re '--append' . | wc -l
       0
```

**Comment by coingraham** [comment]
Wow, my brain saw append.  Thanks for looking into it and humoring me.
