### ISSUE TITLE
Visual errors with commits on webserver

### ISSUE THREAD

**Issue by larsbratholm** [pcottle/learnGitBranching#467]
The webserver at learngitbranching.js.org, which pcottle.github.com/learnGitBranching/ refers to, shows commit hashes visually with lower case letters (c1, c2, ...). However you have to write (git checkout C1 etc) to checkout them. git checkout c1 doesn't work.
The demo gif in the Readme shows the hashes with upper case letters, so I don't know if the webserver is not updated or if it's a font issue.

example: https://i.imgur.com/Msy35L9.png

**Comment by pcottle** [comment]
![screenshot 2018-05-23 at 3 49 48 pm](https://user-images.githubusercontent.com/1135007/40455239-f00324cc-5ea0-11e8-8cd6-5f21e17c0d97.png)
seems like a browser or font thing since even in the DOM we store them as C1

**Comment by pcottle** [comment]
gonna close out since putting the right content in the DOM is the best I can do :-/
