### ISSUE TITLE
git merge --no-ff bug?

### ISSUE THREAD

**Issue by fprochazka** [pcottle/learnGitBranching#469]
Hello, this simple operation 

```
git merge --no-ff bug
```

ends with an error

![image](https://user-images.githubusercontent.com/158625/41324303-216cbac8-6eb4-11e8-878d-3671a777cc04.png)

-----

This can be worked around by using a fake argument

```
git merge --no-ff 1 bug
```

----

minimal reproducible test case

```
git checkout -b bug
git commit
git checkout master
git merge --no-ff bug
```

**Comment by pcottle** [comment]
This is intentional more or less; just like `git merge` requires an argument, it does as well with the `--no-ff` flag.

i think the issue is the semantics of "1 argument". I actually mean "one non-flag argument" :)

**Comment by pcottle** [comment]
Oh I see what you mean, yes its likely just parsing it incorrectly. justasec

**Comment by pcottle** [comment]
![screenshot 2018-06-16 at 4 37 30 pm](https://user-images.githubusercontent.com/1135007/41503269-939de294-7183-11e8-901b-06ae56330fc7.png)

fixed!

**Comment by fprochazka** [comment]
@pcottle epic! Thank you! :)
