### ISSUE TITLE
`git branch -f` works but `git branch --force` doesn't

### ISSUE THREAD

**Issue by MustafaHaddara** [pcottle/learnGitBranching#472]
At least in level `mixed2`, I was getting `The option "--force" is not supported!` but `git branch -f` worked fine.

**Comment by pcottle** [comment]
![screenshot 2018-07-05 at 11 54 50 am](https://user-images.githubusercontent.com/1135007/42342173-3b4174e6-804a-11e8-9b0b-0c62da6ca983.png)

thats just the message for anything that doesnt have a mapping. we only support:

```
git commit

    --amend

    -a

    -am

    -m

git cherry-pick

git pull

    --rebase

git fakeTeamwork

git clone

git remote

    -v

git fetch

git branch

    -d

    -D

    -f

    -a

    -r

    -u

    --contains

git add

git reset

    --hard

    --soft

git revert

git merge

    --no-ff

git log

git show

git rebase

    -i

    --solution-ordering

    --interactive-test

    --aboveAll

    -p

    --preserve-merges

git status

git checkout

    -b

    -B

    -

git push

    --force

git describe

git tag

**Comment by MustafaHaddara** [comment]
@pcottle why do you support `git branch -f` and not `git branch --force`? They mean exactly the same thing...

**Comment by pcottle** [comment]
yeah you can see its pretty inconsistent above in terms of having `-b` but not `--branch`, or `-i` vs `--interactive`

no particular reason. i'll happily accept a PR that adds all the relevant aliases :)

**Comment by waldyrious** [comment]
For reference, these are the next ones I plan to work on when I get some time (no promises!):

- in `git remote`:
  - [ ] `--verbose` for `-v` 
- in `git branch`:
  - [ ] `--delete` for `-d`
  - [ ] `--all` for `-a`
  - [ ] `--remotes` for `-r`
- in `git rebase`:
  - [ ] `--interactive` for `-i`
- in `git checkout`:
  - [ ] `--branch` for `-b`
- in `git push`:
  - [ ] `-f` for `--force`
