### ISSUE TITLE
Converting i to I

### ISSUE THREAD

**Issue by Ma1hT3ach3r** [pcottle/learnGitBranching#476]
In the Interactive Rebase Intro level,  I was trying to write the command to get the interactive rebase working. And it continued to change **i to I** no matter what I did. Eventually I just used the solution and had no problem.

**Comment by pcottle** [comment]
can you clarify what you mean by changing? like typing `i` on the keyboard changed to capital I?

**Comment by Ma1hT3ach3r** [comment]
Precisely. The auto-correct is switching it to `i` to `I`

**Comment by Ma1hT3ach3r** [comment]
I figured it was at the level of the browser but I didn't know.
