### ISSUE TITLE
rampup3 (Relative Refs #2 (~))

### ISSUE THREAD

**Issue by developer-will** [pcottle/learnGitBranching#480]
Hi, I managed to figure it out since I found show solutions, but I feel like it could be improved a bit. I went through the tutorials up until this point a few times, trying to find the bit where it tells you to go down a specific commit without using the hash (since I thought we weren't meant to use hash)

**Comment by pcottle** [comment]
Ah yep, this is one of the weaker lessons. Sadly translations are pretty baked in so its hard to rewrite; I can remove the lesson entirely if negative feedback continues to come in

**Comment by 12944qwerty** [comment]
I thought that you were supposed to use hash. I also didn't know you could force master to a specific commit.

**Comment by pcottle** [comment]
(closing out old issues)
