### ISSUE TITLE
Yet another solution for mixed3 that should be accepted.

### ISSUE THREAD

**Issue by lukasz-zaroda** [pcottle/learnGitBranching#487]
```
git rebase newImage master
git commit --amend
git cherry-pick C3
```

**Comment by pcottle** [comment]
Yep agreed, whats tricky here is that we don't really have a "history" of each commit in the goal check code and rather just the current number of hashes / tree structure. I usually make the asserts fairly strict so we dont allow people to accidentally pass the level... but for this case, you're right that this uses cherry pick (which the level is talking about) in a way to solve the level

**Comment by pcottle** [comment]
I just made a change, this should be a valid solution now

**Comment by pcottle** [comment]
works:
https://learngitbranching.js.org/?NODEMO&command=level%20mixed3;%20git%20rebase%20newImage%20master;%20git%20commit%20--amend;%20git%20cherry-pick%20C3
