### ISSUE TITLE
Permalink is not selectable

### ISSUE THREAD

**Issue by eatdrinksleepcode** [pcottle/learnGitBranching#488]
A permalink to the current state was added as part of #451.

Using this permalink is difficult because if you use the mouse to select it, when you release the mouse button, the selection is removed (both Chrome and Firefox on Mac). It IS possible to copy it if you keep the mouse button down while you do the copy, but that took me a while to figure out.

Note that this seems to be specific to the permalink; all other console output seems to be selectable.

**Comment by pcottle** [comment]
Yeah true, I was using the same output as the rest of the command line outputs and thus it does not render as a link. Let me see if I can update this

**Comment by pcottle** [comment]
Done! its not super beautiful but it should work now -- actually clickable and it doesnt render the whole link anymore.

the rendering slightly breaks (it starts to show outside the box) but this is better UX
