### ISSUE TITLE
Level Cherry Pick Intro not recognizing correct commands

### ISSUE THREAD

**Issue by immortal-potato** [pcottle/learnGitBranching#496]
<img width="1434" alt="screen shot 2018-11-01 at 5 26 47 pm" src="https://user-images.githubusercontent.com/43657841/47887213-6a9cf080-ddfb-11e8-92e2-bea3d4b48594.png">

**Comment by pcottle** [comment]
Oh but this master branch isnt quite what it should be; it should go C0 -> C1 -> C3 -> C4 -> C7

however yours goes C0 -> C1 -> C3 -> C5 -> C7

C4 and C5 are the difference
