### ISSUE TITLE
Do you want use Yarn

### ISSUE THREAD

**Issue by Hongarc** [pcottle/learnGitBranching#513]
**yarn** same **npm** but it is good for me, I have some problem with `npm-shrinkwrap.json` (I can't install module) but It easy in `yarn`.

- You should update `npm-shrinkwrap.json` , because it will break some test ci in https://travis-ci.org
- Most of all module is out of date, I want pull request to update it but it fail in https://travis-ci.org (because `npm-shrinkwrap.json` is old version).

Good day, cheer.

**Comment by pcottle** [comment]
Yep it'd be great to move to yarn, especially so installs are more deterministic. ill keep this open to track
