### ISSUE TITLE
tutorial about `git stash` also helpful

### ISSUE THREAD

**Issue by Foristkirito** [pcottle/learnGitBranching#531]
great tutorial, any idea to add a tutorial about git stash and apply?

**Comment by pcottle** [comment]
Yeah git stash is awesome but it only applies to files and changes. Sadly I never built support for that, I focused on commits and branches rather than the file specifics (which GitHub has a nice tutorial for)

**Comment by vinceAmstoutz** [comment]
Sorry to reopen :/  this PR but it's not to create a new one of the same topic. With a little help is it possible to make a tutorial about `stash` and `stash pop` or still not @pcottle?
