### ISSUE TITLE
Website is broken?

### ISSUE THREAD

**Issue by mohannad-abwah** [pcottle/learnGitBranching#537]
https://learngitbranching.js.org/ stopped working about half an hour ago. I tried with ?NODEMO, and also in incognito. @pcottle is this a known issue?

I'm using chrome version 71.0.3578.98 (& Edge) on Win10 1809 build.

**Comment by mohannad-abwah** [comment]
Seems to be working now.

**Comment by pcottle** [comment]
yeah a hard refresh should fix this. sorry about the outage, there was a diff that modified the .gitignore and it removed some code that tracked our built bundles for the deployed branch of the site. should be all fixed now
