### ISSUE TITLE
remote-level Pull args lesson clarification

### ISSUE THREAD

**Issue by kostadinnm** [pcottle/learnGitBranching#540]
Hello, guys - nice visual tutorial!
On the last level "remote", in lesson "pull args", the `git pull origin master` command seems wrongly explained. To me, it seems that the currently "checked-out" branch brings context to where the implicit `merge` is destined to. I am new to git and, in case I'm right, would be glad to fix that by issuing a pull-request myself.
Here is a screenshot:
![2019-02-14 12_07_58-window](https://user-images.githubusercontent.com/18436405/52789014-6378b600-306b-11e9-8937-0f54f901c7dc.png)
Cheers,
Kostadin

**Comment by pcottle** [comment]
Good catch! I think this is just flat out wrong, its clearly merging to where we are (which is the same as whats checked out)

**Comment by pcottle** [comment]
I think I meant to say something like "merged `o/master` to our currently checked out location, even though its not the same as the local master branch"

**Comment by pcottle** [comment]
![screenshot 2019-02-20 at 2 14 11 pm](https://user-images.githubusercontent.com/1135007/53128498-ceb60280-3519-11e9-8317-4c6f16c872ec.png)
there we go!
