### ISSUE TITLE
syntax error (Ukrainian)

### ISSUE THREAD

**Issue by SSvin** [pcottle/learnGitBranching#554]
![image](https://user-images.githubusercontent.com/48239334/54747516-d4b20880-4bd7-11e9-9d45-3838f4f9de8c.png)
замінити кілку на гілку.

**Comment by pcottle** [comment]
Sorry cant read Ukrainian, what is the fix?

**Comment by SSvin** [comment]
Use google translate. In the photo in the third sentence, "кілку" should be replaced by "гілку".

**Comment by SSvin** [comment]
https://github.com/pcottle/learnGitBranching/blob/5626054b8a7d6ccdaf1e33372b4ba52b1216a675/src/levels/intro/merging.js#L852  here (тут). Вчіть українську мову, будьте освіченими.
