### ISSUE TITLE
Travis-ci auto deploy gh-pages

### ISSUE THREAD

**Issue by Hongarc** [pcottle/learnGitBranching#556]
I think we don't need manual upload `gh-pages`, you can use Travis-ci to deploy it when has changed in `master` branch.

Hongarc/node-facebook@8d1f2d3 is example to do it, but you need create enviroment variable to travis-ci can commit

**Comment by pcottle** [comment]
I kinda like manually updating it though; sometimes I merge in a few pull requests and know that it won't break production without me verifying locally that the build and everything still works. The Travis CI tests are pretty minimal and definitely don't cover everything.

Thanks for letting me know though! Good to know for sure

**Comment by Hongarc** [comment]
@pcottle  You can use Travis-ci to deploy it when has changed in `tags`:
 - Check in your local with `master` branch
 - If it is OK, just create tag

And what is your minify js tool, you can add it in grunt build tool.

**Comment by pcottle** [comment]
Yep a while back I learned that Travis-CI can deploy it, but I still prefer doing it manually :)
