### ISSUE TITLE
Add link+image  contributors

### ISSUE THREAD

**Issue by Hongarc** [pcottle/learnGitBranching#557]
I think you should add info of contributors in `README.md`(image + link instead of the only name).

My recommendation is:
- [contributor-faces](https://github.com/ngryman/contributor-faces): add 30 contributors with image and link.
- [all-contributors](https://github.com/all-contributors) is better but you need time to add contributors with type(example `question`, `code`, ...)

I create [example](https://github.com/Hongarc/learnGitBranching/tree/contributors) use `contributor-faces`

**Comment by pcottle** [comment]
for sure! great idea :)
