### ISSUE TITLE
After changing language, close button non-responsive

### ISSUE THREAD

**Issue by Splaktar** [pcottle/learnGitBranching#583]
The final button here with the door-> icon isn't responsive:
![Screen Shot 2019-06-02 at 14 52 53](https://user-images.githubusercontent.com/3506071/58765910-1ea75b00-8546-11e9-8ac6-9460df8fc762.png)

Clicking it causes this error (but nothing happens in the UI):
```js
Uncaught TypeError: this.setState is not a function
    at Object.showSelf [as onExit] (bundle.min.c898f8cf.js:1)
    at c.<anonymous> (bundle.min.c898f8cf.js:1)
    at Object.<anonymous> (bundle.min.c898f8cf.js:1)
    at d (bundle.min.c898f8cf.js:1)
    at bundle.min.c898f8cf.js:1
    at _ (bundle.min.c898f8cf.js:1)
    at E (bundle.min.c898f8cf.js:1)
    at D (bundle.min.c898f8cf.js:1)
    at q (bundle.min.c898f8cf.js:1)
    at Ao (bundle.min.c898f8cf.js:1)
```
Debug output
```json
{"branches":{"master":{"target":"C1","id":"master","remoteTrackingBranchID":null}},"commits":{"C0":{"parents":[],"id":"C0","rootCommit":true},"C1":{"parents":["C0"],"id":"C1"}},"tags":{},"HEAD":{"target":"master","id":"HEAD"}}
```

macOS Mojave, Chrome 74.

This is a great resource! Thank you for your work! We're planning to recommend it to new contributors to https://github.com/angular-hispano/angular-hispano since there is a Spanish translation.

**Comment by pcottle** [comment]
Thanks for the report! pretty simple function binding issue, was an easy fix :) should be deploying to the site now
