### ISSUE TITLE
A possible mistake in level instructions

### ISSUE THREAD

**Issue by eudoxyz** [pcottle/learnGitBranching#589]
![Screenshot from 2019-06-12 22-42-36](https://user-images.githubusercontent.com/10743071/59384969-b46f9100-8d63-11e9-8459-67b58a39130c.png)

Are you sure _Rebasing over 9000 times_ can be solved in less than four commands without `cherry-pick`?

**Comment by pcottle** [comment]
That sentence isn't meant to imply that it can *always* be done in fewer commands, but thinking about how to do it is a somewhat fun exercise :P
