### ISSUE TITLE
Cannot close level window 

### ISSUE THREAD

**Issue by justinezahiri** [pcottle/learnGitBranching#594]
Cannot close or reduce level map window when working on a level.

**Comment by Hongarc** [comment]
> Cannot close or reduce level map window when working on a level.

@justinezahiri Can you write step-by-step to reproduce your issue? Thank you!

**Comment by mexanga** [comment]
Write `levels` in https://learngitbranching.js.org/?NODEMO and a window will be showned. Once opened, we cannot close it.

To fixed that, we can add fonctionnal close button in the top of the window or a link which can perform that.

**Comment by pcottle** [comment]
(closing out old issues)
