### ISSUE TITLE
level rampup3

### ISSUE THREAD

**Issue by itnikita** [pcottle/learnGitBranching#595]

**Comment by itnikita** [comment]
the Solution is 
git branch -f master c6
$ git checkout HEAD~
$ git branch -f bugFix HEAD~1

but I think the right is 
git branch -f master c6
$ git checkout HEAD~
$ git branch -f bugFix HEAD~3

that is  one should be three .
So tell me I am wrong.

In fact My own answer is 
$ git branch -f master c6
$ git branch -f bugfix c0
$ git checkout HEAD~

**Comment by pcottle** [comment]
I think the key insight is `git checkout HEAD~`

this actually moves `HEAD` one commit behind, now pointing to C1:
<img width="307" alt="Screen Shot 2019-08-20 at 8 25 09 PM" src="https://user-images.githubusercontent.com/1135007/63400467-c33c7a80-c388-11e9-9732-421e7cb13b66.png">

so when we want bugFix to be on C0, thats just one more commit (`HEAD~`) behind. although we just moved the master branch, it doesn't mean we're actually checked out on the master branch (hence the detached HEAD state). 

does that make sense? Your usage of `HEAD~3` seems to imply that we are checked out on C4 or C5 but that's not the case
