### ISSUE TITLE
lesson on 'juggling commits level 2' is confusing 

### ISSUE THREAD

**Issue by 1dropaflame** [pcottle/learnGitBranching#638]
The lesson says to do 
```
git rebase HEAD~2
git commit --amend
git rebase HEAD~2
```
but it doesn't say what to do in the rebase.
Also solutions are not available so one cannot progress until one gets it correct or see what the correct solutions were.

**Comment by pcottle** [comment]
are you sure you mean juggling commits level 2? level 1 is the one with the interactive rebase. level 2 has a different solution:
<img width="1279" alt="Screen Shot 2020-02-18 at 5 00 41 PM" src="https://user-images.githubusercontent.com/1135007/74715670-43786580-5270-11ea-8922-0e6e155212d1.png">

**Comment by 1dropaflame** [comment]
sorry, but I don't remember now. I will check again sometime.

**Comment by Nubosch** [comment]
Imo, the solution to 3: Juggling Commits #2 would be git rebase -i with edit for amend. Please consider adding "full" possibilities for interactive rebasing. The chain rebase, amend, rebase feels wrong.

**Comment by pcottle** [comment]
(closing out old issues)
