### ISSUE TITLE
Upgrade module

### ISSUE THREAD

**Issue by Hongarc** [pcottle/learnGitBranching#654]
I attempt to upgrade the module of this module.

However, too many `grunt-plugin` is outdated(install without `yarn.lock` have error)

In my opinion, `gulp` is easy to understand, do you want to use it? (I made a config file for `gulp` from your `Gruntfile.js`, have an error with old version `jasmine`)

You create a config `jshint` in `Gruntfile.js`, how about create `.jshintrc` file(it can work with a plugin of your IDE)

I use eslint and other plugins(have many options to lint code)

What is your choice?
- [ ] Grunt
- [ ] Gulp
- [ ] Eslint
- [ ] Jshint
- [ ] Update jasmise
- [ ] Keep jasmise

I create this issue because I install and test fails with `npm i` ...

Thank you.

**Comment by pcottle** [comment]
I'd be totally willing to switch to Gulp -- thats more popular and more modern now right?

Don't know how much work it is to switch over. But yeah I think at this point we only support `yarn` and not `npm`. Ill update the readme

**Comment by pcottle** [comment]
(Oh we already reference yarn in the readme, yay)

**Comment by Hongarc** [comment]
Can you help me update `jasmine`?

I need a little time to understand that test and migrate to the new version.

I am going to create a pull request without using `jasmine`(until I migrate it to newversion)
