### ISSUE TITLE
Wrong input text history

### ISSUE THREAD

**Issue by hong4rc** [pcottle/learnGitBranching#679]
Reproduce:
 - Open website
 - Type any command, ex: `ls`
 - Press up arrow: terminal add a little space after ls

**Comment by pcottle** [comment]
<img width="462" alt="Screen Shot 2020-04-21 at 10 26 57 AM" src="https://user-images.githubusercontent.com/1135007/79894660-a4303580-83ba-11ea-86ba-ab10d6fca8d9.png">
I'm not seeing the repro -- what do you mean exactly?

**Comment by hong4rc** [comment]
Just typing ls 1 time and press up arrow, you will see `ls            `
instead of `ls`
