### ISSUE TITLE
Curves and nodes cross, easily cause ambiguity

### ISSUE THREAD

**Issue by fancyop** [pcottle/learnGitBranching#685]
![123123](https://user-images.githubusercontent.com/30931291/80087939-68e66000-858e-11ea-8e11-bea4c617bac6.png)

You can see the uploaded screenshot, actually merge C3 to C8, but the graphic looks through C6, it doesn't look good

**Comment by pcottle** [comment]
Ah yeah, this is unfortunate but part of the reason why we have the arrow is so we can show when a node is actually attached vs a passthrough.

going to close out as a wontfix since this is pretty tricky to avoid (or give a special UI treatment for)
