### ISSUE TITLE
Unable to get past "hide goal" phase at the very first tutorial

### ISSUE THREAD

**Issue by ilgazcan** [pcottle/learnGitBranching#688]
Hello,

I was unable to do anything after the "Goal To Reach" window pops up. When I click any of the window buttons of the goal window, nothing happened. Then I tried to write down `hide goal` on the console; no luck either. 

This error comes up on the browser console: `this.goalVis is undefined`

I tried this on an Ubuntu Linux, Firefox, Brave and Chrome's latest browsers. I saw the issue on every one of them

Thanks!

**Comment by elodg** [comment]
Same issue here. Goal dialog cannot be closed.

**Comment by shubham908** [comment]
I am also getting the same issue. It worked fine just an hour back but now it has this issue.

**Comment by neilteng** [comment]
just facing the same issue

**Comment by ChangMarkusYu** [comment]
Facing the same issue here. Goal dialog cannot be closed and the visuals inside the goal window aren't displaying either.

**Comment by abc12345131** [comment]
Same thing here. I'm a first time user, I thought it's my problem until I saw this issue.

**Comment by owleyes** [comment]
Same here. Reproduced on the following three browsers before I came here to check if others see the same issue.


- Brave Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit)
- Chrome Version 81.0.4044.122 (Official Build) (64-bit)
- Safari  Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by ValentiWorkLearning** [comment]
The same issue.

**Comment by iantolan11** [comment]
I think adding:
  <script defer src="lib/jquery-ui-1.9.0.custom.min.js"></script>
to line 361 of src\template.index.html might fix this

**Comment by shinyT** [comment]
the sme issue

**Comment by Liji-i** [comment]
Just facing the same issue. I have tried chrome and edge. Neither works.

**Comment by hong4rc** [comment]
> I think adding either:
> 
> <script defer src="lib/jquery-ui-1.9.0.custom.min.js"></script>
> to line 361 of src\template.index.html
> 
> or changing line 95 of gulpfile.js to:
> entries: [...glob.sync('src/**/*.js'), ...glob.sync('src/**/*.jsx'),'lib/jquery-ui-1.9.0.custom.min.js'],
> 
> should fix this

We use jquery 3.5, jquery-ui 1.9 cannot compatible with it, I create a PR to fix this issue.

Quick demo: https://hong4rc.github.io/test/index.html

**Comment by wjq990112** [comment]
> > I think adding either:
> > <script defer src="lib/jquery-ui-1.9.0.custom.min.js"></script>
> > to line 361 of src\template.index.html
> > or changing line 95 of gulpfile.js to:
> > entries: [...glob.sync('src/**/*.js'), ...glob.sync('src/**/*.jsx'),'lib/jquery-ui-1.9.0.custom.min.js'],
> > should fix this
> 
> We use jquery 3.5, jquery-ui 1.9 cannot compatible with it, I create a PR to fix this issue.
> 
> Quick demo: https://hong4rc.github.io/test/index.html

Not only can not "hide goal", but also the goal window can not move, it can move in the last version.

**Comment by hong4rc** [comment]
> Not only can not "hide goal", but also the goal window can not move, it can move in the last version.

Can you show me reproduce that error in with  hong4rc.github.io/test/index.html?

Thank you

**Comment by wjq990112** [comment]
> > Not only can not "hide goal", but also the goal window can not move, it can move in the last version.
> 
> Can you show me reproduce that error in with https://hong4rc.github.io/test/index.html?
> 
> Thank you

![image](https://user-images.githubusercontent.com/45777252/80172250-15702280-861f-11ea-9ac5-a8e01f99a1a4.png)

**Comment by hong4rc** [comment]
I need to reproduce the error.

Can you type step by step to get this error?

**Comment by wjq990112** [comment]
> I need to reproduce the error.
> 
> Can you type step by step to get this error?

When you drag the goal window, the goal window will be closed directly instead of moving.

**Comment by hong4rc** [comment]
> When you drag the goal window, the goal window will be closed directly instead of moving.


Thank you, fixed it. Please report any bug if you see it.

**Comment by BIYTC** [comment]
at least I know I'm not the only one

**Comment by bryangators** [comment]
This should be an important issue to fix. I was very interested in trying out this tool to enhance knowledge of git and was immediately stopped because of this issue. It will deter people from using this product. Please fix soon this seems like a great tool!

**Comment by olguergb36** [comment]
tengo el mismo problema por favor arreglarlo

**Comment by uoyevoli** [comment]
same problem here

**Comment by cristianCeamatu** [comment]
Same problem here:
![Untitled](https://user-images.githubusercontent.com/19146884/80276102-dc06e800-86ee-11ea-88f3-4ffff45618a5.png)
