### ISSUE TITLE
i want to close "hide goal", i can not see anything, bu i can not close it using cmd

### ISSUE THREAD

**Issue by disxo** [pcottle/learnGitBranching#691]
![image](https://user-images.githubusercontent.com/20137434/80175705-f080ad00-8628-11ea-9d71-731fb31fec8a.png)

**Comment by wasedawesley** [comment]
same problem, maybe the server is shut down

**Comment by disxo** [comment]
> same problem, maybe the server is shut down

yes, thank you , because i want to use it to make some practice.

**Comment by Inkognitoo** [comment]
Issue and fix are already exist
Now we are waiting for approve pull request
https://github.com/pcottle/learnGitBranching/issues/688

**Comment by zhahuya** [comment]
一个非常糟糕的错误！

**Comment by Blot1** [comment]
same problem,what's wrong?

**Comment by gregzanch** [comment]
still getting the same issue

**Comment by LebronAl** [comment]
I was going to learn this last night, but when I opened it, I found this problem. It really affects the user experience.

**Comment by Ssicayoon** [comment]
Same issue, hope it will be fixed soon

**Comment by zhangzzxiaohong** [comment]
It make me sad.Hope it will be fixed as soon as qucikly

**Comment by hong4rc** [comment]
> > same problem, maybe the server is shut down
> 
> yes, thank you , because i want to use it to make some practice.

You can try: hong4rc.github.io/test/index.html

**Comment by sriramdintakurti** [comment]
> > > same problem, maybe the server is shut down
> > 
> > 
> > yes, thank you , because i want to use it to make some practice.
> 
> You can try: https://hong4rc.github.io/test/index.html

Thanks the new link is working

**Comment by tilakapash** [comment]
Same problem. Breaks the whole funcionality of the app. Great app ... but useless unless this bug is corrected

**Comment by elodg** [comment]
Duplicate of #688

**Comment by zawawimanja** [comment]
same. hide goal not work.

**Comment by pcottle** [comment]
Apologies everyone! #690 should fix this. Pushing an update now

**Comment by pcottle** [comment]
Commit 9706b36d4edb5a0e9e424304023184d9360d36e4 just landed in prod, should be pushed out shortly and you can all try again then.

**Comment by pcottle** [comment]
<img width="1269" alt="Screen Shot 2020-04-25 at 11 55 39 AM" src="https://user-images.githubusercontent.com/1135007/80288254-b1676000-86eb-11ea-9f2b-aed7b700100e.png">
Alright seems restored in prod 😅

**Comment by hong4rc** [comment]
@disxo Can you close this issue?
