### ISSUE TITLE
Migrating from Deprecated Facebook Pixels

### ISSUE THREAD

**Issue by hong4rc** [pcottle/learnGitBranching#696]
Do you want to use Facebook Pixels?

Facebook deprecated the Conversion Tracking Pixel in February 2017, and it is no longer available for use ([Migrating Pixels](https://developers.facebook.com/docs/facebook-pixel/support/pixel-migration/))

You should remove the old code for Facebook pixel (if you don't want to use it)
 or migrate to the new version

**Comment by pcottle** [comment]
Great point! I used this for a bit to run free ads to get more distribution, but I haven't touched those campaigns in years. Overdue for removal :)
