### ISSUE TITLE
Can't Close Level 2: Branching in Git

### ISSUE THREAD

**Issue by kolykhmatovao** [pcottle/learnGitBranching#697]
Can't Close Level 2: Branching in Git

If I created a new branch with a typo in the name, and then the correct bugFix branch, the lesson does not read, I need to delete all the branches and create a new one to go through this lesson, for a beginner it is not clear.

Example: 

  git checkout –b bugFi
  git checkout –b bugFix

**Comment by hong4rc** [comment]
@kolykhmatovao Can you check with `https://hong4rc.github.io/test/`?

**Comment by kolykhmatovao** [comment]
This link does not have this problem.

**Comment by pcottle** [comment]
Fixed! pushing out now

**Comment by pcottle** [comment]
(for anyone curious, the name of the branch was actually irrelevant -- the existence of the branch was blocking the level comparison from returning true)
