### ISSUE TITLE
Insufficient goal checking in remoteAdvanced7 level

### ISSUE THREAD

**Issue by elodg** [pcottle/learnGitBranching#701]
Completed the goal in 1 instruction instead of two because I did not actually complete the goal - foo and o/foo are still there.
![image](https://user-images.githubusercontent.com/7438625/80467629-c1c74700-8946-11ea-826a-448833cf311e.png)

**Comment by pcottle** [comment]
This is likely a result of #699 🙈 I’ll add a new compare method that actually includes looking for leftover branches on the source tree

**Comment by pcottle** [comment]
@elodg  can you clarify which level this was?

**Comment by pcottle** [comment]
@elodg we have an ability to compare with leftover branch cleanup enforced now. I wasn't sure which level you are referring to (and poked around for a few).

cc @hong4rc  just as a side effect of the other PR

**Comment by elodg** [comment]
The level is in the issue title: remoteAdvanced7.

**Comment by pcottle** [comment]
<img width="1269" alt="Screen Shot 2020-04-29 at 5 59 12 PM" src="https://user-images.githubusercontent.com/1135007/80661302-25cf3580-8a43-11ea-90df-da46ae302529.png">
Thanks! have a fix ready :)
