### ISSUE TITLE
Missing Period

### ISSUE THREAD

**Issue by amayer5125** [pcottle/learnGitBranching#705]
There is a missing period at the end of the sentence "`git clone` will be that command" on the Our Command to create remotes modal. I haven't check if any other languages are missing periods in the same place.

Also command should probably be lower case in the modal title.

**Comment by amayer5125** [comment]
There is also a missing period in the last sentence of the Git Fetch modal after "This ties into the previous lesson on remote branches". I wasn't sure if I should open a separate issue for each one or post them all here. I figured a comment was less spammy.

**Comment by pcottle** [comment]
Wanna submit a PR like in #704? 😇

**Comment by nem75** [comment]
Hi, I opened https://github.com/pcottle/learnGitBranching/pull/707.

It adds the requested period characters. And a couple more. ;)

(For some reason the PR wasn't linked automatically?)

**Comment by amayer5125** [comment]
@nem75 GitHub [looks for keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in the body in the format:
```
Git Commit Title

Other git commit body stuff
closes #705
```
Just a heads up for future commits.

**Comment by nem75** [comment]
Thanks @amayer5125! Obviously I was too lazy to look it up. :) At my work we put the issue key as prefix into the title; will adapt when comitting to github.
