### ISSUE TITLE
Goal Reach window

### ISSUE THREAD

**Issue by abdu95** [pcottle/learnGitBranching#712]
To select a level, from the **Main** section, I have chosen a level **Moving Work Around**. In **2: Interactive Rebase Intro**, I have read all the description and wanted to start an exercise. In the **Goal Reach** window (**Show Goal** button) the final result is shown with a graph (containing colorful circles and arrows). But the text that is behind this graph that says **Note; Only the master branch will be checked in this level ...** is not shown properly. Firstly because the text is behind the graph and secondly because the text font is small, this text is not visible. 
This "Note: ..." text is shown at the top of the **Goal Reach** window. The graph is also aligned to the top of the window. Isn't it possible to move this "Note:..." text to the below of the window? There is plenty of space below

**Comment by pcottle** [comment]
I kinda like how most of the text is on the upper side of the screen like so:
<img width="964" alt="Screen Shot 2020-06-15 at 8 20 59 AM" src="https://user-images.githubusercontent.com/1135007/84668703-292e5b80-aee1-11ea-86a9-9b58d17b6d23.png">


vs your suggestion involves darting up and down to read the text in different places:

<img width="1046" alt="Screen Shot 2020-06-15 at 8 22 57 AM" src="https://user-images.githubusercontent.com/1135007/84668935-74e10500-aee1-11ea-90cd-b91bbd84ca15.png">


this is good feedback but I'll probably leave it where it is for now :)

**Comment by abdu95** [comment]
Wow! 😃 Yes, I totally agree with you. Leave it where it is because if I ever could use this website as in the screenshot 😢 I really liked the UI that is  shown in the screenshot. If the website appeared for me in the same way as in the screenshots you sent, I would not even open this Issue. 
For me, it's appearing like this:
I don't know the reason for this, is that because of a browser or because I'm using Windows? 🤔   I'm using chrome, I tried to open the website in Firefox and Edge, but its still the same. What browser are you using?
![image](https://user-images.githubusercontent.com/27206573/84703426-a6a1ac80-af71-11ea-9ff8-dfe73dca6c82.png)

**Comment by pcottle** [comment]
Oh it might totally be a Windows browser support thing. I pretty much only test in Chrome on Mac.

Yeah seems like there are various layout issues in that particular browser! Could you try messing with the CSS locally and see if anything fixes it? there should be a DIV separating it

<img width="533" alt="Screen Shot 2020-06-15 at 4 01 44 PM" src="https://user-images.githubusercontent.com/1135007/84710479-8813c500-af21-11ea-95ff-b047a72fcde8.png">
