### ISSUE TITLE
merge command doesn't support multiple branch arguments

### ISSUE THREAD

**Issue by graemeg** [pcottle/learnGitBranching#713]
The tool is fantastic to teach someone Git, but it seems to be missing one feature I use often. It's perfectly valid to specify 2 or more branches in a `git merge` command. Also known as an Octopus Merge. 

<img width="1559" alt="Screenshot 2020-06-15 at 13 35 30" src="https://user-images.githubusercontent.com/72053/84658108-4711b580-af0d-11ea-8ed9-e067da23334b.png">

**Comment by pcottle** [comment]
Yep this is a known downside of the app. Implementing octopus merges seemed quite complex, and it was hard to justify given how rare they are in industry.

but great feedback!

**Comment by pcottle** [comment]
> Either way the Octopus merge is a really fun way of Merging. You probably won't get to do this at your work as a lot of companies think this complicates things and we all know how much Companies hate complexity.

http://www.freblogg.com/2016/12/git-octopus-merge.html

Linus weighing in on octopus merges:
https://marc.info/?l=linux-kernel&m=139033182525831

> It's pulled, and it's fine, but there's clearly a balance between
"octopus merges are fine" and "Christ, that's not an octopus, that's a
Cthulhu merge".

(a few reasons why I don't use them personally and didn't bother teaching them)
