### ISSUE TITLE
Is it possible to use this same visualization for my actual git repo?

### ISSUE THREAD

**Issue by techsin** [pcottle/learnGitBranching#714]
It'd help me a lot if I could visualize my actual repo in same way as learngitbranching.js.com

**Comment by pcottle** [comment]
Hey @techsin ! There are a bunch of tools that do this a lot better than LGB, my favorite being:
https://github.com/FredrikNoren/ungit

but there are many others:
https://git-scm.com/downloads/guis

We'll probably stick to the educational space for now :)

**Comment by techsin** [comment]
I like the animations

**Comment by techsin** [comment]
But thanks for the tool I reeeealy appreciate it. I hope to see more practice rounds and also more scenarios and concepts.
