### ISSUE TITLE
Tiny question about "When the interactive rebase dialog opens, you have the ability to do 3 things"

### ISSUE THREAD

**Issue by anisilv** [pcottle/learnGitBranching#718]
My question is about the section teaching interactive rebase. It says "When the interactive rebase dialog opens, you have the ability to do 3 things" But actually there are many more options, **would be helpful to say something about them?** Like among other options, or three main things... just a hint that you are going to find more there... or maybe you have a reason to leave the other options outside...

**Comment by pcottle** [comment]
<img width="1001" alt="Screen Shot 2020-07-05 at 2 20 51 PM" src="https://user-images.githubusercontent.com/1135007/86542451-bfdfae00-beca-11ea-849f-f9a5b9d1ae3c.png">
Good point! I always felt like some of the options were a bit more obscure (like exec??) but I'll mention this
