### ISSUE TITLE
Do you have the answer to the problem？

### ISSUE THREAD

**Issue by 1198560751** [pcottle/learnGitBranching#724]
Do you have the answer to the problem？

**Comment by pcottle** [comment]
@1198560751  can you be more specific?

**Comment by 1198560751** [comment]
> @ 1198560751 您能更具体一点吗？

Is there an answer to git learning website？
这个git的闯关有答案吗

**Comment by Pyrokine** [comment]
show solution

**Comment by CoderWeiLee** [comment]
how to find the answer
