### ISSUE TITLE
Remote activity 8 warning message overlaps element container

### ISSUE THREAD

**Issue by maestrom4** [pcottle/learnGitBranching#735]
{"branches":{"master":{"target":"C1","id":"master","remoteTrackingBranchID":null}},"commits":{"C0":{"parents":[],"id":"C0","rootCommit":true},"C1":{"parents":["C0"],"id":"C1"}},"tags":{},"HEAD":{"target":"master","id":"HEAD"}}

![image](https://user-images.githubusercontent.com/5810422/93544320-58e17980-f990-11ea-9567-300bcd6dae5f.png)

**Comment by maestrom4** [comment]
replaced the pre tag with p tag

**Comment by pcottle** [comment]
Yeah that would be great! Would love to review it

**Comment by maestrom4** [comment]
thank u for the response @pcottle. I really thank u and to all contributors for building https://learngitbranching.js.org/ it really help me a lot honestly. I would highly recommend this site for git training.

**Comment by pcottle** [comment]
(closing out old issues)
