### ISSUE TITLE
Level about checkout of a remote branch

### ISSUE THREAD

**Issue by SteeveDroz** [pcottle/learnGitBranching#737]
Hello,

As a teacher, I see a lot of students who struggle with tasks that may seem trivial to experts.

A good example is that, sometimes, they type `git checkout origin/master` and wonder what is that "detached head" gibberish.

In order to fix that precise *<span title="Problem In Chair, Not In Computer">PICNIC</span>* error, I created a level: [see the gist](https://gist.github.com/SteeveDroz/a8b8464293d8db89702100b5aa38c18c).

As the export form told me to send it to you on GitHub, here it is!

Feel free to include it in a new serie of levels (see #430) if you decide to go that way!

**Comment by pcottle** [comment]
easier level link without the license for those who want to try:
https://learngitbranching.js.org/?gist_level_id=d9e6f4a49c905d9977245366ce03d50a

**Comment by pcottle** [comment]
Great level! It's a bit simple but a nice exercise for new students and indeed a common scenario.

I could be fine with adding this after we introduce `git branch -f`, or in that new series you mentioned. thanks for using the level editor and submitting the issue :)
