### ISSUE TITLE
feat: change "Fork me on GitHub" ribbon to a GitHub Corner

### ISSUE THREAD

**Issue by hamirmahal** [pcottle/learnGitBranching#746]
[tholman](https://github.com/tholman) created a fantastic repository called [`github-corners`](https://github.com/tholman/github-corners).

It's a "fresher 'Fork me on GitHub' callout" and you can see examples of it on tholman's [GitHub Corners page](https://tholman.com/github-corners/).

I think it would be awesome if this repository used a GitHub Corner instead of the "Fork me on GitHub" ribbon.

Current appearance of https://learngitbranching.js.org/?demo:

![Current appearance of https://learngitbranching.js.org/?demo as of 2020-10-18 at 4 41 16 PM](https://user-images.githubusercontent.com/43425812/96388874-c126a500-1160-11eb-8369-f4456d8660ac.png)

What https://learngitbranching.js.org/?demo might look like after changing its current "Fork me on GitHub" ribbon to a GitHub corner:

![https://learngitbranching.js.org/?demo with a GitHub Corner instead of a "Fork me on GitHub" ribbon](https://user-images.githubusercontent.com/43425812/96388912-0e0a7b80-1161-11eb-9af7-62a91f5bdab4.png)

Also, thank you! I went through this entire tutorial in just a couple of sittings. It was really enjoyable and you made it free, which I really appreciate. #498 says it all.

**Comment by pcottle** [comment]
Totally agreed! Thanks for sending the PR. I don't think the banner looks super out of date but I like it's more subdued visual appearance (and it allows more space for the graphs)

**Comment by pcottle** [comment]
<img width="1274" alt="Screen Shot 2020-10-19 at 11 56 49 AM" src="https://user-images.githubusercontent.com/1135007/96493419-35fdeb80-1202-11eb-9826-abaeec6a4aa0.png">
<img width="1269" alt="Screen Shot 2020-10-19 at 11 57 00 AM" src="https://user-images.githubusercontent.com/1135007/96493421-38f8dc00-1202-11eb-9bfc-d6f204ee503e.png">

it was a little large by default so downsizing slightly if thats ok!

**Comment by hamirmahal** [comment]
Looks awesome! Thanks for including it.
