### ISSUE TITLE
Allow the presentation of the git switch command

### ISSUE THREAD

**Issue by danielleberre** [pcottle/learnGitBranching#750]
I just noticed that there is now another way to switch from one branch to the other: `git switch <existingbranch>` and `git switch -c <newbranch>`

https://bluecast.tech/blog/git-switch-branch/

It might be a good idea to support git switch command and to allow either git switch or git checkout commands in the exercices.

In exercice 2, I noticed that `git switch -c bugFix` is fully supported while the instructions are mentioning only git checkout.

I wonder if only the explanations need to be updated/completed, or if there are other issues preventing the use of git switch in the exercises?

**Comment by pcottle** [comment]
Yep, I added `git switch` to kinda stay with the times given that it was released recently but haven't added any lessons that specifically introduce or promote it.

Having the ability to use it on sandbox is helpful, but I feel like the learning materials should either:

- solely promote `git switch` over `git checkout/branch`, but only once git switch is available in 90% of situations where you'd be working with git.
- stick to `git checkout/branch` for some kind of usability or understanding reason

My vote is for #1 but it's hard to track git upgrade adoption externally. I wouldn't want someone to go through all the learning materials just to get stuck on their first job when they're forced to use an older version of git

(although checkout/branch are less usable, they're safer to teach given their availability)

**Comment by danielleberre** [comment]
I see. It is indeed troublesome to have now two different commands to perform the same operation when learning git.

Is it the case that using git switch in the exercices is accepted just like git checkout?

If it is the case, then it is quit nice.

Maybe just a note on exercice 2 to mention that git switch exists in recent versions of git and supported in the exercices would be sufficient.

**Comment by pcottle** [comment]
That sounds like a good compromise! I'll keep this issue open until I add that.

The levels rarely care about *how* you obtain the final solution, just that you get the git tree into the final desired state (either by inspecting the whole tree or just a subset of it). So you can use whatever command you prefer

**Comment by olsza** [comment]
> I just noticed that there is now another way to switch from one branch to the other: `git switch <existingbranch>` and `git switch -c <newbranch>`
> 
> https://bluecast.tech/blog/git-switch-branch/
> 
> It might be a good idea to support git switch command and to allow either git switch or git checkout commands in the exercices.
> 
> In exercice 2, I noticed that `git switch -c bugFix` is fully supported while the instructions are mentioning only git checkout.
> 
> I wonder if only the explanations need to be updated/completed, or if there are other issues preventing the use of git switch in the exercises?

thanks, @danielleberre for this information, since I read this information here, I started using this command to switch between branches

**Comment by pcottle** [comment]
<img width="1015" alt="Screen Shot 2020-11-05 at 8 57 44 AM" src="https://user-images.githubusercontent.com/1135007/98264414-1a564d00-1f45-11eb-8cb8-1ef70b861d4e.png">
Ironically I'm on git 2.13 so I don't even have access to the command locally, but I think this will serve a fine introduction!
