### ISSUE TITLE
"Training mode" with no instructions and only exercises

### ISSUE THREAD

**Issue by AndreaCallia** [pcottle/learnGitBranching#764]
Hi all and many thanks to the authors of this projects...

Would it be possible to make a "training mode" for periodic training (to prevent forgetting commands) by disabling instructions and explanations and only keeping the exercises/challenges?

**Comment by pcottle** [comment]
Hey! that's an interesting idea but some of the levels are pretty trivial to solve with commands that are only exposed in later levels. Usually when this is the case I disable some of the other commands to force you to use what the lesson is specifically teaching -- which means if we presented the level without the material, not all of them might make total sense.

are the level dialogs just slow/hard to skip through? maybe adjusting the animation time is the better call?

**Comment by pcottle** [comment]
Closing this out until further feedback. But perhaps a command line option to skip all the instructions on each level? that seems easy

**Comment by AndreaCallia** [comment]
Many thanks @pcottle , the reason why I asked for that feature is that often users like me may learn everything perfectly, but they will forget many things with no training. But if we want to make training "painless" (less time-consuming), then it would be nice to have a separate "mode" where we avoid avoid all the explanations and animations (we are supposed to have learned everything already) and just try the exercises to prevent forgetting.

As you say, if no explanation is provided then we may forget what the purpose of the exercise was, but to fix this there could be just a summary with no animation on the top of the web page, something like: "using X commands to achieve Y". What do you think?

And yes,  the command line option to skip all the instructions on each level would be a great idea!

**Comment by pcottle** [comment]
I'm ok with something like the command line option; might not heavily advertise this mode but it would enable the behavior you describe.

I'll keep this issue open then for someone to go work on this -- should be relatively easy to flip a global Boolean and then just skip all level intros when kicking off a level.

**Comment by AndreaCallia** [comment]
Many thanks for this, I can try to help as well...

**Comment by pcottle** [comment]
Alright its going up now! Think this gets us what we want -- it'll persist between levels, unlike the `--noIntroDialog` option

try it out!

<img width="1050" alt="Screen Shot 2021-01-11 at 12 47 30 PM" src="https://user-images.githubusercontent.com/1135007/104230972-7f2d9800-540b-11eb-8ffb-ca0c25f5942b.png">

**Comment by AndreaCallia** [comment]
Wow that was fast, many thanks!
Going to try this...

**Comment by AndreaCallia** [comment]
Just tried (sorry for the delay), it works wonderfully, many thanks for your help...
