### ISSUE TITLE
Can't continue this lesson

### ISSUE THREAD

**Issue by hamxn** [pcottle/learnGitBranching#766]
<img width="905" alt="Screen Shot 2020-12-29 at 15 44 51" src="https://user-images.githubusercontent.com/36950028/103271500-ff580480-49ec-11eb-8fe9-0695647505a0.png">

**Comment by hamxn** [comment]
This lesson also
<img width="902" alt="Screen Shot 2020-12-29 at 16 13 29" src="https://user-images.githubusercontent.com/36950028/103273021-dc2f5400-49f0-11eb-9aec-99f6e4c8f28c.png">

**Comment by pcottle** [comment]
This is likely due to the change for biased terminology (moved from `master` to `main`). let me check...

**Comment by pcottle** [comment]
Ah an error in `setLocalToTrackRemote`....

**Comment by pcottle** [comment]
Thanks for the report @hamxn! Should be all fixed up now 🎉 

I just pushed the gh-pages site but I would recommend a hard refresh

**Comment by pcottle** [comment]
(There might be other bugs in remote tracking but this one specifically should be fixed)

**Comment by hamxn** [comment]
The first one already fixed. Thanks you.
The second one seem to fix. Please check!

**Comment by pcottle** [comment]
ah its probably a similar issue in the push side of argument parsing. justaec.

also attaching the level names helps a bunch, makes it easier to load it up :)

**Comment by pcottle** [comment]
Btw all of these bugs are related to #751 which I think is a pretty important chunk of work; ideally I caught this with no errors but it's worth fleshing out the few issues to accomplish that task
