### ISSUE TITLE
To Origin And Beyond -- Advanced Git Remotes! Lesson 5 Naming Error

### ISSUE THREAD

**Issue by pg805** [pcottle/learnGitBranching#769]
The branch in the visualization tool is called main, however the solution branch is called master.

**Comment by pcottle** [comment]
Ah good point; I did a big rename sweep inside the translations but not for the solution json. I'll try to do this later in a way that won't disturb the existing solution commands

**Comment by pcottle** [comment]
<img width="522" alt="Screen Shot 2021-01-01 at 1 28 02 PM" src="https://user-images.githubusercontent.com/1135007/103446044-69b0b500-4c38-11eb-9673-3eb96f69587b.png">
theres also some kind of error with duplicate origin tracking branches that is probably related :)
