### ISSUE TITLE
Closing old issues

### ISSUE THREAD

**Issue by YourSenseiCreeper** [pcottle/learnGitBranching#771]
To me current issues are unpleasant because:
- old not closed issues messes the true issues of the project
- many opened issues informs that user input is not really welcome (at first glance)
- issues are not properly tagged - this would inform contributors what they can improve

Regards

**Comment by pcottle** [comment]
True, that's a good point. I'll cruise through and close some of these!

(and as a meta thing, will close this one once kicking off the audit)

**Comment by pcottle** [comment]
Now just 2 issues are open!
