### ISSUE TITLE
Displaying master instead of main

### ISSUE THREAD

**Issue by j3luehawk097** [pcottle/learnGitBranching#778]
Going to https://learngitbranching.js.org/?NODEMO, once running git clone - the console replies => local branch "master" set to track remote branch "o/master"

![image](https://user-images.githubusercontent.com/39236459/104149860-85f2e580-53e0-11eb-8b3b-0b73e6b78d8b.png)

**Comment by pcottle** [comment]
Ah yeah the console doesn't have the same name replacement logic as the display side. This should be relatively easy to fix

**Comment by pcottle** [comment]
Ok I handled this case, but I presume there are others. I looked in the rest of the file and didn't see any others though
