### ISSUE TITLE
Small translation issue (french)

### ISSUE THREAD

**Issue by danielleberre** [pcottle/learnGitBranching#785]
I noticed today that the description of move2 in french in the level panel is

_Introduction à rebase_

while it should read

_Introduction au rebase interactif_

There are currently two levels with the same description (intro4 and move2). The first one is correct. Not the second one.

I have no idea where to fix this else I would have proposed a PR.

**Comment by waldyrious** [comment]
Hey @danielleberre — usually when I don't know a codebase but want to make a wording correction as is the case here, I simply search the repository for the exact string, and if I find a file that seems to be the right one, I edit it directly on the github web interface. It's pretty convenient! :)

In this case, a [search for "Introduction à rebase"](https://github.com/pcottle/learnGitBranching/search?q=%22Introduction+%C3%A0+rebase%22) shows that the phrase is present in:

https://github.com/pcottle/learnGitBranching/blob/b3c46032c32c0481fd1f20c04bad7d9be4f4acca/src/levels/intro/rebasing.js#L13

and

https://github.com/pcottle/learnGitBranching/blob/ea22bf80537fd2a06512c118176e292cf7b5b262/src/levels/rampup/interactiveRebase.js#L35

So according to your message above, the second file is the one that needs to be edited to use the proposed wording.

**Comment by danielleberre** [comment]
Thanks @waldyrious. PR #786 is available to fix this.

**Comment by danielleberre** [comment]
Fix merged. Thanks @pcottle
