### ISSUE TITLE
Goal state issue in remoteAdvanced2

### ISSUE THREAD

**Issue by deepamgupta** [pcottle/learnGitBranching#789]
While I was doing this level (`remoteAdvanced2`), the goal state and the problem procedure seems different, this made me confused.  
_So, I just followed what was suggested as the procedure._

**This is the accepted solution and this is what I think the goal state ought to be.**
![Screenshot from 2021-02-04 12-58-35](https://user-images.githubusercontent.com/36341114/106860239-1a075280-66ea-11eb-866a-1e31ef967cb6.png) 

**This is the current goal state:**
![Screenshot from 2021-02-04 12-57-07](https://user-images.githubusercontent.com/36341114/106860379-5044d200-66ea-11eb-9be5-069d32b35001.png)

Please correct me if I am mistaken.  
**Namaste**🙏

**Comment by pcottle** [comment]
Only `main` is checked as a branch, and main in both cases has all of the necessary commits (C11 downwards). the visual layout might differ but that's the true check of it being completed or not.

there's a small line about this at the top of the goal window :)

**Comment by deepamgupta** [comment]
gotcha, Thanks for clearing. Namaste🙏
