### ISSUE TITLE
French translation still mentions 'master' branch instead of 'main'

### ISSUE THREAD

**Issue by YassinHajaj** [pcottle/learnGitBranching#791]
Hi,

In file `strings.js` looking for `^\s+fdr_FR.*master` returns two results

> 'fr_FR': 'Vous ne pouvez supprimer la branche **master**, la branche sur laquelle vous êtes, ou ce qui n\'est pas une branche',
> 'fr_FR': '<span class="fwber">Note:</span> Dans ce niveau on ne doit faire de git checkout que sur la branche **master**. Les autres branches représentées ici (entourées d\'un cadre en tirets) doivent être utilisées uniquement comme références. Comme toujours, vous pouvez cacher cette fenêtre avec "Cacher les objectifs"',

They should be replaced by

> 'fr_FR': 'Vous ne pouvez supprimer la branche **main**, la branche sur laquelle vous êtes, ou ce qui n\'est pas une branche',
> 'fr_FR': '<span class="fwber">Note:</span> Dans ce niveau on ne doit faire de git checkout que sur la branche **main**. Les autres branches représentées ici (entourées d\'un cadre en tirets) doivent être utilisées uniquement comme références. Comme toujours, vous pouvez cacher cette fenêtre avec "Cacher les objectifs"',

**Comment by waldyrious** [comment]
@YassinHajaj nice catch — have you considered submitting a PR making that change? You can even [edit the file directly in the browser](https://github.com/pcottle/learnGitBranching/edit/master/src/js/intl/strings.js) :)

**Comment by YassinHajaj** [comment]
Hello @waldyrious 
In fact, I tried to create an upstream branch for my changes but got a nice 403 back :D

**Comment by pcottle** [comment]
Oh it's not intentional, we should switch over those references to master as well. I'm not sure how they got missed in our original pass. @YassinHajaj want to submit a PR?

**Comment by YassinHajaj** [comment]
Hi @pcottle ,
I just created it: https://github.com/pcottle/learnGitBranching/pull/793
I did not rerun the app to test because it seems like these kind of changes are quite straightforward, however let me know if this is a mandatory prerequisite.

I also left some comments for you to review, which might bring us to the creation of one or multiple new issue(s)

**Comment by YassinHajaj** [comment]
By the way, I put it in WIP ATM to be able to make some extra changes, cleaning up the log

**Comment by pcottle** [comment]
> I did not rerun the app to test because it seems like these kind of changes are quite straightforward, however let me know if this is a mandatory prerequisite.

That's totally fine, I run the whole test suite while deploying anyways for extra security

**Comment by YassinHajaj** [comment]
Super, thanks @pcottle I guess the issue is resolved 😀

**Comment by pcottle** [comment]
Yep I just deployed!
