### ISSUE TITLE
Broken layout in the goal popup

### ISSUE THREAD

**Issue by youhymuk** [pcottle/learnGitBranching#792]
Hi! 
Positioning for the SVG image in the goal popup doesn't work correctly, you need to add `position: relative` for `div class="inside box"`

![Learn Git Branching 2021-02-07 10-04-26](https://user-images.githubusercontent.com/47541469/107140691-807bb300-692c-11eb-93df-5957e307be0e.png)

**Comment by pcottle** [comment]
I believe this should only be an issue on firefox or non-chrome browsers, but some polish could be added here for sure. Thanks for opening the issue! Would you want to submit a PR to fix it?

**Comment by youhymuk** [comment]
You're right, that's only on firefox. Ok, I'll be glad to help! 😃
