### ISSUE TITLE
Text falls outside the block

### ISSUE THREAD

**Issue by youhymuk** [pcottle/learnGitBranching#796]
Hi!  👋🏻 
As you can see text inside `code`  falls outside the block. It has to do with the default value `white-space: pre` for `pre` tag.
I'll submit a PR to fix it.

<img width="1107" alt="Learn Git Branching 2021-02-10 21-14-28" src="https://user-images.githubusercontent.com/47541469/107560128-a54e7f80-6be5-11eb-882c-9f3a7b03d0f3.png">

**Comment by pcottle** [comment]
Oh awesome, thanks for offering up a PR! yeah maybe on my monitor at the time it fit within the bounds, but `pre` items don't wrap by default. Good catch
