### ISSUE TITLE
Italian translation missing

### ISSUE THREAD

**Issue by ShardanaSoft** [pcottle/learnGitBranching#811]
Hi I saw that Italian translation is missing, and to thank you for your amazing job I want to help you out in this. I've almost done the local one. One last check, and I'll make a pull request. 
P.S. : I might need a little help cause I'm new in this

**Comment by pcottle** [comment]
That'd be great! And yeah I can provide any assistance but its usually pretty straight forward to add a new translation, besides maybe a few minor things like updating the locale/language mapping

**Comment by pcottle** [comment]
will close this out for now but excited for the PR :)

**Comment by pcottle** [comment]
oh unless you wanted it open to close it with your PR

**Comment by ShardanaSoft** [comment]
yeah I've followed a course about linking issue with a pr, that's will be great for me for learning. I'll update later

**Comment by pcottle** [comment]
Oh ok great. yeah you can include "Closes #811" in the commit message and itll close it out when it gets merge and link the two -- kinda a neat feature
