### ISSUE TITLE
Goal Dialog Dragging

### ISSUE THREAD

**Issue by UgmaDevelopment** [pcottle/learnGitBranching#817]
Hello!

Thanks for the wonderful tutorial!

I noticed that the Goal Dialog doesn't like to move. When I click the title bar and drag it, the dialog does nothing. However if I go to drag it again, it teleports and closes. 

 
![dVNhSOLJ8W](https://user-images.githubusercontent.com/19827042/112068826-52df7780-8b30-11eb-81fe-80dffe27952a.gif)

I'm on Windows 10 and I've tried this on Edge and Chrome.

Let me know if there's any other info I can give you—or a way I can help. Thanks!

**Comment by pcottle** [comment]
oh yeah wow this has definitely regressed for me too. the drag and drop plugin might not be playing well with an upgrade in jQuery or something

its not showing any JS errors so it might just be broken for now. I remember I used a plugin almost entirely for this, so I don't think the fix will be easy.

will leave this open in the meantime

**Comment by pcottle** [comment]
Thanks @hong4rc  for the fix in #822!
