### ISSUE TITLE
Use of Master in git status

### ISSUE THREAD

**Issue by Chromeshades** [pcottle/learnGitBranching#818]
Master is still present when running git status when the "main" branch is checked out somewhere in Exercise 2, in Section 1 ("Introduction Sequence")

![image](https://user-images.githubusercontent.com/44106693/112145875-e6548f00-8ba8-11eb-8d12-68bfef047c75.png)

**Comment by pcottle** [comment]
<img width="1118" alt="Screen Shot 2021-03-23 at 8 09 50 AM" src="https://user-images.githubusercontent.com/1135007/112159801-274fa200-8baf-11eb-9eee-172f61501a59.png">
fixing!
