### ISSUE TITLE
Level "Branch Spaghetti"

### ISSUE THREAD

**Issue by Infinituum17** [pcottle/learnGitBranching#820]
The _instructions_ say: 
> Branch `one` needs a re-ordering and a **deletion of `C5`**

But when you look at the _goal graph_:

![image](https://user-images.githubusercontent.com/40234342/113104392-c81e0d00-9200-11eb-9d83-8ea98de59d27.png)

`C5` is still defined under the _main branch_

Is this right?

**Comment by pcottle** [comment]
Ah its referring to the ideal state of branch `one`, not branch `main`. I'll clarify this

**Comment by pcottle** [comment]
<img width="1036" alt="Screen Shot 2021-04-01 at 8 27 19 AM" src="https://user-images.githubusercontent.com/1135007/113309160-17794180-92c4-11eb-8481-ac4b9452b54d.png">
