### ISSUE TITLE
Feature Request: squash commits on interactive rebase

### ISSUE THREAD

**Issue by nbartels** [pcottle/learnGitBranching#825]
While using the interactive rebase, I realized that I can only pick, omit or re-order the commits. In my workflow I usually squash commits in the rebase step, so it would be great to have this possibility.

So I could show some stuff to my coworkers using this great tool.

**Comment by pcottle** [comment]
Ah yeah, a demonstration of squashing would be nice! However it would only be valuable if you could also show the concept of per-file changes (so you could see which changes you're adding or removing in the squash view).

So it's a pretty big leap to go introduce all of that functionality and then squash on top of it. I'll probably defer to other tutorials to educate folks on squash in the meantime :P
