### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by hong4rc** [pcottle/learnGitBranching#826]
Can we enable the discussions tab? (Community members can ask and answer questions)

 - **Settings**

![image](https://user-images.githubusercontent.com/19208123/115380125-7283c180-a1fc-11eb-90af-369d65053333.png)

 - **Just enable**

![image](https://user-images.githubusercontent.com/19208123/115380142-7879a280-a1fc-11eb-8caa-7de8d5f8330e.png)

**Comment by pcottle** [comment]
Great point! I forgot about enabling this when it came out. Done:
https://github.com/pcottle/learnGitBranching/discussions/827
