### ISSUE TITLE
use [levels] command to choose level make the [no translation] alert show multiple times

### ISSUE THREAD

**Issue by GalliumWang** [pcottle/learnGitBranching#831]

**Comment by pcottle** [comment]
can you attach a screenshot of the issue?

**Comment by GalliumWang** [comment]
> can you attach a screenshot of the issue?

Sorry,I failed to reproduct the issue,maybe it's caused by some other operation when I practised.While using the site I found every time I use [levels] command to jump to some level,the [no translation] alert just pop up one more times😶,and reload didn't solve it.So I create the issue.But it seems Ok now🤣,I will close this issue.By the way,thanks for you reply and this great repo.
