### ISSUE TITLE
Add a GUI undo,redo and reset buttons

### ISSUE THREAD

**Issue by Kaphleamrit** [pcottle/learnGitBranching#841]

**Comment by Kaphleamrit** [comment]
addition of GUI undo, redo and reset buttons would be helpful for people who might not be very fond of CLI

**Comment by pcottle** [comment]
Definitely agree that it would be nice for the folks who prefer a GUI. However given that git is so focused on being a CLI, I've tried to minimize the number of UI interactions (besides the visualization) so people get familiar with the command line. I'll keep this in mind though!
