### ISSUE TITLE
Intro Level3

### ISSUE THREAD

**Issue by TmoodGitHub** [pcottle/learnGitBranching#844]
Hi, it keep asking me to do 5 commands but I'm not sure how I can get 5 commands to match the goals without committing main.

Did I overlook something?

**Comment by pcottle** [comment]
try the `show solution` command, it will demonstrate the solution that has 5 commands :)

**Comment by TmoodGitHub** [comment]
git commit -b bugFix?

There were no mention of -b - how could I have figure that out? Even show commands doesn't show that shorthand trick..

**Comment by pcottle** [comment]
<img width="934" alt="Screen Shot 2021-05-31 at 11 04 07 AM" src="https://user-images.githubusercontent.com/1135007/120224075-f075b800-c1ff-11eb-8584-89d7dfba8037.png">
from level intro2

**Comment by TmoodGitHub** [comment]
**facepalm**

I totally missed that...

Thank you!!
