### ISSUE TITLE
Git/Hg option flags shown when entering the "show commands" command

### ISSUE THREAD

**Issue by ryancraigdavis** [pcottle/learnGitBranching#845]
When the user types in "show commands", a list of all of the git and mercurial commands available are shown. I think it would be helpful to also show which option flags are available for each displayed command.
For example:
git commit | Options: --amend, -a, --all, -am, -m

I have done some digging and think that the change would not take much work. Every command that does have an option has that indicated as an object within the hg and git commands.js

I would be happy to begin work on the issue and send in a pull request but I wanted to see if this matched your vision for the project first.

**Comment by pcottle** [comment]
I think that would be great to add! There might not really be a central place where all the options are defined but my memory might be hazy -- feel free to attempt a PR or comment back here if there's not an easy way to do it

**Comment by ryancraigdavis** [comment]
I have been digging around the files and I have found where the options are defined:

Within both the commands.js files for [Git](https://github.com/pcottle/learnGitBranching/blob/main/src/js/git/commands.js) and [Mercurial](https://github.com/pcottle/learnGitBranching/blob/main/src/js/mercurial/commands.js) each command that has options has an options object attached.

Following this chain, within the commands/index.js file found [here](https://github.com/pcottle/learnGitBranching/blob/main/src/js/commands/index.js) the Hg and Git commands are brought in and added to a variable called "commands" which is then exported. This commands variable does contain a function called getOptionMap that gets options for a command if they exist.

I was able to also find how/where the commands are added to the screen. It seems to be the section of code from lines 107-109 found in this [file](https://github.com/pcottle/learnGitBranching/blob/main/src/js/react_views/CommandView.jsx). My problem, however, is I am not very experienced in React, and could not really figure out how to change or trace what is being put into the div: <div class="commandLineResult">

Depending on how the react file is parsing the lists of commands, my thought is that the getOptionMap function referenced above could be used to grab the set of options for each command that DOES have options (with a simple if statement). The getOptionMap just needs the command name and vcs for each command it is called for (which is already found in what is being displayed). To me, this would be the easiest way to solve this, I just am not sure how the react is working. Any additional insihgt would be appreciated!

**Comment by pcottle** [comment]
Yeah so `CommandView` just renders some markup that it's given in the data container of the `command` prop -- so its really just something that converts markdown to HTML in the view.

Where we actually prepare that output is over here:
https://github.com/pcottle/learnGitBranching/blob/main/src/js/sandbox/commands.js#L116-L129

using this method:
https://github.com/pcottle/learnGitBranching/blob/main/src/js/sandbox/commands.js#L164-L171

I think inside there you might have access to options? let me debug and see

**Comment by pcottle** [comment]
Alright this is what I was able to get with the referenced PR
<img width="379" alt="Screen Shot 2021-06-10 at 8 47 12 AM" src="https://user-images.githubusercontent.com/1135007/121546429-83fd7480-c9c8-11eb-9ff6-839f8ad8d28a.png">

**Comment by pcottle** [comment]
It's not great since there's no context for each option -- but is this what you had in mind?

**Comment by ryancraigdavis** [comment]
Yeah that's exactly what I was thinking! To me it seems obvious from context that these are the available flags? But I suppose if someone were completely new to Git they might not understand that

**Comment by pcottle** [comment]
ok cool, ill go land this then

**Comment by pcottle** [comment]
Sorry to steal the PR from you but debugging how this would work was 95% of the implementation :P
