### ISSUE TITLE
Difficult to read contrast

### ISSUE THREAD

**Issue by j1elo** [pcottle/learnGitBranching#849]
Hi, thanks for this very nice interactive reading experience! The single most painful bit that I missed about 0.5 secs of starting was autocomplete, but I see there is an issue already for it.

Meanwhile, I'd like to report a background color that made a git tag very hard for me to read. It is the "HEAD" tag on the "A Mixed Bag" Level 4:

![image](https://user-images.githubusercontent.com/1824582/121824316-a682dc80-ccab-11eb-9970-027c885cce8c.png)

I really had difficulties reading the black text on top of such dark blue background. For me it all seems like if there was no text inside. So I'd like to kindly ask for reviewing those tags that use dark-ish colors for backgrounds, and consider either changing them to lighter alternatives, or even changing the text color to white (albeit I think that's a worse choice because it might make people think the tag with white letters is special for some reason). In any case, looking to keep a good amount of contrast between text and background.

Thanks again!

**Comment by pcottle** [comment]
Good point! I think this is hardcoded and I can tweak the color a bit

**Comment by pcottle** [comment]
<img width="1122" alt="Screen Shot 2021-06-13 at 5 10 51 PM" src="https://user-images.githubusercontent.com/1135007/121824576-59cae180-cc6a-11eb-8fc0-cb5ec9459b7f.png">
this better?

**Comment by pcottle** [comment]
Commit is attached -- feel free to tweak the color if you prefer something else.

It's a little less contrasting against the background now but it is certainly more readable

**Comment by j1elo** [comment]
Hi, yes, the one on the left is much easier to read!! thank you very much
