### ISSUE TITLE
Help for those who get stuck in a level?

### ISSUE THREAD

**Issue by tabbykatz** [pcottle/learnGitBranching#851]
Hello,

I love this tool and have no real complaints or issues, but I saw that you were receptive here and wanted to ask if there are resources for someone (okay, it's me!) who is stuck on a more advanced level. At this point I have tried so many commands I would just be guessing if I solved it, and going back through the entire tutorial has not helped this thick skull of mine. 

All this to say, are the walkthroughs/ solutions for the levels? ***Thanks!***

**Comment by pcottle** [comment]
try `show solution` :)

`show commands` also lists this as one of the commands you can try

**Comment by tabbykatz** [comment]
Thank you!
