### ISSUE TITLE
[IDEA]To set up a problem-solving column?

### ISSUE THREAD

**Issue by qyingkou** [pcottle/learnGitBranching#853]
Thank you for your awesome project.

Can we set up a problem-solving column and set up many common topics in our work? 
For example, soluting the code conflict between the local and remote repos, these should be very good.

Can you consider adding it?

**Comment by pcottle** [comment]
Hi, thanks for dropping by. I'm not quite sure what you're asking -- do you want to set up one of the discussion forums that GitHub supports? Or do you want to create a lesson?

**Comment by qyingkou** [comment]
Thanks reply, pcottle, I want to say "creating lessons"！
Add a new set  in the "Select a level" panel, naming "Practice" or "Challenge" ? (like Main and Remote) .

Different from the previous lessons, this time we solve real  problems at work.
For example, from the perspective of feature developer and branch manager, to write games of different levels of difficulty

**Comment by pcottle** [comment]
Oooh I see. Yeah that could be a beneficial learning exercise but there are actually other educational lessons out there that do exactly this. They have you download an actual git repository and work through resolving issues within local files on your real computer. That's a different type of learning but it's probably not best for this resource to get into that type of study. We can only simulate the very basics of git in the browser and not much else.
