### ISSUE TITLE
A mixed Bag level 1 Solution

### ISSUE THREAD

**Issue by Hellogark** [pcottle/learnGitBranching#854]
I'm a bit confused with the solution, i don't know what is --solution-ordering, i haven't seen anything about that in the site, neither in the git docs about rebase. 

If i send `git rebase -i main C4` the HEAD only moves to C4* and then if i send `git rebase bugFix main` bugFix and main moves to C4 and not to C4*, but including --solution-ordering  it works as the solution.

**Comment by pcottle** [comment]
the `--solution-ordering` is just a way to "use" interactive rebase but specify the exact ordering, since we can't launch the dialog and interact with it when demonstrating the solution.

**Comment by pcottle** [comment]
<img width="997" alt="Screen Shot 2021-07-08 at 4 02 21 PM" src="https://user-images.githubusercontent.com/1135007/124996306-f2ecde00-e005-11eb-9462-39ae43f08a29.png">
it should look like this. then just move the `main` branch to the new commit and the level will be solved
