### ISSUE TITLE
Add Traditional Chinese (zh-TW) Language

### ISSUE THREAD

**Issue by wastu01** [pcottle/learnGitBranching#867]
it will be nice foe those who want learn git in Taiwan like me

**Comment by pcottle** [comment]
Yep I could see this being nice to have -- we rely on the community for these translations so if you're capable, feel free to start 😇 otherwise we can keep this open to track

**Comment by iamqiz** [comment]
啊不会吧,台湾人看不懂简体字吗 我没学过繁体字,也能看懂繁体字

**Comment by yu000291** [comment]
hahahahahahah

**Comment by wastu01** [comment]
:)

**Comment by waldyrious** [comment]
I'm a bit puzzled by this issue — wasn't zh-TW added back in 2014 with #167 and #169?
