### ISSUE TITLE
Add `git switch` Note in  Chinese (zh-CN) Language

### ISSUE THREAD

**Issue by masterX89** [pcottle/learnGitBranching#898]
Hello, I notice a note is missing in the chinese site.

> In Git version 2.23, a new command called `git switch` was introduced to eventually replace `git checkout`.

This message shows in the English language site as a **NOTE**, but didn't show in the Chinese language site.

Maybe we should add this message to inform developers in China.

**Comment by pcottle** [comment]
Yeah that would be great! The English content is here:
https://github.com/pcottle/learnGitBranching/blob/main/src/levels/intro/branching.js#L121

so I think we would just need to add a new modal in the translation here:
https://github.com/pcottle/learnGitBranching/blob/main/src/levels/intro/branching.js#L840

feel free to try out the changes!
