### ISSUE TITLE
Elongated display of branch names

### ISSUE THREAD

**Issue by web-steel** [pcottle/learnGitBranching#901]
<img width="1439" alt="bug" src="https://user-images.githubusercontent.com/20759739/143555030-9adf6d50-1d89-45ee-92e8-b0e6e5df593e.png">

When tasks with a large number of branches, the names overlap all commits

**Comment by pcottle** [comment]
hrm thats very very odd, what browser are you using? i havent seen this in any of the lessons we have built-in

**Comment by SphereBread** [comment]
Same on "Grabbing Just 1 Commit"
Chrome 96.0.4664.45
![image](https://user-images.githubusercontent.com/48400794/143720577-0a2bc777-ed47-4e7a-9be5-3c75cc1c055e.png)

**Comment by web-steel** [comment]
> hrm thats very very odd, what browser are you using? i havent seen this in any of the lessons we have built-in

Chrome 96.0.4664.55

**Comment by pcottle** [comment]
oh I'm seeing this now too, it must be some kind of regression in chrome or the library I use to draw the shapes. Let me check...

**Comment by pcottle** [comment]
Have a fix!
<img width="1058" alt="Screen Shot 2021-11-28 at 7 40 02 PM" src="https://user-images.githubusercontent.com/1135007/143783364-d5f32177-4cfd-4d5f-b300-8a717aed99b8.png">

**Comment by pcottle** [comment]
```
      h: textNode.clientHeight
      h: textNode.getBoundingClientRect().height,
    });
```

**Comment by 0x6d64** [comment]
I have a similar issue with tag names, Browser is Chrome 97.0.4692.71 (Windows). Image:

![image](https://user-images.githubusercontent.com/1077899/148216907-cddb24f0-ee7b-424f-9366-6453b056407f.png)

**Comment by pcottle** [comment]
Probably the same exact fix, just a second

**Comment by pcottle** [comment]
looks good now:
https://learngitbranching.js.org/?NODEMO&command=git%20tag%20foo
