### ISSUE TITLE
Mobile friendly version

### ISSUE THREAD

**Issue by cveld** [pcottle/learnGitBranching#906]
Are you planning for a mobile friendly version?
It could be done with some kind of touch interface where one can touch commands together.
[git] [commit]
[git] [checkout] [select-a-branch-from-the-list]
[git] [checkout] [pick-head-pick-~-pick-1]

**Comment by pcottle** [comment]
Probably not anytime soon, I figure this type of educational content is better suited for desktop. Most folks use git on desktop as well. Maintaining both doesn't sound super fun either :P

**Comment by cveld** [comment]
I don't completely agree ;-)   I guess it would be quite cool to be able to discuss git operations anywhere anyplace.   Maybe in future we will find someone who is willing to take this challenge.
