### ISSUE TITLE
git diff support

### ISSUE THREAD

**Issue by cveld** [pcottle/learnGitBranching#907]
Recently I bumped into the commands `git diff head~1`, `git diff head^`, 'git diff head^^'. Still learning, no clue what this is exactly doing. It would be great if your tool would help in discovering the details.

_In the meanwhile I discovered what was blocking me, cmd.exe requires me to escape carets! So `git diff head^` must actually be entered as `git diff head^^`... To add to the confusion :-)_

**Comment by pcottle** [comment]
Ah yeah, `git diff` never mutates the graph so it's not quite relevant for this educational content. It also only makes sense when you have a sense of what changes are included in what commit (and on what files), so we would need to simulate a lot more.

you can try `git show` to see an example of a command that's not really worth simulating, with some trivial example output
