### ISSUE TITLE
Inconsistent pacing and lack of exercises

### ISSUE THREAD

**Issue by HeavyBulb** [pcottle/learnGitBranching#908]
The pacing of the course is inconsistent, which can be confusing and frustrating. For example, the first level of the second chapter is literally just typing `git checkout C4` which is easier than expected. The level afterwards is a bit more difficult because you have to understand that the checkout is somehow important. The third level is a sudden huge leap in difficulty, as you have to not just navigate through the branches but move them around in a combined matter. Additionally, you have to remember concepts and commands that are only introduced in a single exercise, so that they are not mastered or grasped sufficiently yet. Furthermore, it is not explained to why the `branch` command does not open up a new branch in this exercise but move the branches around. That should be clarified.

My suggestions are:

- add more exercises or give the options to do exercises between the levels
- add hints to already learned commands

**Comment by pcottle** [comment]
It's fair feedback that the pacing is inconsistent; I had to balance the difficulty of a lesson with the topic that a lesson contained. I usually went with the latter, which means that each lesson covers a certain concept but some of the lessons are very very easy -- up until when you need to use all the building blocks together, and the lesson becomes hard.

I don't have the time to do a major overhaul of the content (and that would involve shuffling all the translations as well) so I'll close the issue, but feel free to send some PRs to address this if you'd like!
