### ISSUE TITLE
[Feature Request] Crowdsource level ideas

### ISSUE THREAD

**Issue by alexzhaohong** [pcottle/learnGitBranching#909]
Great resource that I used in 2019, and have now used to teach someone else. It's great for developing a mental model! 

Was wondering if we could have a "Community Created Levels" section in the readme so that we could easily contribute PRs to this project (Using the gist links would be easier than creating an entire interface, not to mention it would be more of an "unofficial tutorial")

We could demonstrate different collaboration set-ups and workflows, such as the [workflows detailed by Atlassian](https://www.atlassian.com/git/tutorials/comparing-workflows)

Here is an example:

## Community Created Levels
Feel free to open a PR with your level!

[Production vs Development](https://learngitbranching.js.org/?gist_level_id=a84407351f9c9f0cb241) by unknown
_Comparing Workflows 1: Centralized_ by @alexzhaohong
_Comparing Workflows 2: Feature Branches_
_Comparing Workflows 3: Gitflow_
_Comparing Workflows 4: Forking_
_Comparing Workflows 5: Truck-based and Feature Flags_

**Comment by pcottle** [comment]
> Was wondering if we could have a "Community Created Levels" section in the readme so that we could easily contribute PRs to this project (Using the gist links would be easier than creating an entire interface, not to mention it would be more of an "unofficial tutorial")

Totally, that would be a great idea! Want to submit the PR to edit the readme? I think encouraging folks to use the level builder (and they would get some actual distribution on their lesson) would nicely close the loop
