### ISSUE TITLE
Time to switch to switch?

### ISSUE THREAD

**Issue by oliviercailloux** [pcottle/learnGitBranching#915]
Thanks for this great tool that I use to [teach git](https://github.com/oliviercailloux/java-course/blob/master/Git/README.adoc) at [Paris-Dauphine University](https://dauphine.psl.eu/formations/licences/informatique-des-organisations/l3-methodes-informatiques-appliquees-pour-la-gestion-des-entreprises/formation).

This request is related to #750. git 2.23 was [released](https://en.wikipedia.org/wiki/Git#Releases) two and half years ago. May I suggest that it’s about time to switch the lessons to talk about `git switch` (and `git restore` where appropriate) instead of `git checkout`? I think that this would ease learning.

**Comment by pcottle** [comment]
That's fair feedback! Anecdotally though, adoption of new git commands (in my opinion) has been a little slow in industry, especially when they only provide a small layer of syntactic sugar over the existing commands. Most engineers I work with still use `git checkout` even though they know `switch` exists (for instance)

We have the reference to the `git switch` command in the branching level. If you want, you could add a custom level for your students via these instructions that focuses on it:
https://github.com/pcottle/learnGitBranching#level-builder

Switching over all of the lesson content seems just like a pretty big jump, and we might need to refresh all the various translations as well

**Comment by waldyrious** [comment]
I'm all for cleaner mental models for using git, but I'd point out that the [documentation for git switch](https://git-scm.com/docs/git-switch) still says

> THIS COMMAND IS EXPERIMENTAL. THE BEHAVIOR MAY CHANGE.

So perhaps learnGitBranching should at least wait until the experimental status is removed before considering replacing `git checkout` with it.

**Comment by vermiculus** [comment]
Dropping in some links from the mailing list regarding the experimental status of git-switch/git-restore:

* May 2020 on what the 'experimental' status means: [Re: Why are experimental commands git restore and git switch suggested in CLI output?](https://public-inbox.org/git/xmqqtv0yjngb.fsf@gitster.c.googlers.com/)
* May 2021 discussion on their continued experimental status: [Re: git switch/restore, still experimental?](https://public-inbox.org/git/CAPiPmQnb=XMaF2+YkryEbiX8zA=jwa5y=fbAGk9jpCExpbS4Rw@mail.gmail.com/).  These are interesting tidbits: [one](https://public-inbox.org/git/CABPp-BHBcjSQbkotrzwDtVRSC-qqjEyP4m=biY-0+=Jdg9ETQw@mail.gmail.com/), [two](https://public-inbox.org/git/877dkdwgfe.fsf@evledraar.gmail.com/), [three](https://public-inbox.org/git/nycvar.QRO.7.76.6.2105051554250.50@tvgsbejvaqbjf.bet/).

That said, I don't think it's a bad idea for learnGitBrancing to advertise the possible use of git-switch -- even if only to garner the usability feedback that the Git project needs. But maybe that's a bad reason to put something into training materials 😄

**Comment by pcottle** [comment]
Thanks for the great links @vermiculus, I really agree with the following:

> Which leaves us with two hard choices regarding switch/restore, none of
them really being comfortable:

> - we scrap switch/restore because their usability is not really all that
  improved relative to `git checkout`.

> - we leave switch/restore as-are (because by now, changing the options or
  the design would be almost certainly disruptive to users who already
  tried to adopt the new commands, I being one of those users).

I think it's too late to improve `switch`'s usability, but it hasn't seen the huge jump in adoption that I expected (maybe due to some of the usability issues in the thread). As long as the majority of industry still uses `checkout`, I'd rather stick with that (and let folks play around with switch in sandbox mode if they want) rather than be the first to update all the lessons and be out of sync with the wider community.

Put another way -- I'd rather this resource be helpful for new students/interns/beginners that have to use `checkout` since other references use that, than be on the bleeding edge of git adoption.

**Comment by waldyrious** [comment]
I don't understand the argument against changing the behavior of `git switch` as Ævar suggested in [their post](https://public-inbox.org/git/877dkdwgfe.fsf@evledraar.gmail.com/), which I totally agree with. I mean, what's the purpose of an experimental marker (which explicitly says, in all caps, "THE BEHAVIOR MAY CHANGE"), if not to allow precisely that kind of improvement?

**Comment by pcottle** [comment]
>  I mean, what's the purpose of an experimental marker (which explicitly says, in all caps, "THE BEHAVIOR MAY CHANGE"), if not to allow precisely that kind of improvement?

I think despite having this warning, it's hard for humans not to build muscle/mental memory when learning new tools. If someone just changed the behavior of most of the `git switch` options overnight with a new git release, that'd probably produce a lot of angst/frustration for folks who have been using the command for a while and built up muscle memory. And keep in mind it's not like a web release -- the behavior might vary between machines for a single person depending on the version of git.

So it's an interesting tradeoff -- experimental commands should leave the space for changes down the line but after enough time and adoption, those changes come at a cost. It's just like google products being in "beta" for years -- after you have 100 million users, changing something comes at a cost :P

**Comment by waldyrious** [comment]
I understand where you're coming from, but I would say that if the feature has reached that point, then the experimental/beta label should be removed; otherwise, they don't really mean anything.

But that's all beside the point, since it's a decision to be taken by the git project itself — regarding learnGitBranching, I agree that it should remain using `checkout` until the situation is clarified upstream.

**Comment by pcottle** [comment]
Agreed! Thanks everyone for keeping a pulse on this 🙌🏻

(not the same exact thing but our switch to `main` from `master` was a time where I was excited to match the industry movements)

**Comment by vermiculus** [comment]
Interesting tidbit I noticed today. The advice for detached HEAD recommends `git-switch`:

```
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false
```

If git's advice mechanisms are recommending `git-switch`, I wonder if that changes the calculus here at all.

**Comment by pcottle** [comment]
Yeah that's interesting 🤔 I wonder how many of the git errors and help pages recommend checkout vs switch.

even looking at `git help`, there's no mention of checkout at all!

```
grow, mark and tweak your common history
   branch            List, create, or delete branches
   commit            Record changes to the repository
   merge             Join two or more development histories together
   rebase            Reapply commits on top of another base tip
   reset             Reset current HEAD to the specified state
   switch            Switch branches
   
```

**Comment by vermiculus** [comment]
I'm surprised by that `git help` piece -- and that's an even stronger argument to 'switch to switch' here than the advice stuff. One of the goals of any tutorial should be to build trust in and encourage (or at least not discourage) the use of built-in help facilities.

**Comment by oliviercailloux** [comment]
Perhaps we should tell git developers that we are wondering about the status of these commands and somehow (with as much tact as possible) make it understood that the current situation is quite unsatisfactory. It is understandable to want to gather opinions and to not rush decisions so that a good API is built, but it’s now been a very long time. From the discussions referred to [here above](https://github.com/pcottle/learnGitBranching/issues/915#issuecomment-1023719362), it seems that they themselves do not really know which direction to take, but (from a cursory reading) I doubt that waiting more will help. I think they should simply take a decision.

I’ve been wanting to write such an e-mail to their mailing list, but could not find the time yet to phrase things as nicely as can be so as not to hurt anyone.

**Comment by pcottle** [comment]
I already have a disclaimer here:
<img width="1007" alt="Screen Shot 2022-02-24 at 1 58 03 PM" src="https://user-images.githubusercontent.com/1135007/155606525-bff39d67-0a86-4b1c-b21f-eba07f77ab33.png">

with the link pointing to here:
https://git-scm.com/docs/git-switch

should I maybe just update that language? I would bet most folks have access to git switch now, but its just a matter of what command they prefer (and what command their teammates use)

**Comment by waldyrious** [comment]
I would suggest replacing "....because most people won't have access to `switch` yet" with "...because the `switch` command is still experimental and the syntax may change in the future". I think that better reflects the reality of the situation.

**Comment by pcottle** [comment]
<img width="708" alt="Screen Shot 2022-03-01 at 9 11 24 AM" src="https://user-images.githubusercontent.com/1135007/156205403-3da6da12-ad3c-4d40-92a9-349363411e3a.png">
