### ISSUE TITLE
"--no-off" is not supported

### ISSUE THREAD

**Issue by DB-db-dron** [pcottle/learnGitBranching#919]
It would be great if the `--no-ff` option is introduced. I was trying to visualize this when I found out that was not supported. It is really disappointing.

**Comment by pcottle** [comment]
I think it is supported for merge:
https://learngitbranching.js.org/?NODEMO&command=git%20checkout%20-b%20other;%20gc;%20git%20switch%20main;%20git%20merge%20other%20--no-ff
compared to:
https://learngitbranching.js.org/?NODEMO&command=git%20checkout%20-b%20other;%20gc;%20git%20switch%20main;%20git%20merge%20other%20

did you mean something else?
