### ISSUE TITLE
git commit command line still not working 

### ISSUE THREAD

**Issue by Hyunwooksuh** [pcottle/learnGitBranching#930]
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/65224203/155145526-3deb258f-135f-4fb3-b9e0-dc2453c895e8.png">

**Comment by pcottle** [comment]
<img width="733" alt="Screen Shot 2022-02-22 at 7 03 42 AM" src="https://user-images.githubusercontent.com/1135007/155147940-a369777c-aa75-4539-8079-79b4d9edc618.png">

**Comment by hong4rc** [comment]
> [e987b9b](https://github.com/pcottle/learnGitBranching/commit/e987b9b6ab79abc551f89860d0d74074826d07e6) and [63b07c0](https://github.com/pcottle/learnGitBranching/commit/63b07c03a425575904118ab664e7ae9e9b172c94) should fix this.
> 
> sorry @hong4rc, I'm about to leave town so I'll try to get the website working and then we can do a proper fix of the `marked` dependency


I got this error before my commit, so I create #925 to fix it, can you check code built for `gh-pages` is merged with my code?

![image](https://user-images.githubusercontent.com/19208123/155153685-c003c3a8-a506-4dfc-94a7-42357a770ff6.png)


https://hong4rc.github.io/learnGitBranching/ is my build

**Comment by Hyunwooksuh** [comment]
Thank you again for your amazing application!

**Comment by pcottle** [comment]
@hong4rc hrm that's possible, let me try another double revert. maybe i hadn't pulled down your changes and pushed the commit before

**Comment by pcottle** [comment]
Hrm, I still get an error when not using the `?NODEMO` link, even after including your changes @hong4rc. Maybe there's one more missing update?
<img width="723" alt="Screen Shot 2022-02-22 at 12 26 15 PM" src="https://user-images.githubusercontent.com/1135007/155204352-e3954cbd-6a8b-4fc4-b324-4a9a1e10b86c.png">

its with these changes
![Uploading Screen Shot 2022-02-22 at 12.27.50 PM.png…]()

**Comment by pcottle** [comment]
you're welcome @Hyunwooksuh and apologies for the breakage!
