### ISSUE TITLE
Ramping up-relative refs No. 2 solution 

### ISSUE THREAD

**Issue by s3496168** [pcottle/learnGitBranching#948]
Hello, and thank you for creating this!

I seem to have difficulty understanding the solution for activity 7 (Ramping up-relative refs No. 2). Particularly the line 'git branch -f main C6'. Could you please direct me (and maybe others) to which lesson this technique is covered in? I can't seem to find it and I would like to understand how this works. 

Kind regards,
Brearne

**Comment by pcottle** [comment]
<img width="721" alt="Screen Shot 2022-03-14 at 9 28 32 AM" src="https://user-images.githubusercontent.com/1135007/158205512-bff6d70c-6286-4ae6-bfd0-d1f4634a174c.png">
its in the exact same lesson (relative refs #2)

**Comment by pcottle** [comment]
were you using a different locale that perhaps didnt have this translation available?
