### ISSUE TITLE
How to completely build in offline env?

### ISSUE THREAD

**Issue by JiangHanChao** [pcottle/learnGitBranching#954]
### Environment
we had the basic construction files:
1. Ubuntu 20.04
2. learnGitBranching-main.zip and unzip (offline download)
3. nodejs (node, npm, npx install by proxy install from local mirror web)
4. yarn (install by npm)
5. set the npm and yarn registry config proxy to local mirror web
6. gulp-cli (install by npm)

### install
when we run `yarn install` cmd then it blocks due to network can't connect (offline):
```
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
```

How can I get a offline-install package that no need connect to network for downloading pkg? 

And thanks for the good project.

**Comment by pcottle** [comment]
I think there are separate instructions for making yarn work offline:
https://classic.yarnpkg.com/blog/2016/11/24/offline-mirror/
