### ISSUE TITLE
`git gc` implementation

### ISSUE THREAD

**Issue by thetayloredman** [pcottle/learnGitBranching#957]
It would be cool if LGB had a little tiny garbage-collector. Nothing fancy with packs, just to remove all of the commits not pointed to by a branch. I could *probably* implement this.

**Comment by pcottle** [comment]
I wouldn't be opposed to this, but I'm not sure if there's a lot of educational value in having this functionality. Most beginners using git can get by without running garbage collection for their side projects.

Could be a neat little hidden feature though
