### ISSUE TITLE
Feature [Add a button to revert the animation ]

### ISSUE THREAD

**Issue by RaheemAmer** [pcottle/learnGitBranching#972]
Could you please add a button to revert the animation, cuz sometimes I need to repeat the whole thing again to summarize what I understood, so I end up returning to the previous page to repeat the animation all over again 

I think this is gonna be a cool thing to add, feel free to share your opinion, and thank you so much for this amazing project 😄 

Much appreciated 💟

**Comment by pcottle** [comment]
Hrm, yeah we have the ability to `undo` in the command line which snaps a tree back to a previous version. Seems like it would be possible to do the same here.

I'll leave this open for now -- it's a small-to-medium feature to implement (just need to add a button and manage some state in the git tree based on that). Hope someone volunteers!

**Comment by RaheemAmer** [comment]
Thank you ❤️

**Comment by Netz00** [comment]
I assume it is the animation inside level demonstration.

If that is the case, the following image would solve the issue (play animation button changes to reset button).

![after](https://user-images.githubusercontent.com/49691921/235619463-3b749505-7697-4e13-920a-4f1e3ced7aa8.png)

**Comment by Netz00** [comment]
I opened PR for issue [here](https://github.com/pcottle/learnGitBranching/pull/1072).

**Comment by pcottle** [comment]
Thanks so much for submitting a PR! I'll go review it now
