### ISSUE TITLE
Remote Lesson 8, Solution/Lesson Bug: Local-Main Moves In Solution, But Not In Lesson.

### ISSUE THREAD

**Issue by Connor-Skudlarek** [pcottle/learnGitBranching#975]
Sorry. New to Git/GitHub. I'll try to give as much detail as possible. I'm 99% sure this is a bug, but might be doing something wrong.

If you follow the solution to remote, lesson 8 "Locked Main" it goes like so:

`git checkout -b feature C2`   // Creates a feature branch at commit 2
`git push origin feature`         // Pushes the feature branch to remote, tracks origin feature branch at C2 in local branch

In the solution this also moves local-main to C1. When actually performed by the user, it leaves local-main at C2.

**Comment by fish-404** [comment]
Actually, the solution has three commands.  And if you loss the first command, the level won't show solved.
``` bash
git reset --hard o/main
git checkout -b feature C2 
git push origin feature
```

**Comment by Connor-Skudlarek** [comment]
> Actually, the solution has three commands. And if you loss the first command, the level won't show solved.
> 
> ```shell
> git reset --hard o/main
> git checkout -b feature C2 
> git push origin feature
> ```

Oh, so that's not just part of resetting the terminal to show the solution? That is part of the solution?

Thanks for clearing that up.

**Comment by fish-404** [comment]
> > Actually, the solution has three commands. And if you loss the first command, the level won't show solved.
> > ```shell
> > git reset --hard o/main
> > git checkout -b feature C2 
> > git push origin feature
> > ```
> 
> Oh, so that's not just part of resetting the terminal to show the solution? That is part of the solution?
> 
> Thanks for clearing that up. I think the confusion is that there is a message right after it, so it looks like that's part of it prepping for a solution and explaining why you might use --hard.
> 
> Edit: I'll close the issue once I get confirmation that was my issue. But it does seem that it was not in fact a bug (the 1% strikes the noob, haha).

Hi, if you look at the terminal, you can find one command before the solution is `reset  --forSolution`, that's the part of resetting the terminal to show the solution. I think you can confirm this by use `show solution` and observe the terminal in other levels. 

Yeah, I think you are right, maybe the message confused and mistooken you to think the first command in solution is for resetting the level.  😊
