### ISSUE TITLE
Level 8 from Push & Pull -- Git Remotes!  does not check as completed

### ISSUE THREAD

**Issue by Lwao** [pcottle/learnGitBranching#984]
Level 8 from Push & Pull -- Git Remotes!  does not check as completed when typed the command "show solution" or when actually solved.

**Comment by pcottle** [comment]
<img width="1279" alt="Screen Shot 2022-07-20 at 5 38 10 PM" src="https://user-images.githubusercontent.com/1135007/180100466-7490b51c-a107-4a77-b3b0-9baffb6bdf53.png">
are you sure? I did `show solution` and it worked and played the animation

**Comment by Lwao** [comment]
I tried a couple of times in Firefox (Ubuntu 20.04 LTS) and although the message "Solved!! :D" popped, it did not registered in the `$levels` menu.

**Comment by pcottle** [comment]
oh we use cookies to do that, you might have cookie storage off? Or firefox might prevent cookies by default

**Comment by Lwao** [comment]
Okay. But it only happens to this specific level. 

Thank you!

**Comment by vasiunov** [comment]
Have a good day, GitMasters!
I discovered kind of a bug in level 8 from Push & Pull:
1st screenshot is initial moment (local main is on c2)
![image](https://user-images.githubusercontent.com/112346049/216840579-76d85f1b-0f21-4782-8a55-1249e17b3067.png)

2nd screenshot is authors' solution (local main is on c1)
![image](https://user-images.githubusercontent.com/112346049/216840624-c2df6dfb-f8c6-4193-bd4f-4c70f9d7904d.png)

As for me solution commands don't change c2 to c1 for local main. Also I tried solution commands manual and it didn't work (3rd screenshot)
![image](https://user-images.githubusercontent.com/112346049/216840748-bb107211-e539-4030-87b5-f8a1a34fd6ba.png)

**Comment by pcottle** [comment]
hrm it worked for me?

<img width="1312" alt="Screenshot 2023-02-06 at 7 46 50 PM" src="https://user-images.githubusercontent.com/1135007/217135203-7271246e-7f72-4e9e-93c0-3d1436f2f071.png">

**Comment by vasiunov** [comment]
> hrm it worked for me?
> 
> <img alt="Screenshot 2023-02-06 at 7 46 50 PM" width="1312" src="https://user-images.githubusercontent.com/1135007/217135203-7271246e-7f72-4e9e-93c0-3d1436f2f071.png">

Could you print solution commands? If I use "solution" everything OK, but if I print this commands manually I get the 3rd screenshot
