### ISSUE TITLE
Reassign or at least disable ctrl-w combination

### ISSUE THREAD

**Issue by david-shiko** [pcottle/learnGitBranching#993]
"ctrl-w" combination is "remove last word" combination on *nix systems and most git consoles. 
But in browsers this is combination to close current tab ://

Well which one combination we should choose for users?
IMO by imitating/pretending git service and git console - we should imitate git shortcuts as well. 
So the best way - is to reassign  ctrl-w combination to git behavior, the temporary solution is just disable this combination.

I just closed about 10 times my level tab just because tried erase the last word :)
It's really annoying. BTW in most web consoles that I met "ctrl-w" combination conforms with *nix rather than browser behavior.

**Comment by pcottle** [comment]
Yeah I'm totally supportive of this -- sadly it looks like it's not quite possible though. The most we could do is hook into the beforeunload event (which helps catch accidental closes):
https://stackoverflow.com/questions/21695682/is-it-possible-to-catch-ctrlw-shortcut-and-prevent-tab-closing

thoughts?

**Comment by david-shiko** [comment]
I'm not a web developer but IMO the specified solution looks adoptable for this case.

**Comment by pcottle** [comment]
Ok I'll try that -- fwiw I made it so it only warns if you're in the middle of solving a level and not just all the time.

**Comment by pcottle** [comment]
(so its not overly annoying)
