### ISSUE TITLE
Docker image/build instructions

### ISSUE THREAD

**Issue by brandonmcclure** [pcottle/learnGitBranching#998]
I would like to run a copy of this website locally so that I can build out levels while I will be traveling and not have a solid internet connection. I would like to be able to docker run and pull a publicly available image of this app behind a minimal web server. 

I built this out and submitted PR #997 to push the built image to the github container registry.  I included a Makefile that has a dependency on powershell core, but demos out how to use the multi stage build to retrieve the built files. 

The powershell can be dropped out and keep the docker functionality, with less robust tagging. I think there is value in keeping the build process as simple and transparent as possible.

**Comment by pcottle** [comment]
> to run a copy of this website locally so that I can build out levels while I will be traveling and not have a solid internet connection. 

Hrm, but we can do that today pretty easily right? All you have to do is run `yarn gulp fastBuild && open ./index.html` build and run the latest version.

Is there another benefit of the docker build? Sorry just trying to figure out if this makes sense to encourage others to use.

In the meantime I clarified the README a little bit to point people to the build + open command earlier.

**Comment by brandonmcclure** [comment]
No worries at all. I do not know if it makes sense to encourage others per se. I think the Gitpod instructions should be encouraged over docker. 

I like using docker to build from source, so i do not need to manage all of the build dependencies on my daily computer. This build process is elegantly simple so there is not a huge need to containerize it, but I am stubborn and do not want to install yarn :-)

**Comment by brandonmcclure** [comment]
closing this issue since the related PR was merged.
